[msg MSG_BTLSTART_001 [Mona]]
[s][bup 0 3 5 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Ngh... we're surrounded![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Mona]]
[s][bup 0 3 5 0 0][vp 8 0 2 1003 0 3][f 4 10 65535 0 0]You guys just HAD to come swarming[n]out...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Mona]]
[s][bup 0 3 3 0 0][vp 8 0 2 1005 0 3][f 4 10 65535 0 0]There's more of them? This is bad...[n][f 1 3 65535][w][e]

