[msg MSG_BTLSTART_002 [Skull]]
[s][bup 0 2 122 65535 0][vp 8 0 2 1002 0 2][f 4 10 65535 0 0]Kamoshida's cognition ain't changin',[n]right? Then I'll act like the troublemaker[n]I am![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Skull]]
[s][bup 0 2 102 65535 0]You guys have put me through a ton[n]of bullshit... I hope you're ready for[n]pain![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Skull]]
[s][bup 0 2 122 65535 0][vp 8 0 2 1003 0 2][f 4 10 65535 0 0]Let's do this, Captain Kidd![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Skull]]
[s][bup 0 2 102 65535 0][vp 8 0 2 1005 0 2][f 4 10 65535 0 0]Yeah, impossible, right? You picked a[n]fight with the wrong guy, dipshit![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_009 [Skull]]
[s][bup 0 2 101 65535 0][vp 8 0 2 1008 0 2][f 4 10 65535 0 0]It just proves that Kamoshida ain't[n]anything special.[n][f 1 3 65535][w][e]

