[msg MSG_BTLSTART_003 [Skull]]
[s][bup 0 2 0 65535 0]Hell yeah! They're all down![n]Wanna beat 'em up?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Skull]]
[s]Let's all attack 'em at the same time![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Mona]]
[s][bup 0 3 0 0 0]Or, we could approach them in[n]conversation and demand things[n]of them.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Skull]]
[s][bup 0 2 0 65535 0]Either way, surprisin' 'em or hittin' their[n]weaknesses to knock 'em down is a[n]good thing![n][f 1 3 65535][w][e]

