[msg MSG_BTLSTART_004 [Mona]]
[s][bup 0 3 5 0 0][vp 8 0 2 1004 0 3][f 4 10 65535 0 0]Ngh! The fact he's an infamous cheater[n]isn't just for show...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Mona]]
[s][bup 0 3 5 0 0][vp 8 0 2 1005 0 3][f 4 10 65535 0 0]It's no good if we continue this! Let's[n]withdraw once and come up with a[n]countermeasure![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Oracle]]
[s][bup 0 8 602 0 0][vp 8 0 2 1006 0 8][f 4 10 65535 0 0]Look at him, acting all smug because[n]of his cheats...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 0 2 1007 0 8][f 4 10 65535 0 0]We can't do anything to him at this rate[n]though. Let's retreat for now and[n]rethink our approach.[n][f 1 3 65535][w][e]

