[msg MSG_BTL_START_001 [Panther]]
[s][bup 0 4 104 0 0][vp 8 2 2 6132 0 0][f 4 10 65535 0 0]Joker, let's try talking to her. Maybe we[n]can calm her down![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0 [Panther]]
[s][bup 0 4 104 0 0][vp 8 2 2 6039 0 0][f 4 10 65535 0 0]What!? She just healed herself![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0_2 [Panther]]
[s][bup 0 4 100 0 0][vp 8 2 2 6132 0 0][f 4 10 65535 0 0]Hey Joker, let's see if we can calm her[n]down! It might be easier to change her[n]heart that way![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP_FIRST [Panther]]
[s][bup 0 4 100 0 0][vp 8 2 2 6132 0 0][f 4 10 65535 0 0]Okay! Looks like we can talk to her now![n]Let's try and get through to her![n][f 1 3 65535][w][e]

[msg MSG_BTL_MORE_BOKO [Panther]]
[s][bup 0 4 100 0 0][vp 8 2 2 6132 0 0][f 4 10 65535 0 0]We aren't getting anywhere like this...[n][f 1 3 65535][w][e]
[s][bup 0 4 100 0 0]Looks like we'll have to weaken her a[n]little more![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_001 [Panther]]
[s][bup 0 4 100 0 0][vp 8 2 2 6132 0 0][f 4 10 65535 0 0]Looks like we couldn't convince her! We[n]might need to think of something else.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Panther]]
[s][bup 0 4 103 0 0][vp 8 2 2 6027 0 0][f 4 10 65535 0 0]But... I do know.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_002 [Panther]]
[s][bup 0 4 103 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Shiho told me that you're the one she[n]trusts the most on the volleyball team.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_001 [Panther]]
[s][bup 0 4 104 0 0][vp 8 2 2 6132 0 0][f 4 10 65535 0 0]Looks like we couldn't convince her! We[n]might need to think of something else.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_001 [Panther]]
[s][bup 0 4 104 0 0][vp 8 2 2 6132 0 0][f 4 10 65535 0 0]Looks like we couldn't convince her! We[n]might need to think of something else.[n][f 1 3 65535][w][e]

[msg MSG_BTL_END_000 [Panther]]
[s][bup 0 4 103 0 0][vp 8 2 2 6038 0 0][f 4 10 65535 0 0]You were jealous of Shiho, weren't you?[n][f 1 3 65535][w][e]

[msg MSG_BTL_END_002 [Panther]]
[s][bup 0 4 103 0 0][vp 8 2 2 6130 0 0][f 4 10 65535 0 0]You were envious of Shiho because[n]the teacher you admired only ever[n]acknowledged her.[n][f 1 3 65535][w][e]

[msg MSG_BTL_END_004 [Panther]]
[s][bup 0 4 100 0 0][vp 8 2 2 6038 0 0][f 4 10 65535 0 0]You were suffering... and so was[n]the person you were jealous of.[n][f 1 3 65535][w][e]

[msg MSG_BTL_END_005 [Panther]]
[s][bup 0 4 103 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]You weren't the only person who felt[n]betrayed by someone you admired.[n][f 1 3 65535][w][e]

[msg MSG_BTL_END_006 [Panther]]
[s][bup 0 4 100 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]But even despite everything, Shiho is still[n]trying to keep moving forward.[n][f 1 3 65535][w][e]
