[msg MSG_BTL_START_001 [Queen]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Joker, please try talking to her! I'm sure[n]we can calm her down if we talk things over![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0 [Queen]]
[s][bup 0 6 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Be careful, she healed![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0_2 [Queen]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Joker, please try talking to her! I'm sure[n]she'll calm down after talking about this![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_000 [Queen]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]People who bought coins from you are[n]stating that they're victims of your scam.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_000 [Queen]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]You call it "Virtual Currency," but it[n]sounds like it doesn't actually have[n]any monetary value.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_001 [Queen]]
[s][bup 0 6 105 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]It doesn't sound like that convinced her.[n]Try saying something else.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_000 [Queen]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]It's a trap to make it seem more legitimate,[n]isn't it?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_001 [Queen]]
[s][bup 0 6 105 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]It doesn't sound like that convinced her.[n]Try saying something else.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_000 [Queen]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]How are they supposed to sell them if[n]the only site where they can is always[n]under construction?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_001 [Queen]]
[s][bup 0 6 105 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]It doesn't sound like that convinced her.[n]Try saying something else.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_000 [Queen]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]And where do we buy items with the[n]points you created?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_002 [Queen]]
[s][bup 0 6 102 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]That is enough![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_003 [Queen]]
[s][bup 0 6 102 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]You might think you're being clever and[n]getting away with it, but what you're doing[n]is inhuman![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_001 [Queen]]
[s][bup 0 6 105 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]It doesn't sound like that convinced her.[n]Try saying something else.[n][f 1 3 65535][w][e]