[msg MSG_BTL_TALK_FIRST_001 [Skull]]
[s][bup 0 2 107 0 0][vp 8 2 2 7026 0 2][f 4 10 65535 0 0]I get idols are important... but that's[n]not everything in life, right?[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FIRST_002 [Skull]]
[s][bup 0 2 111 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]We need to tell 'im that there're[n]more important things in life.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FIRST_003 [Skull]]
[s][bup 0 2 100 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Here's the stuff we know 'bout him.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]"He's got no place at home" and[n]"He wants to get involved with his[n]kid's life, but he can't."[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FAIL_002_00 [Oracle]]
[s][bup 0 8 604 0 0][vp 8 2 2 9040 0 8][f 4 10 65535 0 0]Crap, he's going berserk![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FAIL_002_00_2 [Oracle]]
[s][vp 8 2 2 0 0 0][bup 0 8 602 0 0][f 4 10 65535 0 0]Think about what to say and try[n]again, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FAIL_003_00 [Oracle]]
[s][bup 0 8 604 0 0][vp 8 2 2 9040 0 8][f 4 10 65535 0 0]Whoa! He's real pumped all of a sudden![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_001_002 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 9135 0 8][f 4 10 65535 0 0]And that's what got you into idols...[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_001_003 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]He might think he stopped caring about[n]his family, but we all know that's not the[n]case.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_001_004 [Oracle]]
[s][vp 8 2 2 9158 0 3][bup 0 8 602 0 0][f 4 10 65535 0 0]Tell 'im, Joker.[n][f 1 3 65535][w][e]

