[msg MSG_BTL_START_001 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Joker! Let's try and talk her out of this! I'm[n]certain we'll be able to change her heart![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0 [Fox]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]She healed by retouching herself!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0_2 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Joker, let's try speaking to her! It might[n]be easier than fighting her![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_000 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Stop playing dumb and tell us the truth![n]Why did you end up plagiarizing?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_000 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]If you've traced something that's[n]copyrighted without permission,[n]then it is plagiarized work.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_001 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Correct, it is illegal.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_001 [Fox]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]She wasn't convinced by that, Joker![n]Let's take a different approach![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]You may be happy to have become[n]popular, but that popularity will[n]bring you harsher critics as well.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_002 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Fans start to expect more from you.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_001 [Fox]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]She wasn't convinced by that, Joker![n]Let's take a different approach![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]You were able to draw however you liked[n]in the beginning, but now you're limited[n]to drawing what the fans want to see.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_001 [Fox]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]She wasn't convinced by that, Joker![n]Let's take a different approach![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_001 [Fox]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]You start having sleepless nights. You stay[n]up late thinking to yourself "maybe I don't[n]have what it takes"...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_002 [Fox]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Plenty of authors have struggled with this[n]in the past, and I'm sure there'll be more[n]as time goes on...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_003 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]However, is that not the reason why[n]people continue to work hard?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_005 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]I understand the feeling of wanting to run[n]away. It takes an incredible amount of skill[n]to create something for others to see.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_006 [Fox]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]But you did something to ruin all the hard[n]work you built up. What were you even[n]trying to protect...?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_007 [Fox]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]I want you to try and recall what was most[n]important to you as an artist.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_001 [Fox]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]She wasn't convinced by that, Joker![n]Let's take a different approach![n][f 1 3 65535][w][e]