[msg MSG_BTL_START_001 [Mona]]
[s][bup 0 3 2 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Joker, try talking to him! I'm sure he'll[n]change his heart if he hears what we[n]have to say![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0 [Noir]]
[s][bup 0 3 4 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]What!? Did he just heal!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP00_000_000 [Noir]]
[s][bup 0 7 102 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]You might call it a miracle, but some[n]people are getting even sicker![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_000 [Noir]]
[s][bup 0 7 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Their illnesses weren't cured by the[n]ingredients in the drink.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_002 [Mona]]
[s][bup 0 3 4 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Looks like we couldn't convince him![n]We'll have to try a different approach![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_000 [Noir]]
[s][bup 0 7 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]I heard that you have the clients sign a[n]self-renewing contract?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Noir]]
[s][bup 0 7 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]If you were confident in the authenticity[n]of your products, you wouldn't have to[n]do something like that.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_001 [Mona]]
[s][bup 0 3 4 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Looks like we couldn't convince him![n]We'll have try a different approach![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_000 [Noir]]
[s][bup 0 7 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]You don't allow them to cancel the renewal[n]because of a loophole, right? People feel like[n]they can't fight back, so they just give up.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Noir]]
[s][bup 0 7 100 0 0]Do you have any proof that it causes[n]miracles?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_001 [Mona]]
[s][bup 0 3 4 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Looks like we couldn't convince him![n]We'll have to try a different approach![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_000 [Noir]]
[s][bup 0 7 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]You trick sick people by only showing[n]them the successful data right?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_001 [Noir]]
[s][bup 0 7 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]There's nothing wrong with a healthy[n]drink. It's you who needs to be brought[n]to justice![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_003 [Noir]]
[s][bup 0 7 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Food becomes cells, bones, and muscles...[n]In other words, we are what we eat.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_004 [Noir]]
[s][bup 0 7 102 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]If you can't show your customers any[n]sincerity, then you have no right to sell[n]them food! You should be ashamed![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_001 [Mona]]
[s][bup 0 3 4 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Looks like we couldn't convince him![n]We'll have to try a different approach![n][f 1 3 65535][w][e]