[msg MSG_BTLSTART_002 [Mona]]
[s][bup 0 3 4 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]I-Is that the Shadow from earlier!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Mona]]
[s][bup 0 3 4 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]Don't tell me... Did you take in the[n]Shadow's appearance and powers[n]as a Persona!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Mona]]
[s][bup 0 3 4 0 0][vp 8 0 2 1003 0 3][f 4 10 65535 0 0]Holy... Does that mean you can wield[n]multiple Personas?[n][f 1 3 65535][w][e]

