[msg MSG_BTL_FLYUNDER50_020_0 [Queen]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 6]That's our line! You had better be[n]prepared![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_002_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 3]Keep at it, Joker! Corner him![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_000_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1010 0 3]Show no mercy! Let's finish him![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_030_000 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1013 0 3]You're all buzz and no bite![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_090_002 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 3]A pig!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_110_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 3]Dammit! I didn't expect he'd have[n]something like this up his sleeve![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_120_005 [Queen]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 6]Joker! Make sure you have us regroup[n]if you think we're at a disadvantage![n][f 1 3 65535][w][e]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1023 0 6]That thing's a giant... If it attacks us[n]while we're at low stamina, we won't[n]survive![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_130_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1024 0 6]Joker! Have us regroup if you think[n]we're at a disadvantage![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1025 0 6]We need to take down that giant robot,[n]but we'll be in trouble if it attacks us[n]when we're weakened![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_030_0 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 3]It transformed!? What is it planning[n]on doing!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_040_0 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]Don't tell me it's going to rush us!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_050_0 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 3]It transformed!? Don't tell me it's going[n]to roll into us![n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_000_00 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Hm!? Is that bastard going to rush us[n]again!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_010_00 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1036 0 3]What do we do? Should we try[n]distracting Kaneshiro!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_030_00 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]As you can see, Kaneshiro is obviously[n]a money monger![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1039 0 3]We might be able to draw his attention[n]by throwing an expensive item[n]his way![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Let's give it a try, Joker! It's[n]your call what item we throw![n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER_032_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Don't be ridiculous! There's another[n]way![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 3]As you know, Kaneshiro is a money[n]monger.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]Tossing an expensive item his[n]way might draw his attention[n]and serve as a distraction![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Let's give it a try, Joker! It's[n]your call what item we throw![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_010_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Hm!? Is that bastard going to rush us[n]again!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_200_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1037 0 3]What's the plan? Should we knock him[n]off like earlier, or do you want to find[n]another way out?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_300_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Don't be ridiculous! There's another[n]way![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_400_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]As you know, Kaneshiro is a money[n]monger.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1039 0 3][f 4 10 65535 0 0]Tossing an expensive item his[n]way might draw his attention[n]and serve as a distraction![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Let's give it a try, Joker! It's[n]your call what item we throw![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_000_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Hm!? Is that bastard going to rush us[n]again!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_100_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 3]What do we do? Should we try[n]distracting Kaneshiro!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1035 0 3][f 4 10 65535 0 0]Shouldn't we be able to stop the rush[n]then? Perhaps we can drop him on it![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_500_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1200 0 3]He's going to rush us again... Hey Joker,[n]I have a good idea.[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_700_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1201 0 3]Attacking him is fine... but why not[n]find another way to distract him?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_800_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Don't be ridiculous! There's another[n]way![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_900_002 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]As you know, Kaneshiro is a money[n]monger.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1043 0 3]Tossing an expensive item his[n]way might draw his attention[n]and serve as a distraction![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Let's give it a try, Joker! It's[n]your call what item we throw![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_300_000 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1194 0 3]He's in pain. This is our chance to keep[n]the pressure on![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_030_002 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1064 0 3]D-Did it work...!?[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1065 0 3]We don't need to worry about getting[n]rushed now! Nice work, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGWAIT_010_002 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1070 0 3]Kaneshiro's completely engrossed...[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1071 0 3]Attack him while he's off guard![n]It's only right that a money monger[n]like him is destroyed by money![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGCLOSED_010_00 [Mona]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1073 0 3]Ngh, he's not interested at all...[n][f 1 3 65535][w][e]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1074 0 3]Do we need to use something worth[n]a little more?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER25_020_0 [Queen]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1077 0 6]It's already been decided...[n]You are going down.[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYUNDER50_020_0_2 [Queen]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 6]That's our line! You had better be[n]prepared![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_002_002EX [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 3]Keep at it, Joker! Corner him![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_000_002EX [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1010 0 3]Show no mercy! Let's finish him![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_030_000EX [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1013 0 3]You're all buzz and no bite![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_090_002EX [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 3]A pig!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_110_002EX [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 3]Dammit! I didn't expect he'd have[n]something like this up his sleeve![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_120_005EX [Queen]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 6]Joker! Make sure you have us regroup[n]if you think we're at a disadvantage![n][f 1 3 65535][w][e]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1023 0 6]That thing's a giant... If it attacks us[n]while we're at low stamina, we won't[n]survive![n][f 1 3 65535][w][e]

[msg MSG_BTL_FLYEND_130_002EX [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1024 0 6]Joker! Have us regroup if you think[n]we're at a disadvantage![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1025 0 6]We need to take down that giant robot,[n]but we'll be in trouble if it attacks us[n]when we're weakened![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_030_0_2 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 3]It transformed!? What is it planning[n]on doing!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_040_0_2 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]Don't tell me it's going to rush us!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER50_050_0_2 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 3]It transformed!? Don't tell me it's going[n]to roll into us![n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_000_00_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Hm!? Is that bastard going to rush us[n]again!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_010_00_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1036 0 3]What do we do? Should we try[n]distracting Kaneshiro!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER02_030_00_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]As you can see, Kaneshiro is obviously[n]a money monger![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1039 0 3]We might be able to draw his attention[n]by throwing an expensive item[n]his way![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Let's give it a try, Joker! It's[n]your call what item we throw![n][f 1 3 65535][w][e]

[msg MSG_PARTY_ORDER_032_002E [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Don't be ridiculous! There's another[n]way![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 3]As you can see, Kaneshiro is obviously[n]a money monger![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]Tossing an expensive item his[n]way might draw his attention[n]and serve as a distraction![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Let's give it a try, Joker! It's[n]your call what item we throw![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_010_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Hm!? Is that bastard going to rush us[n]again!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_200_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1037 0 3]What's the plan? Should we knock him[n]off like earlier, or do you want to find[n]another way out?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_300_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Don't be ridiculous! There's another[n]way![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_400_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]As you know, Kaneshiro is a money[n]monger.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1039 0 3][f 4 10 65535 0 0]Tossing an expensive item his[n]way might draw his attention[n]and serve as a distraction![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Let's give it a try, Joker! It's[n]your call what item we throw![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_000_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Hm!? Is that bastard going to rush us[n]again!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_100_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 3]What do we do? Should we try[n]distracting Kaneshiro!?[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1035 0 3][f 4 10 65535 0 0]Shouldn't we be able to stop the rush[n]then? Perhaps we can drop him on it![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_500_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1200 0 3]He's going to rush us again... Hey Joker,[n]I have a good idea.[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_700_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1201 0 3]Attacking him is fine... but why not[n]find another way to distract him?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_800_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]Don't be ridiculous! There's another[n]way![n][f 1 3 65535][w][e]

[msg MSG_PARTY_TSUIKA_900_002_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]As you know, Kaneshiro is a money[n]monger.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1043 0 3]Tossing an expensive item his[n]way might draw his attention[n]and serve as a distraction![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Let's give it a try, Joker! It's[n]your call what item we throw![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGSHOOT_300_000_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1194 0 3]He's in pain. This is our chance to keep[n]the pressure on![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGOPEN_030_002E [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1064 0 3]D-Did it work...!?[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1065 0 3]We don't need to worry about getting[n]rushed now! Nice work, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGWAIT_010_002E [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1070 0 3]Kaneshiro's completely engrossed...[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1071 0 3]Attack him while he's off guard![n]It's only right that a money monger[n]like him is destroyed by money![n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGCLOSED_010_00_2 [Mona]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1073 0 3]Ngh, he's not interested at all...[n][f 1 3 65535][w][e]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 0 2 1074 0 3]Do we need to use something worth[n]a little more?[n][f 1 3 65535][w][e]

[msg MSG_BTL_PIGUNDER25_020_0_2 [Queen]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1077 0 6]It's already been decided...[n]You are going down.[n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_START3 [Queen]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 6]It's about time for you to face the[n]bottom line![n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_BLOCK [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1090 0 3]What!? They blocked that?[n][f 1 3 65535][w][e]

[msg MSG_BTL_3RD_BLOCK2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Hmmm, that shield move is a real[n]hassle... Should we put them to[n]sleep so they can't get in our way?[n][f 1 3 65535][w][e]

[msg MSG_BTL_AFTER_SPECIAL [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1102 0 3]His minions are nowhere to be seen...[n]I guess relationships built on money don't[n]mean anything once the wealth dries up![n][f 1 3 65535][w][e]

[msg MSG_BTL_FRIENDSUMMON_04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1088 0 3]Ugh, how is this dealing with us[n]yourself?[n][f 1 3 65535][w][e]

[msg MSG_BTL_FRIENDSUMMON_05 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1089 0 3]Hey, guys! Their numbers may be[n]growing, but we can't let that get[n]to us! Let's do this![n][f 1 3 65535][w][e]

[msg MSG_BTL_FIRSTBLOCK_01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1092 0 3]Hmmm... That shield move is a real[n]hassle...[n][f 1 3 65535][w][e]

[msg MSG_BTL_FIRSTBLOCK_02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1093 0 3]We can try to take down those minions,[n]but Kaneshiro's not lying when he says[n]they're tough.[n][f 1 3 65535][w][e]

[msg MSG_BTL_FIRSTBLOCK_03 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1094 0 3]...In that case, why don't we just put them[n]to sleep? If they're not awake, they can't[n]get in our way![n][f 1 3 65535][w][e]

[msg MSG_BTL_FIRSTBLOCK_04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1095 0 3]We'll leave the tactics to you, Joker—[n]but I don't think it's a bad plan, myself![n][f 1 3 65535][w][e]

[msg MSG_BTL_ULTIMATUM [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1104 0 3]You're out of options here. Why won't[n]you accept your fate already?[n][f 1 3 65535][w][e]
