[msg MSG_BATTLESTART02_010_00 [Oracle]]
[s]What is this power!?[n][f 1 3 65535][w][e]
[s]Careful! Those muscles aren't just for[n]show![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_020_00 [Oracle]]
[s]Now's our chance! Let's take his Treasure![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_070_00 [Mona]]
[s]He's still gonna come at us!?[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_090_00 [Mona]]
[s]All right![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_091_00 [Mona]]
[s]You hear that, Shido!?[n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_092_00 [Mona]]
[s]All right, our next move is gonna[n]end this once and for all![n][f 1 3 65535][w][e]

[msg MSG_BATTLESTART03_110_00 [Oracle]]
[s]No way! He's even stronger now!?[n][f 1 3 65535][w][e]

[msg MSG_03HP50_020_000 [Mona]]
[s]You're a disgrace![n][f 1 3 65535][w][e]

