[msg MSG_CINDERELLA_B02_ENTRY [Oracle]]
[s][bup 0 8 602 65535 0][vp 8 0 2 1001 0 8][f 4 10 65535 0 0]Okay guys, leave the navigation to me![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1002 0 8][f 4 10 65535 0 0]Let's push 'em back![n][f 1 3 65535][w][e]

[msg MSG_CINDERELLA_B02_UNDER_2 [Oracle]]
[s][bup 0 8 602 65535 0][vp 8 0 2 1005 0 8][f 4 10 65535 0 0]It looks like it's working—just hang in[n]there a little longer![n][f 1 3 65535][w][e]
