[msg MSG_BTLSTART_000 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 2 1001 0 10]Dr. Maruki...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 8]Incoming, guys! Get ready![n][f 1 3 65535][w][e]

[msg MSG_BTL_HP75_2 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 8]Huh? He's getting stronger!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 2 1015 0 8]Be careful![n][f 1 3 65535][w][e]

[msg MSG_BTL_AFTER_CHANGE [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1016 0 8]Nnh... What was that just now?[n][f 1 3 65535][w][e]

[msg MSG_BTL_BLOCK01 [Queen]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1007 0 6]The Persona protected him!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_BLOCK01B [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 4]No way! The Persona blocked for him!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_BLOCK01C [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1009 0 8]What? The Persona shielded him!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_BLOCK02 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1010 0 8]This Persona's definitely trouble...[n][f 1 3 65535][w][e]

[msg MSG_BTL_CHARGE_1 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1072 0 3]What the—!? What are they doing!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_CHARGE_1B [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1073 0 8]Be careful! I'm sensing a ridiculous[n]amount of energy from his Persona![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 2 1074 0 8]Joker! You all have to guard this![n][f 1 3 65535][w][e]

[msg MSG_BTL_CHARGE_1C [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1077 0 8]Here they come again, Joker! Get your[n]guard up![n][f 1 3 65535][w][e]

[msg MSG_BTL_AZATOTH_DEAD [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1081 0 8]Finally! His Persona can't act anymore![n][f 1 3 65535][w][e]

[msg MSG_BTL_AZATOTH_DEAD2 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1082 0 8]Now's your shot, Joker![n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION02 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1062 0 2]Yeah? Well, too bad for you—I'm done[n]runnin' away from my problems![n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION03 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1064 0 3]I don't care what I look like anymore![n]I'm always going to be myself![n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION04 [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1063 0 4]We're... We're both going to keep[n]living our lives on our own strength![n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION05 [Fox]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1065 0 5]I have my friends by my side in this[n]world—I don't need another world[n]forced upon me![n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION06 [Queen]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1066 0 6]I'll fulfill my desire for a happy family—[n]with my own power![n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION07 [Noir]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1067 0 7]I'm going to do just that with my life—[n]pain and all![n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION08 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0]Unused[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION09 [Crow]]
[s][bup 0 9 802 65535 0][f 4 10 65535 0 0][vp 8 0 2 1068 0 9]Enough of this high-and-mighty[n]bullshit! You're pissing me off![n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION10 [Violet]]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][vp 8 0 2 1069 0 10]I am myself! I'll never forget that again![n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION01_B [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1017 0 8]They can't do anything!?[n]Something's not right here...[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION02_B [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 2]I can't, though... Why?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION03_B [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1020 0 3]Hey, something's wrong.[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION04_B [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 4]Huh? But, I... I can't...[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION05_B [Fox]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 5]I can't... But, why?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION06_B [Queen]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 6]I have to move... I have to... But...[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION07_B [Noir]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1023 0 7]I can't do it... What is...?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION0F_B [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1017 0 8]They can't do anything!?[n]Something's not right here...[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION08_B [Crow]]
[s][bup 0 9 802 65535 0][f 4 10 65535 0 0][vp 8 0 2 1025 0 9]What did you do to me!?[n][f 1 3 65535][w][e]

[msg MSG_PARTY_REACTION09_B [Violet]]
[s][bup 0 10 105 0 0][f 4 10 65535 0 0][vp 8 0 2 1024 0 10]Huh? Something's not right...[n][f 1 3 65535][w][e]

[msg MSG_HP_MIDDLE_REACTION [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0]奥の手でもあるのか?(仮)[n]不穏な動きがあったら気をつけろ![n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_TARGET02 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 8]Skull, be careful! I'm picking up[n]multiple readings beneath you![n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_TARGET03 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 8]Mona, be careful! I'm picking up[n]multiple readings beneath you![n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_TARGET04 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 8]Panther, be careful! I'm picking up[n]multiple readings beneath you![n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_TARGET05 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 8]Fox, be careful! I'm picking up[n]multiple readings beneath you![n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_TARGET06 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 8]Queen, be careful! I'm picking up[n]multiple readings beneath you![n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_TARGET07 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 8]Noir, be careful! I'm picking up[n]multiple readings beneath you![n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_TARGET08 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0]未使用[n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_TARGET09 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1036 0 8]Crow, be careful! I'm picking up[n]multiple readings beneath you![n][f 1 3 65535][w][e]

[msg MSG_BTL_MARUKI_TARGET10 [Oracle]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1035 0 8]Violet, be careful! I'm picking up[n]multiple readings beneath you![n][f 1 3 65535][w][e]

