[msg FLD162_010_notkey_mes_01 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What are you doing? There's no point[n]inspecting that right now.[n][w][e]

[msg FLD162_010_notkey_3rd_me [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]Figures it won't open normally.[n]Try checking that authentication[n]device on the side there.[n][w][e]

[msg FLD162_03_notkey_check_g [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9160 65535 0]Let's check out the security door first.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We might learn something.[n][w][e]
