[msg FLD162_012_notkey_mes_01 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh? It won't open...[n][w][e]

[msg FLD162_012_notkey_mes_02 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's locked from the inside. We should[n]use a different entrance.[n][w][e]

[msg FLD162_012_notkey_mes_03 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What are you doing!? That'll break your[n]shoulder![n][w][e]

