[msg LOCK_CLEAR02 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right! Let's get movin'![n][w][e]

[msg NOT_OPEN_DOOR [Skull]]
[s]The door is tightly sealed.[n][w][e]

[msg LOCK_DOOR [Skull]]
[s]The door is locked.[n][w][e]

[msg D01_04_e160_051_mes01 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hold on, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1148 65535 0]Can we look around a little more before[n]he head back? There might be a hidden[n]path we can take.[n][w][e]

