[msg D157_006_miniEV_01_mes03 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]It seems we have no choice but to do as[n]he says. Let us go.[n][w][e]

[msg D06_MIDDLE_BOSS_LOCK_mes [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8156 65535 0]We finally obtained the High Stakes Card.[n]Why don't we go check the elevator?[n][w][e]

