[msg D10_07_locked_door_mes_s [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]The hell? It's locked.[n][w][e]

[msg D10_07_locked_door_mes02 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There doesn't seem to be a way[n]around this one.[n][w][e]

[msg D10_07_locked_door_mes04 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]See those scaffolds? They help auditorium[n]workers get around more easily—perhaps[n]they can do the same for us?[n][w][e]

[msg D10_07_locked_door_mes_e [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...That's not a bad idea.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]Joker, see if your grappling hook[n]can help us out here.[n][w][e]