[msg EX_000e_CHECK_mes01 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]Th-The hell... It ain't openin'![n][w][e]

[msg EX_000e_CHECK_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wait... I can hear a faint breeze blowing[n]in from somewhere... Is there another[n]way through?[n][w][e]

[msg LOCK_CLEAR02 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7147 65535 0]All right! Let's get movin'![n][w][e]

[msg D01_ex_e490_001_mes01 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Somethin's up with this door...[n][w][e]

[msg D01_ex_e490_001_mes02 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Doesn't it seem different from everything[n]else we've seen so far?[n][w][e]

[msg D01_ex_e490_001_mes03 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I've never seen anything like it either...[n]Let's take a closer look, Joker.[n][w][e]

