[msg D156_03_miniEV03_mes01 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Don't this look like an elevator?[n]It ain't doin' anything, though.[n][w][e]

[msg D156_03_miniEV03_mes02 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But it doesn't seem to be completely out of[n]order either. Perhaps it's at another floor.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's try coming back later.[n][w][e]

[msg D156_03_miniEV03_mes03 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The elevator seems to be stopped at[n]another floor. Let's try coming back[n]later, okay?[n][w][e]

