[msg e382_205_mes01 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Sheesh, it ain't openin'. Guess we gotta[n]sign up to get in.[n][w][e]

[msg e382_205_mes02 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh well. Let's head over to the counter[n]and pay our registration fee.[n][w][e]

[msg e382_206_mes01 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]God damn! It's so freakin' dark![n][w][e]

[msg e382_206_mes02 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is definitely not "a little"—we've[n]been tricked.[n][w][e]

[msg e382_206_mes03 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm sensing Shadows too. "Very simple,"[n]my ass.[n][w][e]

[msg e382_206_mes04 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If we do not ascertain the layout and[n]placement of the enemies, we will[n]surely find ourselves in danger.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I just hope there is an adequate way[n]of doing so...[n][w][e]

[msg e382_220_mes01 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Oooh, we made it through![n][w][e]

[msg e382_220_mes02 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Is that it though? It feels like there's[n]more up ahead.[n][w][e]

[msg e382_210_mes01 [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6200 65535 0]No way... It's not opening!?[n][w][e]

[msg e382_210_mes02 [Fox]]
[s][bup 0 5 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Impossible. We took the only path[n]available straight to this point.[n][w][e]

[msg e382_210_mes03 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, the participants are trapped in here[n]to fall victim to the Shadows?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...It seems they have no intention[n]of letting us proceed further.[n][w][e]

[msg e382_210_mes04 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Dammit, this is cheatin'... Actually, it's[n]even worse than cheatin'![n][w][e]

[msg e382_210_mes05 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Regardless, let's search for a way past[n]here. We can't get the coins if we don't[n]reach the goal.[n][w][e]

[msg e382_210_mes06 [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6200 65535 0]Huh, it's not opening!?[n][w][e]

[msg e382_210_mes07 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Odd. That [clr 2]duct[clr 27] excluded, the path here[n]from the entrance was quite direct.[n][w][e]

[msg e382_210_mes08 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, the participants are trapped in here[n]to fall victim to the Shadows?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...It seems they have no intention of[n]letting us proceed further.[n][w][e]

[msg e382_210_mes09 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]They're cheatin', dammit![n][w][e]

[msg e382_210_mes10 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fine. Things are different now.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We will make it to the goal, even if we[n]have to use that [clr 2]secret passage[clr 27].[n][w][e]

