[msg FLD162_009_LookEnemy_sta [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So this room's for the wrong answer...[n]What woulda happened to us if we[n]chose it?[n][w][e]

[msg FLD162_009_LookEnemy_02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...I guess we may as well check.[n][w][e]

[msg FLD162_009_LookEnemy_05 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A Shadow... It's rather easy to imagine[n]now what would've happened had we[n]chosen A instead.[n][w][e]

[msg FLD162_009_LookEnemy_end [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Looks like we were right—choosing the[n]answer that Maruki would believe is[n]correct is the safest way for us to advance.[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's just sneak away... It'd be a pain[n]if we had to deal with that.[n][w][e]

[msg FLD162_009_accept_lock [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We don't know what's happening[n]in there. We should investigate the[n]reception area thoroughly first.[n][w][e]

