[msg D10_02_DOOR_mes01 [Mona]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No good... We'll have to find another way.[n][w][e]

[msg D10_02_DOOR_mes02 [Mona]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's find another route.[n][w][e]

[msg D10_02_ST_door_mes01 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Didn't we discuss needing to go to the[n]Auditorium? I can't say I agree with any[n]detours at the moment.[n][w][e]

[msg D10_02_ST_door_mes02 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]We don't know what the enemy is[n]planning—let's not make any detours[n]for now and just focus on our objective.[n][w][e]
