[msg FLD162_015_notkey_mes_St [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The hell, man? It's locked.[n][w][e]

[msg FLD162_015_notkey_mes_En [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nothing we can do about that. Let's find[n]another door.[n][w][e]

[msg FLD162_015_notkey_Retry_ [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What are you doing? Let's hurry up and[n]find another door.[n][w][e]
