[msg D157_005_DOOR_01_mes01 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Damn, it ain't openin'.[n][w][e]

[msg D157_005_DOOR_01_mes02 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Doesn't it seem like it might need a[n]keycard?[n][w][e]

[msg D157_005_DOOR_01_mes03 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6019 65535 0]Maybe we can use that security key[n]we found earlier?[n][w][e]

[msg D157_005_DOOR_02_mes01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Hm, it's not opening.[n][w][e]

[msg D157_005_DOOR_02_mes02 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's an authentication device.[n]Perhaps we need some kind of keycard.[n][w][e]

[msg D157_005_DOOR_02_mes03 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It will likely not be easily attained,[n]given its relation to the security of[n]this place.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It would be most logical to expect[n]someone relatively powerful would[n]have it in their possession.[n][w][e]

[msg D157_005_DOOR_02_mes04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]We can't get through here.[n][w][e]

[msg D157_005_DOOR_02_mes05 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's an authentication device next[n]to it though. Let's try using the keycard[n]from earlier.[n][w][e]

[msg D157_005_DOOR_02_mes06 [Panther]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6045 65535 0]All right! It's open![n][w][e]

[msg D157_005_DOOR_02_mes07 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Great. Now we'll be able to get through[n]here, Joker.[n][w][e]

[msg D157_005_DOOR_02_mes08 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It appears to be locked, but I see no[n]avenue by which to unlock it.[n][w][e]

[msg D157_005_DOOR_02_mes09 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Either there is no way to open this door,[n]or the device to do so lies on the other[n]side.[n][w][e]

[msg D157_005_DOOR_03_mes01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1173 65535 0]It won't open... Do you think it's locked[n]from the other side?[n][w][e]

[msg D157_005_DOOR_03_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1176 65535 0]It's not opening. Looks like we need to[n]find a keycard.[n][w][e]

[msg D157_005_DOOR_04_mes01 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7043 65535 0]It ain't openin'![n][w][e]

[msg D157_005_DOOR_04_mes02 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4175 65535 0]It seems things won't be so simple for[n]us. We will have to search for another[n]way around after all...[n][w][e]

[msg D157_005_DOOR_04_mes03 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1018 65535 0]Hey, where are you going? That's not[n]the right direction for now.[n][w][e]

[msg D157_005_miniEV_05_mes03 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Damn... So this is how they're keepin'[n]tabs on everyone...[n][w][e]

[msg D157_005_miniEV_05_mes04 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It seems they're instructing how to[n]manipulate their customers as well.[n]How thorough of them.[n][w][e]

[msg D157_005_miniEV_05_mes05 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1133 65535 0]Looks like this is where they keep[n]surveillance on the casino. Let's go[n]elsewhere before they see us.[n][w][e]

[msg D157_005_miniEV_05_mes06 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2103 65535 0]It would be a problem if these guards[n]saw us. We should avoid opening that[n]door.[n][w][e]

