[msg GOTO_D04_EXIT_mes01 [Mona]]
[s]Do you want to head back to the pyramid?[n][w][e]

[msg D04_02_e296_501_mes01 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y'know, just what the hell's happenin'[n]in her heart?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's this bandit, those weird voices[n]sayin' "you killed her," and who knows[n]what else...[n][w][e]

[msg D04_02_e296_501_mes02 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Futaba's supposed to be the queen of this[n]Palace, but even she can't control it?[n][w][e]

[msg D04_02_e296_501_mes03 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If I had to guess, I'd say her suppressed[n]memories are causing her to lose[n]command over it.[n][w][e]

[msg D04_02_e296_501_mes04 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Regardless, we should go back and open[n]the gate of fire.[n][w][e]

[msg MSG_e296_521_000 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7043 65535 0]Hey, I said wait! We're—[n][w][e]

[msg MSG_e296_521_002 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He ran off again! Hurry up and catch him,[n]fast![n][w][e]

[msg MSG_e296_522_001 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6115 65535 0]Urghhh, he got away again! This is really[n]pissing me off![n][w][e]

[msg MSG_e296_522_002 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We'll never catch him if we do nothing[n]but follow his path... We should corner[n]him somewhere.[n][w][e]

[msg MSG_e296_522_003 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Corner him? But how?[n][w][e]

[msg MSG_e296_522_004 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2127 65535 0]Let's use that square from earlier. We [n]sneak around him and trap him in there![n][w][e]

[msg MSG_e296_523_001 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Grhhh! That freakin' bastard really[n]pisses me off![n][w][e]

[msg MSG_e296_523_002 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Just carefully observe where he's headed![n]We should be able to corner him with a[n]bit of skill![n][w][e]

[msg MSG_e296_523_004 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is humiliating, but we must endure.[n]Our only option is to corner him, correct?[n][w][e]

[msg MSG_e296_523_005 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]Yes. We should sneak around from the[n]other side and corner him in the square[n]where we first met.[n][w][e]

[msg MSG_e296_523_006 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6117 65535 0]There he goes...! We finally chased him[n]into the square![n][w][e]

[msg MSG_e296_523_007 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perfect. He has nowhere else to run now...[n]Let's do this, Joker![n][w][e]

