[msg D08_01_e440_010_mes01 [Oracle]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What is this...? Joker, try activating it.[n][w][e]

[msg D08_01_NPC_TALK_01_mes02 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]The hell...? Is this some kinda prison[n]cell too...?[n][w][e]

[msg D08_01_NPC_TALK_01_mes03 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Plus there are those blood vessel things[n]coming down into it...[n][w][e]

[msg D08_01_NPC_TALK_02_mes02 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3184 65535 0]This is just like how I used to be...[n][w][e]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If I had stayed like that, I would sound[n]just like her now...![n][w][e]

[msg D08_01_NPC_TALK_03_mes02 [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9027 65535 0]Uh, you talk about justice, but you know[n]there's something sucking stuff outta your[n]head, right...?[n][w][e]

[msg D08_01_NPC_TALK_04_mes02 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]It's all... going to end? What is he saying...?[n][w][e]

