[msg e382_210_mes01 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Oooh, I can feel some breeze comin'[n]through here. Whaddya say? Wanna[n]head inside?[n][w][e]

[msg e382_210_mes02 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I hope nobody finds us and disqualifies[n]us for breaking the rules...[n][w][e]

[msg e382_210_mes03 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Good idea. We may have to use it in the[n]end, but for now let us simply remember[n]it is here.[n][w][e]

[msg e382_210_mes04 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]Heh, we still ended up usin' it.[n][w][e]

[msg e382_210_mes05 [Crow]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Haha, perhaps we should have gone[n]through with it in the first place. Ah well,[n]such is life.[n][w][e]

[msg e382_210_mes06 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7159 65535 0]Yo, look! There's a breeze comin' through[n]here. You think it goes somewhere else!?[n][w][e]

[msg e382_210_mes07 [Queen]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, how convenient. If they're not going[n]to let us move forward, we can force our[n]way through here.[n][w][e]

[msg e382_210_mes08 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Haha, an unsurprising idea for Sae-san's[n]sister. I will go along with whatever plan[n]we choose.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The decision is yours, Joker.[n][w][e]