[msg D157_007_miniEV_02_mes11 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let us prioritize putting this trickery to an[n]end. We should sweep the area for clues.[n][w][e]

[msg D157_007_miniEV_03_mes01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1160 65535 0]This seems to lead somewhere...[n]Should we check it out, Joker?[n][w][e]

[msg D6_SAIKORO_TRICK01 [Crow]]
[s]Joker, could I have a word?[n][w][e]
[s]Based on what Sae-san said earlier,[n]I doubt these dealers are playing[n]an honest game here.[n][w][e]
[s]It is quite likely they are cheating.[n]Shall we check the area around[n]here instead?[n][w][e]

[msg D157_007_miniEV_05_mes02 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Is this a secret passage? I must admit,[n]I am curious. However, we should[n]prioritize the coins first.[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_2 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_3 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_5 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_6 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_7 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_9 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_10 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg D06_MIDDLE_DICE_LOCK_mes [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]We already got the device thing, right?[n]Let's go somewhere else.[n][w][e]

[msg e380_125_mes01 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh? Hey, where are you going? We set[n]the cheating device up. Wouldn't it be[n]bad to leave now?[n][w][e]

[msg e380_125_mes02 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It would be troublesome if some other[n]guest won big. Let us take advantage of[n]the device before we leave, Joker.[n][w][e]

