[msg D157_004_miniEV_01_mes01 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It seems this door cannot be opened...[n][w][e]

[msg D157_004_miniEV_01_mes02 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We'll have to find another way...[n][w][e]

[msg D157_004_miniEV_02_mes01 [Crow]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I do not intend on dragging your team[n]down. I will gladly prove that intent to[n]you here.[n][w][e]

[msg D157_004_miniEV_02_selA_ [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Then I shall exceed your expectations![n][w][e]

[msg D157_004_miniEV_02_selA__2 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, let us commence when you feel[n]ready.[n][w][e]

[msg D157_004_miniEV_04_mes01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]It doesn't look like this[n]door is going to open...[n][w][e]

[msg D157_004_LOCK_KENJI_mes0 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]We should focus on chasing after Sae-san[n]for now![n][w][e]

[msg D157_004_LOCK_KENJI_mes0_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1164 65535 0]There's no point in floundering. Let's get[n]down there and hear what she has to say.[n][w][e]

