[msg test_COUNTER_selA_1_mes0 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg e380_250_mes01 [Noir]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We finally have the card! Let's do our best[n]on the next floor as well.[n][w][e]

[msg e380_250_mes02 [Crow]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I hope I was able to contribute in some[n]meaningful way. Come, let us head over[n]to the elevator.[n][w][e]

[msg e380_260_mes01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1133 65535 0]They're greeting us in front of the elevator?[n]This doesn't give off a welcoming vibe[n]though...[n][w][e]

[msg e380_260_mes02 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This must be due to the instigation of[n]Sae-san. We should be prepared to fight.[n][w][e]

[msg e383_005_mes02 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We merely followed your rules.[n][w][e]

[msg e383_005_mes04 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It appears both the Sae-san of the real[n]world and that of this world are at their[n]wit's end...[n][w][e]

[msg e383_005_mes06 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You're the only one who's gonna be[n]leaving, black suit![n][w][e]

[msg e383_005_mes07 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Things would've been so much simpler[n]if we could do this from the start![n][w][e]

[msg D157_006_miniEV_01_mes03 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]It seems we have no choice but to do as[n]he says. Let us go.[n][w][e]

