[msg D10_11_Light_Tutorial01_ [Fox]]
[s][bup 0 5 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Where... are we?[n][w][e]

[msg D10_11_Light_Tutorial01__2 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]What a change in scenery. We were[n]just in a science lab, and now...[n][w][e]

[msg D10_11_Light_Tutorial01__3 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quite. It's almost as if we're in—[n][w][e]

[msg D10_11_Light_Tutorial01__4 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Whoa! Look over there![n][w][e]

[msg D10_11_Light_Tutorial01__5 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhhh, those people are floating away...[n][w][e]
[s][bup 0 10 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57065 65535 0]What on earth is going on!?[n][w][e]

[msg D10_11_Light_Tutorial01__6 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Whatever it is, it most likely has to do[n]with Maruki's cognition in some way.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'd say he believes anyone who[n]undergoes his "treatment" winds up[n]feeling downright rapturous.[n][w][e]

[msg D10_11_Light_Tutorial01__7 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So he actually thinks he's sending them[n]to paradise?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmph. Maruki must really be convinced[n]he's doing the right thing.[n][w][e]

[msg D10_11_Light_Tutorial01__8 [Violet]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]Dr. Maruki...[n][w][e]

[msg D10_11_Light_Tutorial01__9 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mona-senpai, the Treasure's above[n]this room, right?[n][w][e]

[msg D10_11_Light_Tutorial01__10 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, I think we're pretty close.[n][w][e]

[msg D10_11_Light_Tutorial01__11 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The real problem is actually getting[n]up there.[n][w][e]

[msg D10_11_Light_Tutorial01__12 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]There's some stairs, but there's a[n]big ol' hole in the middle of 'em...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They got thick-lookin' vines growin'[n]outta both sides, too... Think we can[n]use those somehow?[n][w][e]

[msg D10_11_Light_Tutorial01__13 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We don't know if they'll support[n]our weight—I'd rather not take[n]any unnecessary risks.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The steps do extend partway upwards,[n]so there should be some method to[n]turn them into safe passageways.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]At least, that's what prior Palace[n]experience makes me think.[n][w][e]

[msg D10_11_Light_Tutorial01__14 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I must agree—and it looks like there[n]may a device for doing just that right[n]over there. Think it could help?[n][w][e]

[msg D10_11_Light_Tutorial01__15 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3192 65535 0]Well, what say we don't waste any time[n]then?[n][w][e]

[msg D10_11_Light_Tutorial02_ [Violet]]
[s][bup 0 10 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57064 65535 0]We fixed the stairs![n][w][e]

[msg D10_11_Light_Tutorial02__2 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It appears the vines grow whenever the[n]color of light matches the color of flowers.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The switch also seems to affect any[n]lights in the immediate area.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I wonder if there are any more of them[n]in here...[n][w][e]

[msg D10_11_Light_Tutorial02__3 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7048 65535 0]Point is, we can use these light switch[n]thingies to make the vines grow, right?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's get to work, Joker![n][w][e]

[msg D10_11_Light_Tutorial03_ [Mona]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]First the stairs, now a wall of vines...[n][w][e]

[msg D10_11_Light_Tutorial03__2 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We grew stairs out of vines by[n]manipulating light switches...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54404 65535 0]Shouldn't we be able to do the same[n]with this wall?[n][w][e]

[msg D10_11_Light_Tutorial04_ [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What is this?[n][w][e]

[msg D10_11_Light_Tutorial04__2 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]It's a light control switchboard.[n]It's for adjusting the brightness[n]of the colored lights.[n][w][e]

[msg D10_11_Light_Tutorial04__3 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]See the light on that gate in front of[n]the stairs?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Right now, the color on the dimmer[n]switch panel matches that of the light.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Now that I take a closer look, the vines[n]appear to form stairs where the light[n]is shining.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I believe we'll be able to change the[n]available paths if we alter the lighting.[n][w][e]

[msg D10_11_Light_Tutorial04__4 [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]All right, Joker—try out the dimmer[n]switch and change the color scheme[n]of the lights![n][w][e]

[msg D10_11_Light_Wall_Vanish [Mona]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]The wall's gone. Now we can keep[n]advancing![n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Man... Turn lights on to make sets of[n]stairs, turn lights off to get rid of walls...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I wish we could just crank all the dials[n]and be done with this.[n][w][e]

[msg D10_11_Light_Wall_Vanish_2 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Not only that, we only had access to[n]the red lights here.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Should we find any additional switches,[n]I doubt we'll have access to all the colors[n]there, either.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's something we'll have to keep[n]in mind going forward.[n][w][e]

[msg D10_11_Light_Camera_Expl [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1019 65535 0]Hey, Joker—got a second?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We need to be careful when we change[n]the lights or we're going to have an even[n]harder time making progress.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Take a look at your surroundings[n]before deciding which lights to[n]switch on or off.[n][w][e]

[msg D10_11_Mixed_Light_First [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Alright, let's keep up the pace![n][w][e]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Hm?[n][w][e]

[msg D10_11_Mixed_Light_First_2 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We gotta match the color of the lights[n]with the flowers, right?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sooo... anyone remember seein'[n]a purple switch yet?[n][w][e]

[msg D10_11_Mixed_Light_First_3 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2131 65535 0]I would say this is more like magenta.[n]This is just a guess, but I think we can[n]just create that color with the panel.[n][w][e]

[msg D10_11_Mixed_Light_First_4 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If we turn on multiple colors at once,[n]the light should blend to create a new[n]color.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The red and green lights are on right now,[n]but if we adjust the dials properly, we should[n]end up with the requisite magenta.[n][w][e]

[msg D10_11_Mixed_Light_First_5 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4133 65535 0]Ah, so secondary colors are involved.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Blending colors together to reveal[n]our path... What a captivating puzzle.[n][w][e]

[msg D10_11_Mixed_Light_First_6 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The switches even have notes attached[n]to help us with the color blending.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Care to give it a try, Joker?[n][w][e]

[msg D10_11_light_stairs_end0 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]Yesss! The finish line![n][w][e]

[msg D10_11_light_stairs_end0_2 [Violet]]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're so close to the Treasure...[n]I'm getting kind of nervous.[n][w][e]

[msg D10_11_4th_EX_before_sta [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's a TV over there—and it looks[n]like there's a tape in the player.[n][w][e]

[msg D10_11_4th_EX_before_01 [Crow]]
[s][bup 0 9 813 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8028 65535 0]This AGAIN? I really hope it's the last one.[n][w][e]

[msg D10_11_4th_EX_before_end [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The tapes seem to be growing more[n]and more recent, though.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What do we have in store this time...?[n][w][e]

[msg D10_11_4th_passcode_lock_2 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"The day the sky turned red"? It must be[n]referring to Mementos merging with the[n]real world.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We'll leave the answer to you, Joker.[n][w][e]

[msg D10_11_4th_passcode_lock_5 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3021 65535 0]Looks like that wasn't it. Let's try again.[n][w][e]

[msg D10_11_4th_passcode_lock_7 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's open.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Shall we press on? The Treasure is close.[n][w][e]

[msg D10_11_4th_passcode_lock_9 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7114 65535 0]Another one o' these!?[n][w][e]

[msg D10_11_4th_passcode_lock_10 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"The day the sky turned red"? Is it talking[n]about the sunset? This one's extra hard[n]to figure out without any clues...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57144 65535 0]We should come back to this after we[n]get our hands on more information,[n]Joker-senpai.[n][w][e]

[msg D10_11_4th_passcode_lock_11 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57144 65535 0]We should get some information first,[n]Joker-senpai.[n][w][e]

[msg D10_11_EX3BOSS_1st_01 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That Shadow looks really strong,[n]Joker-senpai...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57047 65535 0]Let's make sure we're well-prepared[n]before the fight—what do you say?[n][w][e]

[msg D10_11_EX3BOSS_2nd_01 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57047 65535 0]Are we going in?[n][w][e]

[msg D10_11_EX3BOSS_selA_2_01 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57123 65535 0]Okay, let's pull back for now.[n][w][e]

[msg D10_11_EX3BOSS_before_ba_2 [Violet]]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Not today! We're taking the treasure[n]you guard whether you like it or not![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's go, everyone![n][w][e]

[msg D10_11_To05_Confirmation [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This looks like the final line of defense.[n]We should make sure we're in our best[n]condition before the confrontation.[n][w][e]

[msg D10_11_To05_Confirmation_2 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Shall we go, Joker?[n][w][e]

[msg D10_11_To05_Confirmation_4 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I see. I'll leave the timing to you.[n][w][e]

[msg D10_11_To05_Confirmation_5 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yes, let's.[n][w][e]

[msg D10_11_Tell_the_Goal_sta [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6001 65535 0]Hey, look! A huge staircase![n][w][e]

[msg D10_11_Tell_the_Goal_01 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It appears to stretch all the way to[n]the top of the buildings.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's probably where the Treasure is...[n][w][e]

[msg D10_11_Tell_the_Goal_end [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're almost there. Let's keep moving,[n]Joker.[n][w][e]

[msg D10_11_Boss03_Confirmati [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There aren't any other readings past[n]this guy... The map doesn't show any[n]more areas beyond him, either.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...This is probably the final hurdle.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This looks like a tough fight, so make[n]sure everyone's in peak condition first![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Ready, Joker?[n][w][e]

[msg D10_11_Boss03_Confirmati_2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Ready, Joker?[n][w][e]

[msg D10_11_Boss03_Confirmati_4 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9023 65535 0]Got it! Make sure everyone's sitting[n]pretty before we head in![n][w][e]

[msg D10_11_Boss03_mes_start [Guard Shadow]]
[s]You!? I can't believe you've made it[n]so far...[n][w][e]

[msg D10_11_Boss03_mes_01 [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4088 65535 0]But of course. You oughtn't underestimate[n]the Phantom Thieves.[n][w][e]

[msg D10_11_Boss03_mes_02 [Violet]]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're not backing down now.[n]Let us through![n][w][e]

[msg D10_11_This_is_Ishi_Rout [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3019 65535 0]Wait, Joker...[n][w][e]

[msg D10_11_This_is_Ishi_Rout_2 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We all agreed the Treasure is at the top[n]of that large staircase, didn't we?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Shouldn't we go in that direction instead?[n][w][e]

[msg D10_11_This_is_Ishi_Rout_3 [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Buuut, I DO sense a Will Seed over[n]there... What sort of Phantom Thieves[n]would we be if we ignored it?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It may be a good idea to check out[n]the area if we get the chance.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's entirely up to you though, Joker.[n][w][e]

[msg note_find_reaction_start [Violet]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]What could this be...? A diary?[n][w][e]

[msg note_find_reaction_01 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Looks like it. Judging from what's written[n]inside, it's most likely Maruki's...[n][w][e]

[msg note_find_reaction_watch [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Even that video from earlier... He just[n]really loves talking about himself.[n][w][e]

[msg note_find_reaction_notwa [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]It seems like he has written about things[n]in the past, but it looks like they are only[n]fragments of them...[n][w][e]

[msg note_find_reaction_end [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Doesn't look like it has any meaning to[n]it either.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Not sure if it'll come in handy for the[n]investigation, but let's hold on to it and[n]see if we can find other ones.[n][w][e]

