[msg D05_02_e341_030_ng_mes01 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Where are you going? Let's try gathering[n]some information from those robots.[n][w][e]

[msg D156_13_alert_mes02 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Shit, we got caught![n][w][e]

[msg D156_13_alert_mes04 [Queen]]
[s][bup 0 6 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2047 65535 0]We got too close... Let's withdraw for now[n]and reorganize![n][w][e]

[msg D156_13_miniEV04_mes01 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Huh... So we're basically eavesdroppin'[n]on 'em...[n][w][e]

[msg D156_13_miniEV04_mes02 [Oracle]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's a divine skill of mine.[n][w][e]

[msg D156_13_miniEV04_mes03 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6025 65535 0]Impressive. I can see how you managed[n]to wiretap Leblanc for so long...[n][w][e]

[msg D156_13_miniEV04_mes04 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That? Oh, that was nothing! Someday[n]I'll show you what real wiretapping is.[n]Mwehehe...[n][w][e]

[msg D156_13_miniEV04_mes05 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...I-In any case, there's no denying that[n]this is a smart move.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We'll just have to obtain information from[n]the group about [clr 2]what their boss is like[clr 27].[n][w][e]

[msg D156_13_miniEV04_mes06 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4192 65535 0]There appear to be a few of them further in.[n]Let us go obtain their information as well![n][w][e]

[msg D156_13_intelli_point_le [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2157 65535 0]We've heard a good amount...[n]What do you think, Joker?[n][w][e]

[msg D156_13_intelli_point_le_3 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2021 65535 0]Okay, let's get what we need and head out.[n][w][e]

[msg D156_13_intelli_point_le_4 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2118 65535 0]Then let's get out of here before we get[n]caught.[n][w][e]

[msg D05_02_kakari_battle07 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dude, we don't even work here.[n][w][e]

[msg D05_02_kakari_battle08 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2128 65535 0]Skull, would you mind staying focused?[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Excuse me, we have a matter to discuss[n]with the chief director...[n][w][e]

[msg D05_02_kakari_battle10 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Well, it was worth a try.[n][w][e]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Get ready, everyone![n][w][e]

[msg D156_13_miniEV05_mes01 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Huh. I'm thinkin' we can tell whether[n]they're the target if we can [clr 2]squeeze some[n]info outta 'em[clr 27].[n][w][e]

[msg D156_13_miniEV05_mes01_2 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7079 65535 0]Well, we ended up fightin' anyways, but I[n]think this is prolly a good way of doin' this.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can prolly tell whether they're the[n]target if we can [clr 2]squeeze some info outta[n]'em[clr 27] before we fight.[n][w][e]

[msg D156_13_miniEV05_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's right! We might be able to avoid[n]unnecessary battles if we [clr 2]cross-reference[n]that information[clr 27]![n][w][e]

[msg D05_02_e341_031_clear_me [Noir]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3045 65535 0]Yes, it opened![n][w][e]

[msg D05_02_e341_031_clear_me_2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We might end up getting a chief director[n]ID eventually if we keep getting higher[n]and higher ranks![n][w][e]

[msg D05_02_e341_031_clear_me_3 [Queen]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2035 65535 0]Agreed. Let's go about this one step at[n]a time.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, and if you're feeling tired, be sure to[n]stop in at a safe room, Joker.[n][w][e]

[msg D05_02_e341_034_end_mes0 [Fox]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4045 65535 0]It is over... Hm?[n][w][e]

[msg D05_02_e341_034_end_mes0_2 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's an ID! This should get us through[n]the gates.[n][w][e]

[msg D05_02_e341_034_end_mes0_3 [Skull]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7025 65535 0]So that one was the... Section Chief?[n]Or somethin'? Ugh, why can't the big[n]boss just come to us...?[n][w][e]

[msg D05_02_e341_034_end_mes0_5 [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6186 65535 0]This is...[n][w][e]

[msg D05_02_e341_034_end_selA_2 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]

[msg D05_02_e341_034_end_selA_3 [Mona]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]Come on, get with the program![n][w][e]

[msg D05_02_e341_034_end_mes0_6 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]The employees must be getting switched[n]out just like before.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why don't we check the places accessible[n]via the section chief ID card?[n][w][e]

[msg D05_02_e341_033_mes01 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7025 65535 0]We're stuck here too? Is this another[n]one of them rank things?[n][w][e]

[msg D05_02_e341_033_mes02 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yup! We'll need a section chief or higher[n]ID card for this one.[n][w][e]

[msg D05_02_e341_033_mes03 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm truly sorry for all the trouble I'm[n]putting you through...[n][w][e]

[msg D05_02_e341_033_mes04 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6024 65535 0]Stop that. The only one who's going to[n]be apologizing here is your father,[n]right?[n][w][e]

[msg D05_02_e341_033_mes05 [Fox]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Panther is correct. Let us go search for[n]this next ID card.[n][w][e]

[msg D05_02_e341_033_mes06 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This one's for section chiefs and above.[n]We're gonna need to snag another[n]employee ID.[n][w][e]

[msg D05_02_e341_033_clear_me [Noir]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3045 65535 0]Great! This one's open as well![n][w][e]

[msg D05_02_e341_033_clear_me_2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We've gotta be close to the end, right?[n]Chief director is usually directly above[n]section chief![n][w][e]

[msg D05_02_e341_033_clear_me_3 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Don't forget to be conscious of your[n]condition, everyone.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If you're feeling tired, be sure to rest[n]at a safe room.[n][w][e]

[msg D05_02_e341_034_ng_selA__3 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Looks like we're gonna have to fight.[n]C'mon, let's kick his ass![n][w][e]

[msg D05_02_e341_034_ng_selA__5 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Crap, we're gonna have to fight him at[n]this rate! Let's do it![n][w][e]

[msg D05_02_e341_034_ng_selB__3 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Looks like we're gonna have to fight.[n]C'mon, let's kick his ass![n][w][e]

[msg D05_02_e341_034_ng_selB__5 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Crap, we're gonna have to fight him at[n]this rate! Let's do it![n][w][e]

[msg D05_02_e341_034_ng_mes03 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]It is time we make our decision, Joker.[n]What do you want to do?[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Should we fight him for his employee ID?[n][w][e]

[msg D05_02_e341_034_ng_selC_ [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Right, there's no need for any more[n]discussion. Take him down![n][w][e]

[msg D05_02_e341_034_ng_selC__2 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]So you don't want to fight right now?[n]Then let's retreat![n][w][e]

[msg D05_02_true_kachou_battl_2 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]Hold on a second. We're...[n][w][e]

[msg D05_02_true_kachou_battl_6 [Noir]]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3108 65535 0]It looks like fighting is our only option[n]now. Let's go![n][w][e]

[msg D05_02_true_kachou_battl_9 [Skull]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7025 65535 0]Tch, you sure are quick to judge.[n]What would you know about how[n][clr 2]useless[clr 27] anyone is?[n][w][e]

[msg D05_02_true_kachou_battl_12 [Fox]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4045 65535 0]Listen to you, calling everyone [clr 2]useless[clr 27] and[n][clr 2]worthless[clr 27]. Have you thought about those[n]on the receiving end of your verbal abuse?[n][w][e]

[msg D05_02_true_kachou_battl_14 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]It's time to decide, Joker.[n]What should we do?[n][w][e]

[msg D05_02_true_kachou_battl_16 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1175 65535 0]Right, there's no need for any more[n]discussion. Take him down![n][w][e]

[msg D05_02_true_kachou_battl_17 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1166 65535 0]So you don't want to fight right now?[n]Then let's retreat![n][w][e]

[msg D05_02_e341_034_ng_end_m [Mona]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]Phew, we're done with that.[n][w][e]

[msg D05_02_e341_034_ng_end_m_2 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It doesn't look like he had anything,[n]unfortunately. It seems he wasn't[n]important, after all.[n][w][e]

[msg D05_02_e341_034_ng_end_m_3 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh well... Let's check elsewhere.[n][w][e]

[msg D05_02_e341_036_ng2_mes0_2 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]It is time we make our decision, Joker.[n]What do you want to do?[n][w][e]

[msg D05_02_e341_036_ng2_selC_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Right, there's no need for any more[n]discussion. Take him down![n][w][e]

[msg D05_02_e341_036_ng2_selC_3 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1163 65535 0]So you don't want to fight right now?[n]Then let's retreat![n][w][e]

[msg D05_02_e341_036_ng_end_m [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]Serves you right, bastard! That takes care[n]of that![n][w][e]

[msg D05_02_e341_036_ng_end_m_2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This guy's got nothing on him though.[n]100% waste of time.[n][w][e]

[msg D05_02_e341_036_ng_end_m_3 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]I-It seems their physical size doesn't[n]necessarily correlate to their rank...[n][w][e]

[msg D05_02_e341_036_ng_end_m_4 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The chief director must be somewhere[n]else... Let's try looking in another room.[n][w][e]

[msg D05_02_e341_036_mes03 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]It is time we make our decision, Joker.[n]What do you want to do?[n][w][e]

[msg D05_02_e341_036_selC_0_m [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]All right then, Joker! Let's take him down![n][w][e]

[msg D05_02_e341_036_selC_1_m [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]So you don't want to fight right now?[n]Then let's retreat![n][w][e]

[msg D05_02_e341_036_end_mes0 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]Looks like that finished him off. Hm?[n]What's that on the ground...?[n][w][e]

[msg D05_02_e341_036_end_mes0_2 [Noir]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perfect! We've finally found the chief[n]director's ID card![n][w][e]

[msg D05_02_e341_036_end_mes0_3 [Panther]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This means we can go in that rank door[n]downstairs now![n][w][e]

[msg D05_02_e341_036_end_mes0_4 [Oracle]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9048 65535 0]Welp, let's go check it out! Time to make[n]like a banana and split![n][w][e]

[msg D05_02_e341_035_mes01 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2128 65535 0]Hm, another roadblock. Is this one rank[n]authentication as well?[n][w][e]

[msg D05_02_e341_035_mes02 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmhm. We can get through here if we[n]have a chief director ID card or higher.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Though given the layout of this floor, it[n]doesn't look like this leads to a new area[n]or anything.[n][w][e]

[msg D05_02_e341_035_mes03 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]So our main goal remains the door we[n]found downstairs.[n][w][e]

[msg D05_02_e341_035_mes04 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why don't we skip all this shit and just[n]nab the president's ID? I wanna get this[n]over with![n][w][e]

[msg D05_02_e341_035_mes05 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, another roadblock. Is this one rank[n]authentication as well?[n][w][e]

[msg D05_02_e341_035_mes06 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yep yep. We can get through here if we[n]have a chief director ID card or higher.[n][w][e]

[msg D05_02_e341_035_mes07 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can get through here if we have a[n]chief director ID card or higher.[n][w][e]

[msg D05_02_e341_035_clear_me [Noir]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3048 65535 0]Yes, it opened![n][w][e]

[msg D05_02_e341_035_clear_me_2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Now we can move freely about this floor![n][w][e]

[msg D05_02_e341_035_clear_me_3 [Queen]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perfect. We have the employee ID card[n]we were after, so let's head downstairs[n]when we're done here![n][w][e]

[msg D05_02_e341_036_ng4_selA_4 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Hm, I was just feeling in the mood for a[n]spot of excitement. Let us do this, Joker![n][w][e]

[msg D05_02_e341_036_ng4_selB_3 [Fox]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4025 65535 0]Hm, I was just feeling in the mood for a[n]spot of excitement. Let us do this, Joker![n][w][e]

[msg D05_02_e341_036_ng4_mes0_2 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]It is time we make our decision, Joker.[n]What do you want to do?[n][w][e]

[msg D05_02_e341_036_ng4_selC_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Right, there's no need for any more[n]discussion. Take him down![n][w][e]

[msg D05_02_e341_036_ng4_selC_3 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]So you don't want to fight right now?[n]Then let's retreat![n][w][e]

[msg D05_13_avoid_fake_battle [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]We've already got an employee ID,[n]so we shouldn't need to pick any more[n]unnecessary fights now.[n][w][e]

[msg D05_13_Bucho_door_back_s [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can't open this from here. Try and see[n]if you can find a card reader![n][w][e]

