[msg D05_12_Door_Unlock_01 [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, looks like the door's unlocked.[n]Let's check it out, Joker.[n][w][e]

[msg D05_12_Ex3Battle_Confirm [Noir]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Are we fighting?[n][w][e]

[msg D05_12_Check_lock_door_0 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It looks like this door is locked...[n]We'll have to find some way to open it.[n][w][e]

