[msg e210_152_mes01 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7182 65535 0]Wait, this camel... We're back at the first[n]freakin' one![n][w][e]

[msg e210_152_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So they're not connected exactly as they[n]seem... We'll have to keep trying until we[n]find the right way.[n][w][e]

[msg e210_151_mes06 [Skull]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Shit, we can't get back in from here...[n][w][e]

[msg D153_007_miniEV_01_mes02 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...So he's gonna blame the world for his[n]declinin' skill?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Heh, that bastard never had any real talent[n]to begin with![n][w][e]

[msg D153_007_miniEV_02_mes02 [Panther]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh!? Even if that's true, that doesn't give[n]you the right to be deceiving people![n][w][e]

[msg D153_007_miniEV_03_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What the heck? He's basically saying he's[n]jealous of young talent...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Look at me! I was turned into a cat, but[n]I'm still fighting. Age isn't a valid excuse.[n][w][e]

[msg D153_007_miniEV_04_mes02 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So he's usin' all those pretty words,[n]but he's basically sayin' people are like[n]steppin' stones.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's just like what he did to all those[n]kids—crushed 'em for his "art"! What a[n]piece of shit![n][w][e]

[msg D153_007_miniEV_05_mes02 [Fox]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So running your atelier out of a shabby,[n]run-down shack was simply an act after[n]all...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]How foolish I was to have been deceived[n]for so long...[n][w][e]

[msg D153_007_miniEV_05_mes03 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fox...[n][w][e]

[msg D153_007_miniEV_06_mes01 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Sweet, this has gotta be the end![n][w][e]

[msg D153_007_miniEV_06_mes02 [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]How despicable...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We have encountered so many of his[n]paintings, yet not once did he mention[n]a love for art.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]These are no "paintings"...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They are just meaningless self-assertions[n]placed into picture frames...![n][w][e]

[msg D153_007_miniEV_06_mes03 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm excited to see how the change of heart[n]alters him.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Now, let's hurry![n][w][e]

[msg D02_07_EX_SHUTTER_mes01 [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]We cannot proceed like this...[n][w][e]

[msg D02_07_EX_SHUTTER_mes03 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We have to do something with these[n]shutters to go in.[n][w][e]

