[msg D157_008_miniEV_01_mes01 [Noir]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Is this the back room?[n][w][e]

[msg D157_008_miniEV_01_mes02 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Super convenient, don'tcha think?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anyway, based on what Crow was saying,[n]the games in here are all totally rigged.[n][w][e]

[msg D157_008_miniEV_01_mes03 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oooh, so we're gonna catch 'em in the act![n]I guess that's easy... C'mon, let's get to it![n][w][e]
