[msg D08_01_NPC_TALK_13_mes02 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3111 65535 0]When did these people begin to think[n]this prison is a comfortable place to live...?[n][w][e]

[msg D08_01_NPC_TALK_14_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]These people really think their wishes[n]are going to come true...?[n][w][e]

[msg D08_01_NPC_TALK_15_mes02 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9021 65535 0]...Do you think that could be the[n]Quarantine Cell we heard about?[n][w][e]

