[msg D10_15_Mission_Impossibl [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Hold on—there are a ton of tough[n]enemies down there. It'd be bad[n]if they came at us all at once.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maybe we should come back later?[n]They might move on while we[n]investigate some other place.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Orrr, do you really wanna risk going[n]down there?[n][w][e]

[msg D10_15_Mission_Impossibl_3 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]Well... if you say so. Just be careful,[n]Joker.[n][w][e]

[msg D10_15_Mission_Impossibl_4 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1023 65535 0]Yeah, let's scope out the other rooms[n]first.[n][w][e]

[msg D10_15_NPC_look_start [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Whoa whoa whoa! What's with these[n]guys!?[n][w][e]

[msg D10_15_NPC_look_01 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Whooooa, look at those freaky machines[n]they're wearing![n][w][e]

[msg D10_15_NPC_look_02 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8128 65535 0]They called this place the Treatment[n]Room, so...[n][w][e]

[msg D10_15_NPC_look_03 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]THAT'S what "treatment" is!? It sure[n]as hell don't look like it to me![n][w][e]

[msg D10_15_NPC_look_end [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's a weird gate-type-thing over[n]there, too—let's check that out next.[n][w][e]

[msg D10_15_NPC_look_another_ [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Whoa whoa whoa! What's with these[n]guys!?[n][w][e]

[msg D10_15_NPC_look_another__2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Whooooa, look at those freaky machines[n]they're wearing![n][w][e]

[msg D10_15_NPC_look_another__3 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8134 65535 0]Well, we came here from the Exam[n]Room, so...[n][w][e]
[s]It logically follows that this is the[n]Counselling Room, and those[n]people are...[n][w][e]

[msg D10_15_NPC_look_another__4 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]THAT'S what "treatment" is!? It sure[n]as hell don't look like it to me![n][w][e]

[msg D10_15_NPC_look_another__5 [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9197 65535 0]Eh, don't sweat it too much—they're all[n]cognitive beings. Let's just keep moving.[n][w][e]

[msg D10_15_discover_passward [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's another security door—that[n]means we're going to need to find[n]another clue somewhere...[n][w][e]

[msg D10_15_discover_passward_2 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Right—we probably won't know the[n]answer unless we get some sort of hint.[n][w][e]

[msg D10_15_discover_passward_3 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We should check it out just in case,[n]though.[n][w][e]

[msg D10_15_3rd_video_notExis [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]Hup, another TV—looks like we're in[n]for another movie.[n][w][e]

[msg D10_15_3rd_video_notExis_2 [Violet]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, but not right now, at least—[n]there's no tape in the player.[n][w][e]

[msg D10_15_3rd_video_notExis_3 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No doubt we'll need to find one[n]in order to proceed.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's start looking.[n][w][e]

[msg D10_15_3rd_passcode_lock_2 [Fox]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm... Another one of these doors.[n][w][e]

[msg D10_15_3rd_passcode_lock_3 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Any further time spent here will[n]be wasted.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Let's return once we have an idea[n]of the answer, Joker.[n][w][e]

[msg D10_15_3rd_passcode_lock_4 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]We need to find a hint to the answer[n]first, Joker.[n][w][e]

[msg D10_15_3rd_passcode_lock_8 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57033 65535 0]Looks like that's not it... Give it[n]another try, Joker-senpai.[n][w][e]

[msg D10_15_3rd_passcode_lock_10 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...We did it.[n][w][e]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57173 65535 0]I never would've thought I'd be the[n]password to someone's security...[n][w][e]

[msg D10_15_formidable_enemy_ [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7018 65535 0]Hey, those are some scary-lookin'[n]Shadows—make sure we don't get[n]caught.[n][w][e]

[msg D10_15_formidable_enemy__2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Looks like we've got Shadows patrolling[n]the area...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Make sure no one sneaks up on us[n]while we hunt down that videotape.[n][w][e]

[msg D10_15_something_check01 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Let's find out what's in that box.[n][w][e]

[msg D10_15_something_check_n [Mona]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1028 65535 0]Nothing here... Let's look elsewhere.[n][w][e]

[msg D10_15_after_enemies_lef [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9100 65535 0]Looks like we've got even more[n]Shadows now.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That room they exited looks kinda[n]suspicious, though—maybe we should[n]take a peek?[n][w][e]

[msg D10_15_something_check06 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Let's find out what's in that box.[n][w][e]

[msg D10_15_get_video_start [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54241 65535 0]Ah! Got it! Now to go watch the thing.[n][w][e]

[msg D10_15_get_video_end [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's the key to our success! Let's get[n]back to that TV room.[n][w][e]

[msg D162_015_mini_EV_01_mes_ [Oracle]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9040 65535 0]Whoa! Beefcake Shadow at 12 o'clock![n][w][e]

[msg D162_015_mini_EV_01_mes__2 [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He appears to be blocking the only[n]path forward in the Palace. We'd[n]better prepare for a fight.[n][w][e]

[msg D162_015_mini_EV_01_mes__3 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]He looks really tough... Are you ready,[n]Joker?[n][w][e]

[msg D162_015_mini_EV_01_mes0 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]All right, let's do this![n][w][e]

[msg D162_015_mini_EV_01_mes0_2 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]Gotcha. Let's get as ready as possible.[n][w][e]

[msg D162_015_BOSS_EV_01 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]We're here to destroy the phony utopia[n]your boss is trying to make—would you[n]mind getting out of the way?[n][w][e]

[msg D10_15_look_videoroom_st [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Joker, look![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That looks like a place where we might[n]find a videotape. Let's go check it out![n][w][e]

[msg D10_15_videoroom_remind_ [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Joker, can we check out that TV room[n]we passed?[n][w][e]

[msg D10_15_enemy_look_force_ [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7018 65535 0]Hey, those are some scary-lookin'[n]Shadows—make sure we don't get[n]caught.[n][w][e]

[msg D10_15_enemy_look_force__2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Looks like we've got Shadows patrolling[n]the area...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why don't we come back here later?[n]We shouldn't waste our energy on[n]all of them.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54703 65535 0]We passed a room a little while back—[n]the one with a TV?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why don't we check that one out?[n][w][e]

[msg D10_15_urge_check_3rd_vi_2 [Fox]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4129 65535 0]...It looks like we stopped here a bit[n]earlier than we should have.[n][w][e]

[msg D10_15_urge_check_3rd_vi_3 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We should get a hint from watching[n]the videotape. Let's come back here[n]after doing that.[n][w][e]

[msg D10_15_urge_check_3rd_vi_4 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Let's watch the video first, Joker.[n][w][e]

[msg D10_FindGate_start_inser [Panther]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]What the—[n][w][e]

[msg D10_FindGate_start [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They're just passing through that[n]weird wall of... what even IS that!?[n][w][e]

[msg D10_FindGate_02 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]So, they identify "abnormalities" in the[n]Exam Room, then "treat" them here...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Once someone is certified as "happy,"[n]they get funneled into that gate.[n][w][e]

[msg D10_FindGate_03 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Careful! You might get burned to a crisp[n]the second you touch it or something.[n][w][e]

[msg D10_FindGate_04 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]How about we DON'T jinx this?[n][w][e]

[msg D10_FindGate_05 [Announcement]]
[s]Patients may not pass without receiving[n]treatment. Please follow the instructions[n]provided elsewhere to seek treatment.[n][w][e]

[msg D10_FindGate_end [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It looks like we really aren't getting[n]through this gate.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I suppose we'll just have to find[n]another path.[n][w][e]

[msg D10_15_CheckTvWithVideo_ [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, we got the tape... I wonder[n]what we'll see this time.[n][w][e]

[msg D10_15_CheckTvWithVideo__2 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4129 65535 0]I'll wager this much: it won't be pleasant.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Regardless, we should watch it sooner[n]rather than later.[n][w][e]

[msg note_find_reaction_start [Violet]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]What could this be...? A diary?[n][w][e]

[msg note_find_reaction_01 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Looks like it. Judging from what's written[n]inside, it's most likely Maruki's...[n][w][e]

[msg note_find_reaction_watch [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Even that video from earlier... He just[n]really loves talking about himself.[n][w][e]

[msg note_find_reaction_notwa [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]It seems like he has written about things[n]in the past, but it looks like they are only[n]fragments of them...[n][w][e]

[msg note_find_reaction_end [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Doesn't look like it has any meaning to[n]it either.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Not sure if it'll come in handy for the[n]investigation, but let's hold on to it and[n]see if we can find other ones.[n][w][e]

