[msg D157_011_miniEV_01_mes01 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6165 65535 0]Are these the rules? Umm...[n]"The House of Darkness"...?[n][w][e]

[msg D157_011_miniEV_01_mes02 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's see what it says...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"In this game, you will attempt to escape[n]a pitch-black maze."[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"You are free to quit at any point and[n]start over. The game ends when you[n]reach the finish."[n][w][e]

[msg D157_011_miniEV_01_mes03 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7177 65535 0]Wait, that's it? That don't tell us shit 'cept[n]for there's a maze and it's dark.[n][w][e]

[msg D157_011_miniEV_01_mes04 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I suppose we will have to go in and find[n]out for ourselves what it is all about.[n][w][e]

[msg D157_011_miniEV_02_mes01 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3180 65535 0]Oh, these are the rules for what they call[n]the "Battle Arena."[n][w][e]

[msg D157_011_miniEV_02_mes02 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, I shall read them.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"This is a series of one-on-one, fair fights in[n]which your skills are all you can rely on."[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well... there you have it.[n][w][e]

[msg D157_011_miniEV_02_mes03 [Oracle]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9191 65535 0]So it's like the whole "Challenger[n]Approaching" thing in Super Bash Bros![n]You fight whoever shows up![n][w][e]

[msg D157_011_miniEV_02_mes04 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I suppose a criminal trial is like a battle[n]of sorts. This may be a bit more refreshing[n]though.[n][w][e]

[msg D157_011_miniEV_02_mes05 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, I'm curious as to what's waiting for us[n]inside here. Let's check it out when you're[n]ready.[n][w][e]