[msg D154_011_mini_EV_02_mes0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1176 65535 0]Hm!? Wait, Joker! Hide![n][w][e]

[msg D154_011_mini_EV_02_mes0_2 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What, more cameras?[n][w][e]

[msg D154_011_mini_EV_02_mes0_3 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1037 65535 0]No... These ones seem different from what[n]we've seen before... They turn on and off.[n][w][e]

[msg D154_011_mini_EV_02_mes0_4 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It might be a surveillance system that[n]switches between multiple cameras for[n]efficient coverage...[n][w][e]

[msg D154_011_mini_EV_02_mes0_5 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7150 65535 0]That just means we gotta pass by when[n]it's not recordin', yeah?[n][w][e]

[msg D154_011_mini_EV_02_mes0_6 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That should work... but there are guards[n]to watch out for too. We should proceed[n]with caution![n][w][e]

