[msg D157_013_miniEV_01_mes01 [Crow]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8020 65535 0]Ah, we were able to circumvent the wall[n]of cards, it seems.[n][w][e]

[msg D157_013_miniEV_01_mes02 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Man, that long way 'round shit is bull![n]Where's that bastard from earlier, huh!?[n][w][e]

[msg e382_235_mes01 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6194 65535 0]Hey, isn't this the thing that Shadow was[n]messing with?[n][w][e]

[msg e382_235_mes02 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, we have an escape route now! We can[n]proceed onward without having to worry[n]about it anymore.[n][w][e]

[msg D06_mini_ev03_mes4 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What the heck? This is a piece of cake.[n]We got this, no problem![n][w][e]

[msg D06_mini_ev03_mes5 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hopefully it continues being as simple[n]as it is now...[n][w][e]

[msg D06_mini_ev03_mes18 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You bastard! This shit's rigged![n][w][e]

[msg D06_mini_ev03_mes20 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You knew exactly what numbers we[n]were using![n][w][e]

[msg D06_mini_ev03_mes22 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You just happened to, hm?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Very well. But your tricks will not work[n]on us again.[n][w][e]

[msg D06_mini_ev03_mes24 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's wrong? We won, yes?[n][w][e]

[msg D06_mini_ev03_mes26 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Come, let us continue.[n][w][e]

[msg D06_mini_ev03_mes28 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Look who's talking...[n][w][e]

[msg D06_mini_ev03_mes29 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We are most certainly not cheating. False[n]accusations are unbecoming, you know.[n][w][e]

[msg D06_mini_ev03_mes30 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's right! Anyways, let's keep this[n]shit rollin'![n][w][e]

[msg D06_13_TRUMP_END_mes01 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, this is our victory.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What was the prize again? You said you[n]would double the coins in our possession,[n]did you not?[n][w][e]

[msg D06_13_TRUMP_END_mes03 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? What are you scheming?[n][w][e]

[msg D06_13_TRUMP_END_mes05 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is freakin' ridiculous.[n][w][e]

[msg D06_13_TRUMP_END_mes06 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It should be a simple finish.[n][w][e]

[msg D06_13_TRUMP_END_mes7 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's get it over with then![n][w][e]

[msg Card_Battle_LAST_02 [Skull]]
[s]Dammit, quit messin' around...[n]This has gotta be rigged![n][w][e]

[msg Card_Battle_LAST03_01 [Crow]]
[s]Hold on a moment. Are you certain[n]you're not cheating here?[n][w][e]

[msg Card_Battle_LAST03_03 [Crow]]
[s]Hmph, I expect that means you've[n]rigged this game in a manner[n]that is difficult to prove.[n][w][e]

[msg Card_Battle_LAST03_05 [Crow]]
[s]Very well then. Let us continue playing.[n][w][e]

