[msg mini_ev_mes_02_02_03_mes [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Stop, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Slot machines are essentially synonymous[n]with control. It would be simple for them[n]to rig these.[n][w][e]

[msg mini_ev_mes_02_02_03_mes_2 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So you're saying we'll never win if we[n]continue on like this.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...That is, unless we can do something[n]about it.[n][w][e]

[msg mini_ev_mes_02_01_mes08 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]I understand how you feel, but we have to[n]prioritize breaking through their cheating,[n]Joker.[n][w][e]

[msg mini_ev_mes_02_01_mes09 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I think there's prolly a terminal back[n]behind it. Try looking there, Joker.[n][w][e]

[msg D157_010_miniEV_01_mes01 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The enemy seems unwilling to leave[n]that area... Is there something it wants[n]to protect?[n][w][e]

[msg D157_010_miniEV_01_mes02 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm not sure... Do you think we should[n]take it down?[n][w][e]

[msg D157_010_miniEV_01_mes03 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yes, we should do so as quick as possible.[n][w][e]

[msg D157_010_miniEV_01_mes04 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aight! We can take our sweet time lookin'[n]at what's over there once we kick that[n]thing's ass![n][w][e]

[msg SLOT_SAIKU_02 [Oracle]]
[s]This big thing controlled all the slots[n]around here.[n][w][e]
[s]Anyway, I reprogrammed some stuff,[n]so it should be easier to win on[n]the smaller slots now too.[n][w][e]
[s]You can choose what we do next, Joker.[n][w][e]

[msg e380_220_mes9 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We'll have to try another control panel.[n]We can't disable the cheating mechanism[n]from here.[n][w][e]

[msg mini_ev_mes_02_02_mes01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's put a stop to the whole cheating[n]business first. Look around for anything[n]suspicious.[n][w][e]

[msg mini_ev_mes_02_02_mes02 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let us go play the large slot first.[n]We wouldn't want other customers[n]playing it in our stead.[n][w][e]

[msg mini_ev_mes_02_02_selA_0 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_02_02_selA_1 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg D07_10_BIG_SLOT_mes01 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's put a stop to the whole cheating[n]business first. Look around for anything[n]suspicious.[n][w][e]

[msg D07_10_BIG_SLOT_mes02 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Awwww yeahhhh! Let's make some[n]freakin' money![n][w][e]

[msg D07_10_BIG_SLOT_mes03 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do your thing, Joker![n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Whoa, this is amazing...![n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_2 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]W-W-We won! Everyone, look![n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_3 [Crow]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I suppose in the gambling world,[n]this would be an apt time to say,[n]"Winner winner, chicken dinner"...[n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_4 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Huh?[n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_5 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Never mind.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Regardless, we have acquired our target[n]amount. Let us trade these coins in for a[n]high limit card.[n][w][e]

[msg D07_10_BIG_SLOT_selA_1_m [Oracle]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why!?[n][w][e]

[msg D07_10_BIG_SLOT_selA_1_m_2 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do we not have enough coins...?[n][w][e]

[msg D07_10_BIG_SLOT_selA_2_m [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_02_mes05 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It would look suspicious if we continued[n]spending here. Let us cease using this slot[n]for now.[n][w][e]

[msg D06_SLOT_CONSOLE_NOT_mes [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Joker, I suggest we examine that giant[n]slot machine first.[n][w][e]

[msg seigyoban_mes01 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]We won't be able to stop their cheating[n]from here...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It looks like there are multiple different-[n]colored control panels throughout this[n]area.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Out of those, I'll need the [clr 2]red[clr 27] and [clr 2]green[clr 27][n]ones. I should be able to control things[n]from there.[n][w][e]

[msg seigyoban_mes02 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7192 65535 0]But where're they gonna be?[n][w][e]

[msg seigyoban_mes03 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]One's most likely [clr 2]near the entrance[clr 27] to the[n]area. That's how far the signal reached.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The other should be back in the [clr 2]staff-[n]only area[clr 27] somewhere... At least, that's[n]what I'd guess.[n][w][e]

[msg seigyoban_mes04 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8021 65535 0]Hm, the entrance to the slot area... and[n]somewhere back in the staff-only area...[n][w][e]

[msg seigyoban_mes05 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]We won't be able to stop their cheating[n]from here...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'll need you to find me the [clr 2]red[clr 27] and[n]the [clr 2]green[clr 27] control panels. I think I can[n]fix things from there.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, but the red one's all set. You just[n]have to find the [clr 2]green[clr 27] one now, and[n]we'll be good.[n][w][e]

[msg seigyoban_mes06 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]The green control panel... Where's that[n]one, again?[n][w][e]

[msg seigyoban_mes07 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, the red one was near the entrance...[n]so it's probably back in the [clr 2]staff-only area[clr 27].[n][w][e]

[msg seigyoban_mes08 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm... So I suppose it would have to be[n]somewhere devoid of customers.[n][w][e]

[msg seigyoban_mes09 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]Mkay, all we gotta do now is start lookin'![n][w][e]

[msg seigyoban_mes10 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]We won't be able to stop their cheating[n]from here...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'll need you to find me the [clr 2]red[clr 27] and[n]the [clr 2]green[clr 27] control panels. I think I can[n]fix things from there.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, but the green one's all set. You just[n]have to find the [clr 2]red[clr 27] one now, and we'll[n]be good.[n][w][e]

[msg seigyoban_mes11 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]You know where that is?[n][w][e]

[msg seigyoban_mes12 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well the green one was in the staff[n]passageway, so the red one should[n]be [clr 2]near the entrance[clr 27]![n][w][e]

[msg seigyoban_mes13 [Fox]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]The entrance to the slot area... That was[n]where that Shadow was waiting for us...[n][w][e]

