[msg AREA_EXIT_mes01 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's chase after Mona for now.[n][w][e]

[msg mona_chase_ng_mes01 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tch, he ain't here... C'mon, we gotta look[n]on another path![n][w][e]

[msg mona_chase_ng_mes02 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is not where he is... Let us go[n]elsewhere![n][w][e]

[msg mona_chase_ng_mes03 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He isn't here... Let's try searching on a[n]different path![n][w][e]

[msg D05_02_e334_105_mes01 [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, where are you going!? Mona's not[n]down that way![n][w][e]

