[msg D04_07_floor_trap_start [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]Talk about a close call... We almost[n]found out what life's like for a[n]pincushion.[n][w][e]

[msg D04_07_floor_trap_01 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]How're we supposed to get to the[n]other side with the floor like this?[n][w][e]

[msg D04_07_floor_trap_02 [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is the point where we check our[n]surroundings carefully. There has to[n]be something we can use...[n][w][e]

[msg D04_07_floor_trap_03 [Mona]]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1183 65535 0]Ooh![n][w][e]

[msg D04_07_floor_trap_end [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'd bet your grappling hook would[n]catch that just fine, Joker—give it[n]a shot![n][w][e]

