[msg D157_007_miniEV_01_mes01 [Queen]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A Shadow...![n][w][e]

[msg D157_007_miniEV_01_mes03 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yup, that's why we're here.[n][w][e]

[msg D157_007_miniEV_01_mes05 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It appears we cannot avoid interferences[n]in here.[n][w][e]

[msg D157_007_miniEV_01_mes06 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Same as the floor below...[n][w][e]

[msg D157_007_miniEV_01_mes07 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wait, why aren't the guests around us[n]reacting to our battle?[n][w][e]

[msg D157_007_miniEV_01_mes08 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That might be Sae-san's perception[n]towards the people of the court.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Even though you fight to carry out[n]justice... their indifference leads you[n]to feeling isolated.[n][w][e]

[msg D157_007_miniEV_01_mes9 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You may be right...[n][w][e]

[msg D157_007_miniEV_01_mes10 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Even over here, there are Shadows[n]attacking us...[n][w][e]

[msg D157_007_miniEV_01_mes11 [Panther]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pretty hospitable, huh?[n][w][e]

[msg D157_007_miniEV_07_mes01 [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6162 65535 0]Amazing... We managed to get our hands[n]on [var 0] coins...[n][w][e]

[msg D157_007_miniEV_07_mes02 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We still have a long way before we reach[n]our goal though. Now then, on to the slot[n]machines.[n][w][e]

