[msg D157_008_miniEV_01_mes01 [Noir]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Is this the back room?[n][w][e]

[msg D157_008_miniEV_01_mes02 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Super convenient, don'tcha think?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anyway, based on what Crow was saying,[n]the games in here are all totally rigged.[n][w][e]

[msg D157_008_miniEV_01_mes03 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oooh, so we're gonna catch 'em in the act![n]I guess that's easy... C'mon, let's get to it![n][w][e]

[msg D157_009_miniEV_01_mes01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A Shadow![n][w][e]

[msg D157_009_miniEV_01_mes03 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here to make money, not to play[n]your games![n][w][e]

[msg D157_009_miniEV_01_mes05 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It appears we cannot avoid interferences[n]in here.[n][w][e]

[msg D157_009_miniEV_01_mes06 [Oracle]]
[s][bup 0 8 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Same as the floor below...[n][w][e]

[msg D157_009_miniEV_01_mes07 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wait, why aren't the guests around us[n]reacting to our battle?[n][w][e]

[msg D157_009_miniEV_01_mes8 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That might be Sae-san's perception[n]towards the people of the court.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Even though you fight to carry out[n]justice... their indifference leads you[n]to feeling isolated.[n][w][e]

[msg D157_009_miniEV_01_mes9 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You may be right...[n][w][e]

[msg D157_009_miniEV_01_mes10 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Even over here, there are Shadows[n]attacking us...[n][w][e]

[msg D157_009_miniEV_01_mes11 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pretty hospitable, huh?[n][w][e]

