[msg D10_005_Return_to_Entran [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57047 65535 0]If we don't have any other business here,[n]should we go back to the entrance?[n][w][e]

[msg D10_005_Return_to_Entran_3 [Violet]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, let's head back and rest up.[n][w][e]

[msg D10_005_Return_to_Entran_4 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, but... Make sure you don't[n]overexert yourself, okay?[n][w][e]

