[msg D01_e490_031_mes01 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So this is what made him the asshole he is[n]now![n][w][e]

[msg D01_e490_031_mes02 [Panther]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Makes sense that you'd want to hide the[n]reason you turned into such a dick![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No one would show him any mercy if[n]they saw that![n][w][e]

[msg D01_e490_031_mes03 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I know what you mean, but Kamoshida[n]probably feels the same way about us.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What we just did is like barging into his[n]house and going through all his personal[n]possessions.[n][w][e]

[msg D01_e490_031_mes04 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You mean he's pissed 'cuz we went ahead[n]and looked into his past?[n][w][e]

[msg D01_e490_031_mes05 [Panther]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're WAY more pissed than him! And he's[n]gonna find out soon enough![n][w][e]

[msg D01_e490_031_mes06 [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's good to see you've still got that[n]determination. We've got this![n][w][e]

