[msg D157_009_miniEV_01_mes02 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2037 65535 0]We're here to make money, not to play[n]your games![n][w][e]

[msg D157_009_miniEV_01_mes04 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]It appears as though these interferences[n]are unavoidable. We must be ever-[n]vigilant.[n][w][e]

[msg D157_009_miniEV_01_mes05 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wait, why didn't the guests around us[n]react to that battle?[n][w][e]

[msg D157_009_miniEV_01_mes06 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It is probably due to Sae-san's perception[n]of the other people in the courtroom.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perhaps as she sees it, they only care[n]for their own victory, while ignoring[n]the needs of others.[n][w][e]

[msg D157_009_miniEV_01_mes07 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2022 65535 0]That reaction is certainly different from[n]what we saw on the lower floor.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I wonder if that trend grows stronger[n]the higher up you go in the court system.[n][w][e]

[msg D157_009_miniEV_01_mes08 [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It is possible. In any case, we can now[n]freely access the Slot Room. We should[n]go look around.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Although I doubt we will find a fair fight[n]waiting for us in this scamming casino.[n][w][e]

[msg D157_009_miniEV_04_GET_m [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, is this the key?[n][w][e]

[msg D157_009_miniEV_04_GET_m_2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wahoooo, let's take this and head back[n]to the control unit![n][w][e]

[msg D157_009_miniEV_05_GET_m [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, it's and operation key![n][w][e]

[msg D157_009_miniEV_05_GET_m_2 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perfect. Now we will be able to use[n]the control unit.[n][w][e]

[msg D157_009_miniEV_06_GET_m [Noir]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Look, it's an operation key![n][w][e]

[msg D157_009_miniEV_06_GET_m_2 [Queen]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Now we can operate the control unit...[n][w][e]

[msg D157_009_miniEV_07_GET_m [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm... I found the operation key![n][w][e]

[msg D157_009_miniEV_07_GET_m_2 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Now we have four of them...[n]There's only one left![n][w][e]

[msg D157_009_miniEV_08_GET_m [Crow]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh... I found an operation key.[n][w][e]
[s]This is our fifth and final one.[n]Let us head to the control unit.[n][w][e]

