[msg mini_EV_e205_111_selA_2_ [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_EV_e205_111_mes02 [Skull]]
[s][bup 0 2 100 0 0]......[n][w][e]

[msg mini_EV_e210_144_selA_2_ [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_EV_e210_144_mes04 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, I guess we got what we came[n]here for.[n][w][e]

[msg mini_EV_e210_144_mes05 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He said he wrote the password down[n]at Madarame's feet...[n][w][e]

[msg mini_EV_e210_144_mes6 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Like, he wrote it on Madarame's actual[n]feet? That can't be it...[n][w][e]

[msg mini_EV_e210_144_mes7 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do you suppose it's a metaphor?[n][w][e]

[msg mini_EV_e210_144_mes8 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, whatever he's talking about,[n]it can't be far—not if he needs to[n]check quickly.[n][w][e]
[s]Let's look for anything feet-sy![n][w][e]

