[msg PARTY_IN_CHECK_PC02_mes0 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]I'm ready whenever you need me![n]Put me in, coach![n][w][e]

[msg PARTY_IN_CHECK_PC02_EX_m [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]We've come real far, man. You sure[n]you want me fightin'?[n][w][e]

[msg PARTY_IN_CHECK_PC02_selA_2 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Mkay, you can count on me![n][w][e]

[msg PARTY_IN_CHECK_PC02_selA_3 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7193 65535 0]You sure? Welp, you can count on me[n]whenever you're feelin' it![n][w][e]

[msg PARTY_IN_CHECK_PC02_mes0_2 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7190 65535 0]Looks like you already got a full roster.[n]Who do you wanna take outta the lineup?[n][w][e]

[msg PARTY_IN_CHECK_PC03_mes0 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]You want me in the starting lineup?[n]Sounds good to me![n][w][e]

[msg PARTY_IN_CHECK_PC03_EX_m [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]This is the last battle, so I'll give the fight[n]everything I have![n][w][e]

[msg PARTY_IN_CHECK_PC03_selA_2 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1116 65535 0]All right, let's go![n][w][e]

[msg PARTY_IN_CHECK_PC03_selA_3 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Okay, don't be afraid to come to me[n]if you need some help.[n][w][e]

[msg PARTY_IN_CHECK_PC03_mes0_2 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1021 65535 0]Your starting lineup's already full...[n]Pick someone to switch out.[n][w][e]

[msg PARTY_IN_CHECK_PC04_mes0 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6018 65535 0]You want me to fight?[n][w][e]

[msg PARTY_IN_CHECK_PC04_EX_m [Panther]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6156 65535 0]Let's put an end to this here, Joker![n]Do you want me in the party?[n][w][e]

[msg PARTY_IN_CHECK_PC04_selA_2 [Panther]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6060 65535 0]Yeah, let's do this![n][w][e]

[msg PARTY_IN_CHECK_PC04_selA_3 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6020 65535 0]Got it. Just talk to me if you change[n]your mind, okay?[n][w][e]

[msg PARTY_IN_CHECK_PC04_mes0_2 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6186 65535 0]Your party's full though... Who do you[n]want me to switch with?[n][w][e]

[msg PARTY_IN_CHECK_PC05_mes0 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4104 65535 0]Hm? Shall I join the vanguard?[n][w][e]

[msg PARTY_IN_CHECK_PC05_EX_m [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4083 65535 0]I am fully prepared for this final battle...[n]Please include me if you consider[n]it necessary.[n][w][e]

[msg PARTY_IN_CHECK_PC05_selA_2 [Fox]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4136 65535 0]I will ensure you don't come to regret[n]this decision.[n][w][e]

[msg PARTY_IN_CHECK_PC05_selA_3 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4020 65535 0]Understood. I will hold my ground as[n]a member of the rear guard.[n][w][e]

[msg PARTY_IN_CHECK_PC05_mes0_2 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]It seems the vanguard is already packed[n]full. Please designate a person with[n]whom I should switch.[n][w][e]

[msg PARTY_IN_CHECK_PC05_D02_ [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4150 65535 0]Please allow me to join the vanguard,[n]Joker. I will not disappoint you,[n]I promise.[n][w][e]

[msg PARTY_IN_CHECK_PC05_D02__3 [Fox]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4177 65535 0]Thank you. We will change Madarame's[n]heart, no matter what![n][w][e]

[msg PARTY_IN_CHECK_PC05_D02__4 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4026 65535 0]Then I shall remain prepared for the off[n]chance you choose to include me later on.[n][w][e]

[msg PARTY_IN_CHECK_PC05_D02__5 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]It seems the vanguard is already packed[n]full. Please designate a person with[n]whom I should switch.[n][w][e]

[msg PARTY_IN_CHECK_PC06_mes0 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]You'd like me as part of your team?[n]Sure, I don't mind.[n][w][e]

[msg PARTY_IN_CHECK_PC06_EX_m [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2165 65535 0]Let's settle this once and for all. If you[n]want me to fight, I will gladly accept![n][w][e]

[msg PARTY_IN_CHECK_PC06_selA_2 [Queen]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2048 65535 0]I won't let you down![n][w][e]

[msg PARTY_IN_CHECK_PC06_selA_3 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2022 65535 0]Very well. I suppose it's not a bad thing[n]to be cautious with these kinds of[n]decisions.[n][w][e]

[msg PARTY_IN_CHECK_PC06_mes0_2 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]It seems you already have enough[n]people on your team. Who would[n]you like me to switch with?[n][w][e]

[msg PARTY_IN_CHECK_PC06_D03_ [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2150 65535 0]Would it be okay if I accompany you[n]for battle? I assure you, I will be useful[n]to the team.[n][w][e]

[msg PARTY_IN_CHECK_PC06_D03__3 [Queen]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2196 65535 0]Thank you... You won't regret it.[n][w][e]

[msg PARTY_IN_CHECK_PC06_D03__4 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2026 65535 0]Just let me know if you need my strength.[n]I'll be ready to go at any time.[n][w][e]

[msg PARTY_IN_CHECK_PC06_D03__5 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]It seems you already have enough[n]people on your team. Who would[n]you like me to switch with?[n][w][e]

[msg PARTY_IN_CHECK_PC07_mes0 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3001 65535 0]Me, fight? Okay, I'll work extra hard[n]for you today![n][w][e]

[msg PARTY_IN_CHECK_PC07_EX_m [Noir]]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3158 65535 0]We're the only ones who can save the[n]world now... Please let me fight, Joker.[n]I know I can help![n][w][e]

[msg PARTY_IN_CHECK_PC07_selA_2 [Noir]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3199 65535 0]Great, I'll give it my all![n][w][e]

[msg PARTY_IN_CHECK_PC07_selA_3 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3020 65535 0]I see. In that case, I can handle taking[n]care of backup.[n][w][e]

[msg PARTY_IN_CHECK_PC07_mes0_2 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]It seems as though the fighting team is[n]already set. Who would you like me to[n]switch with?[n][w][e]

[msg PARTY_IN_CHECK_PC07_D05_ [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3158 65535 0]Joker, do you mind if I join you today?[n]I'm sure I can be of help.[n][w][e]

[msg PARTY_IN_CHECK_PC07_D05__3 [Noir]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3030 65535 0]I won't let you down![n][w][e]

[msg PARTY_IN_CHECK_PC07_D05__4 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3022 65535 0]I see. In that case, I'll do my best to[n]provide support from the rear.[n][w][e]

[msg PARTY_IN_CHECK_PC07_D05__5 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]It seems as though the fighting team is[n]already set. Who would you like me to[n]switch with?[n][w][e]

[msg FUTABA_PARTY_SCOUT [Oracle]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9055 65535 0]I got all the navigation you need right here![n][w][e]

[msg FUTABA_PARTY_SCOUT_EX [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9177 65535 0]Don't worry Joker, I'm here with you.[n]Let's win this time![n][w][e]

[msg FUTABA_PARTY_SCOUT_EX02 [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9055 65535 0]Joker, you okay?[n][w][e]
[s]It's okay to head back and get some[n]more equipment and items ready if[n]you need to![n][w][e]

[msg PARTY_IN_CHECK_PC09_mes0 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8019 65535 0]It would be a mistake not selecting me[n]for this. You understand, do you not?[n][w][e]

[msg PARTY_IN_CHECK_PC09_selA_2 [Crow]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8151 65535 0]Superb judgment, Joker![n][w][e]

[msg PARTY_IN_CHECK_PC09_selA_3 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]If that is what you desire.[n][w][e]

[msg PARTY_IN_CHECK_PC09_mes0_2 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]Ah, there seem to be quite a few people[n]already on the team. Could you tell me[n]who to switch with?[n][w][e]

[msg PARTY_IN_CHECK_PC10_mes0 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57144 65535 0]Do you want me to join the main team?[n]Don't worry, I can be ready anytime![n][w][e]

[msg PARTY_IN_CHECK_PC10_selA_2 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57106 65535 0]Got it! I'll be sure to do my part![n][w][e]

[msg PARTY_IN_CHECK_PC10_selA_3 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57055 65535 0]All right. I'll stay warmed up in case[n]you need me.[n][w][e]

[msg PARTY_IN_CHECK_PC10_mes0_2 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Oh, but you've already got a full team.[n]Who should I switch places with?[n][w][e]

[msg PARTY_IN_CHECK_PC02_NM_m [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]I'm ready whenever you need me![n]Put me in, coach![n][w][e]


[msg PARTY_IN_CHECK_PC02_NM_s_2 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Mkay, you can count on me![n][w][e]

[msg PARTY_IN_CHECK_PC02_NM_s_3 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7193 65535 0]You sure? Welp, you can count on me[n]whenever you're feelin' it![n][w][e]

[msg PARTY_IN_CHECK_PC02_NM_m_2 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7190 65535 0]Looks like you already got a full roster.[n]Who do you wanna take outta the lineup?[n][w][e]

[msg PARTY_IN_CHECK_PC04_NM_m [Panther]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6018 65535 0]You want me to fight?[n][w][e]

[sel PARTY_IN_CHECK_PC04_NM_s top]
[s]I'll be counting on you.[e]
[s]Actually, stay here.[e]

[msg PARTY_IN_CHECK_PC04_NM_s_2 [Panther]]
[s][bup 0 4 1 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6060 65535 0]Yeah, let's do this![n][w][e]

[msg PARTY_IN_CHECK_PC04_NM_s_3 [Panther]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6020 65535 0]Got it. Just talk to me if you change[n]your mind, okay?[n][w][e]

[msg PARTY_IN_CHECK_PC04_NM_m_2 [Panther]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6186 65535 0]Your party's full though... Who do you[n]want me to switch with?[n][w][e]

[msg PARTY_IN_CHECK_PC05_NM_m [Fox]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4104 65535 0]Hm? Shall I join the vanguard?[n][w][e]

[sel PARTY_IN_CHECK_PC05_NM_s top]
[s]I'll be counting on you.[e]
[s]Actually, stay here.[e]

[msg PARTY_IN_CHECK_PC05_NM_s_2 [Fox]]
[s][bup 0 5 1 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4136 65535 0]I will ensure you don't come to regret[n]this decision.[n][w][e]

[msg PARTY_IN_CHECK_PC05_NM_s_3 [Fox]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4020 65535 0]Understood. I will hold my ground as[n]a member of the rear guard.[n][w][e]

[msg PARTY_IN_CHECK_PC05_NM_m_2 [Fox]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]It seems the vanguard is already packed[n]full. Please designate a person with[n]whom I should switch.[n][w][e]

[msg PARTY_IN_CHECK_PC06_NM_m [Queen]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]You'd like me as part of your team?[n]Sure, I don't mind.[n][w][e]

[sel PARTY_IN_CHECK_PC06_NM_s top]
[s]I'll be counting on you.[e]
[s]Actually, stay here.[e]

[msg PARTY_IN_CHECK_PC06_NM_s_2 [Queen]]
[s][bup 0 6 1 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2048 65535 0]I won't let you down![n][w][e]

[msg PARTY_IN_CHECK_PC06_NM_s_3 [Queen]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2022 65535 0]Very well. I suppose it's not a bad thing[n]to be cautious with these kinds of[n]decisions.[n][w][e]

[msg PARTY_IN_CHECK_PC06_NM_m_2 [Queen]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]It seems you already have enough[n]people on your team. Who would[n]you like me to switch with?[n][w][e]

[msg PARTY_IN_CHECK_PC02_NM02 [Ryuji]]
[s][bup 0 2 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]I'm ready whenever you need me![n]Put me in, coach![n][w][e]

[sel PARTY_IN_CHECK_PC02_NM02_2 top]
[s]I'll be counting on you.[e]
[s]Actually, stay here.[e]

[msg PARTY_IN_CHECK_PC02_NM02_3 [Ryuji]]
[s][bup 0 2 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Mkay, you can count on me![n][w][e]

[msg PARTY_IN_CHECK_PC02_NM02_4 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7193 65535 0]You sure? Welp, you can count on me[n]whenever you're feelin' it![n][w][e]

[msg PARTY_IN_CHECK_PC02_NM02_5 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7190 65535 0]Looks like you already got a full roster.[n]Who do you wanna take outta the lineup?[n][w][e]

[msg PARTY_IN_CHECK_PC04_NM02 [Panther]]
[s][bup 0 4 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6018 65535 0]You want me to fight?[n][w][e]

[sel PARTY_IN_CHECK_PC04_NM02_2 top]
[s]I'll be counting on you.[e]
[s]Actually, stay here.[e]

[msg PARTY_IN_CHECK_PC04_NM02_3 [Panther]]
[s][bup 0 4 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6060 65535 0]Yeah, let's do this![n][w][e]

[msg PARTY_IN_CHECK_PC04_NM02_4 [Panther]]
[s][bup 0 4 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6020 65535 0]Got it. Just talk to me if you change[n]your mind, okay?[n][w][e]

[msg PARTY_IN_CHECK_PC04_NM02_5 [Panther]]
[s][bup 0 4 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6186 65535 0]Your party's full though... Who do you[n]want me to switch with?[n][w][e]

[msg PARTY_IN_CHECK_PC05_NM02 [Fox]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4104 65535 0]Hm? Shall I join the vanguard?[n][w][e]

[sel PARTY_IN_CHECK_PC05_NM02_2 top]
[s]I'll be counting on you.[e]
[s]Actually, stay here.[e]

[msg PARTY_IN_CHECK_PC05_NM02_3 [Fox]]
[s][bup 0 5 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4136 65535 0]I will ensure you don't come to regret[n]this decision.[n][w][e]

[msg PARTY_IN_CHECK_PC05_NM02_4 [Fox]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4020 65535 0]Understood. I will hold my ground as[n]a member of the rear guard.[n][w][e]

[msg PARTY_IN_CHECK_PC05_NM02_5 [Fox]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]It seems the vanguard is already packed[n]full. Please designate a person with[n]whom I should switch.[n][w][e]

[msg PARTY_IN_CHECK_PC06_NM02 [Queen]]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]You'd like me as part of your team?[n]Sure, I don't mind.[n][w][e]

[sel PARTY_IN_CHECK_PC06_NM02_2 top]
[s]I'll be counting on you.[e]
[s]Actually, stay here.[e]

[msg PARTY_IN_CHECK_PC06_NM02_3 [Queen]]
[s][bup 0 6 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2048 65535 0]I won't let you down![n][w][e]

[msg PARTY_IN_CHECK_PC06_NM02_4 [Queen]]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2022 65535 0]Very well. I suppose it's not a bad thing[n]to be cautious with these kinds of[n]decisions.[n][w][e]

[msg PARTY_IN_CHECK_PC06_NM02_5 [Queen]]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]It seems you already have enough[n]people on your team. Who would[n]you like me to switch with?[n][w][e]

[msg PARTY_IN_CHECK_PC07_NM02 [Noir]]
[s][bup 0 7 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3001 65535 0]Me, fight? Okay, I'll work extra hard[n]for you today![n][w][e]

[msg PARTY_IN_CHECK_PC07_NM02_3 [Noir]]
[s][bup 0 7 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3199 65535 0]Great, I'll give it my all![n][w][e]

[msg PARTY_IN_CHECK_PC07_NM02_4 [Noir]]
[s][bup 0 7 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3020 65535 0]I see. In that case, I can handle taking[n]care of backup.[n][w][e]

[msg PARTY_IN_CHECK_PC07_NM02_5 [Noir]]
[s][bup 0 7 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]It seems as though the fighting team is[n]already set. Who would you like me to[n]switch with?[n][w][e]

[msg FUTABA_PARTY_SCOUT_NM02 [Oracle]]
[s][bup 0 8 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9055 65535 0]I got all the navigation you need right here![n][w][e]

[msg PARTY_IN_CHECK_PC09_NM02 [Crow]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8019 65535 0]It would be a mistake not selecting me[n]for this. You understand, do you not?[n][w][e]

[msg PARTY_IN_CHECK_PC09_NM02_3 [Crow]]
[s][bup 0 9 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8151 65535 0]Superb judgment, Joker![n][w][e]

[msg PARTY_IN_CHECK_PC09_NM02_4 [Crow]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]If that is what you desire.[n][w][e]

[msg PARTY_IN_CHECK_PC09_NM02_5 [Crow]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]Ah, there seem to be quite a few people[n]already on the team. Could you tell me[n]who to switch with?[n][w][e]

[sel PARTY_SEL top]
[s]Skull[e]
[s]Mona[e]
[s]Panther[e]
[s]Fox[e]
[s]Queen[e]
[s]Noir[e]
[s]Oracle[e]
[s]Crow[e]
[s]Violet[e]
[s]Cancel[e]

[msg D156_01_npc_01_mes01 [Noir]]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3158 65535 0]I can fight too! Please, put me on the[n]front lines![n][w][e]

[msg D156_01_npc_01_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1037 65535 0]No, your Persona is too weak. It would[n]be dangerous to have you out seeing[n]action, so leave this to us.[n][w][e]

[msg D156_01_npc_01_mes03 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3022 65535 0]Okay...[n][w][e]

[msg D162_01_npc_01_mes01 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57136 65535 0]I want to talk to Dr. Maruki. Please, let me[n]come with you.[n][w][e]

