[msg D10_09_NPC_01_begining_m [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]All right, let's try asking this guy.[n][w][e]

[msg D10_09_NPC_01_reason_mes [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4090 65535 0]Is there a reason you didn't even[n]hesitate?[n][w][e]

[msg D10_09_NPC_01_reason_mes_3 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6197 65535 0]Yeah... Stuff like that can make you[n]feel totally horrible...[n][w][e]

[msg D10_09_NPC_01_reason_mes_4 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Even if it ends up hurtin', it's still better[n]to go with whatever choice you won't[n]regret later.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7138 65535 0]"A" sounds like the right answer to me.[n][w][e]

[msg D10_09_NPC_02_begining_m [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Hey, you got a sec?[n][w][e]

[msg D10_09_NPC_02_sel_01_01__2 [Noir]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Joker, you should probably consider[n]your phrasing here.[n][w][e]

[msg D10_09_NPC_02_sel_02_03__2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So they don't have a clue that their[n]cognitions could be overwritten[n]depending on their answer...[n][w][e]

[msg D10_09_NPC_02_reason_mes_2 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]So you're the type to ask others for help.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I mean, that ain't wrong, but don't you[n]ever think to yourself, "I wanna help[n]them"?[n][w][e]

[msg D10_09_NPC_02_reason_mes_4 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3081 65535 0]So it's your consideration for others[n]that made you choose "B"... Well,[n]thank you for your time.[n][w][e]

[msg D10_09_NPC_03_sel_01_01__2 [Violet]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57033 65535 0]Does that mean you have a dream[n]already?[n][w][e]

[msg D10_09_NPC_03_reason_mes_2 [Violet]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57030 65535 0]But, but—working hard towards your[n]dream is healthy![n][w][e]

[msg D10_09_NPC_03_reason_mes_5 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57039 65535 0]Thank you so much! I hope you make it[n]big soon![n][w][e]

[msg D10_09_NPC_04_begining_m_2 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1022 65535 0]What the heck is with this guy...?[n]He's so pushy...[n][w][e]

[msg D10_09_NPC_04_sel_02_01__3 [Queen]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do we really need the unabridged[n]version?[n][w][e]

[msg D10_09_NPC_04_sel_04_01_ [Oracle]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9115 65535 0]You just HAD to ask, Joker...[n][w][e]

[msg D10_09_NPC_04_reason_mes_2 [Fox]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4129 65535 0]So you're doing it for the money...[n][w][e]

[msg D10_09_NPC_04_reason_mes_4 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9128 65535 0]Oh, so he's flame baiting—saying[n]outrageous stuff just for the attention.[n][w][e]

[msg D10_09_NPC_04_reason_mes_5 [Skull]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sooo, all this stuff you're goin' on about...[n]Basically, it boils down to you talkin' shit[n]about other people for money, yeah?[n][w][e]

[msg D10_09_NPC_04_reason_mes_7 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2117 65535 0]I don't know how I should feel about all[n]this—you spread negativity, but it's not[n]entirely for personal gain...[n][w][e]

[msg D10_09_NPC_04_reason_mes_9 [Skull]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, yeah, whatever. Just go already.[n][w][e]

[msg D10_09_NPC_04_goodbay_me_2 [Noir]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That really wore me out, for some[n]reason...[n][w][e]

[msg D10_09_NPC_05_reason_mes_2 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6001 65535 0]What do you mean? Don't you want[n]to make your dream come true?[n][w][e]

[msg D10_09_NPC_05_reason_mes_4 [Fox]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4022 65535 0]I personally believe that pursuing[n]something is a wonderful thing...[n]I suppose it depends on the person.[n][w][e]

[msg D10_09_NPC_05_reason_mes_6 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, he's avoiding dreams that might not[n]come true because it's easier?[n][w][e]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's not the worst advice, but still...[n][w][e]

[msg D10_09_NPC_06_reason_mes [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]Have you decided your answer yet?[n][w][e]

[msg D10_09_NPC_06_reason_mes_3 [Violet]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57114 65535 0]So you'll choose "A: Steal something valuable"?[n][w][e]

[msg D10_09_NPC_06_reason_mes_5 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2128 65535 0]So she would wish to fund her dream[n]if there were no risks involved...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I suppose we should consider what[n]Dr. Maruki's stance on that would be.[n][w][e]

[msg D10_09_NPC_07_begining_m_2 [Noir]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3200 65535 0]Yes, we're going around asking how[n]others intend to answer the questions.[n]Have you come to a decision yet?[n][w][e]

[msg D10_09_NPC_07_sel_02_03__2 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4107 65535 0]He is quite the family man.[n][w][e]

[msg D10_09_NPC_07_reason_mes_2 [Noir]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You must care quite a bit for them.[n][w][e]

[msg D10_09_NPC_07_reason_mes_4 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Family's important n' all, but don'tcha[n]wanna, like, do something big with[n]your life?[n][w][e]

[msg D10_09_NPC_07_reason_mes_6 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, he cares for his family and doesn't[n]want much else out of life besides them...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It doesn't do anyone any harm, and[n]on top of that, there aren't any big[n]risks or dangers involved.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If those are all the relevant factors, then[n]this guy seems to be on the level—but[n]it all depends what Maruki would think.[n][w][e]

[msg ONE_RESEARCH_END_PC02_me [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Okay, let's go![n][w][e]

[msg ONE_RESEARCH_END_PC03_me [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]All right, Joker, let's keep asking around.[n][w][e]

[msg ONE_RESEARCH_END_PC04_me [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6018 65535 0]There sure are a lot of people here, huh?[n]You see any more we could ask about[n]their answer?[n][w][e]

[msg ONE_RESEARCH_END_PC05_me [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4104 65535 0]I think I'm beginning to grasp the[n]situation. Let's continue to interrogate[n]the other exam takers.[n][w][e]

[msg ONE_RESEARCH_END_PC06_me [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]Perhaps we'll get a better understanding[n]of the situation if we ask around.[n][w][e]

[msg ONE_RESEARCH_END_PC07_me [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3001 65535 0]I wonder, could anyone else here be[n]of any help? Let's try to keep up[n]the questioning![n][w][e]

[msg ONE_RESEARCH_END_PC08_me [Oracle]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9055 65535 0]Responses noted—on to the next[n]subject![n][w][e]

[msg ONE_RESEARCH_END_PC09_me [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8019 65535 0]We should continue questioning the[n]cognitive beings here. It'd be best to[n]hear multiple side of the situation.[n][w][e]

[msg ONE_RESEARCH_END_PC10_me [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The exam room's full of diverse[n]opinions. Let's try to learn more[n]of them![n][w][e]

[msg ALL_RESEARCH_END_mes_sta [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]Looks like we've mined all the info that[n]we can from this floor. Let's hash out[n]our own answer, Joker.[n][w][e]

[msg ALL_RESEARCH_END_mes_1st [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2127 65535 0]Now we know both sides of the story.[n][w][e]

[msg ALL_RESEARCH_END_mes_1st_2 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But neither one's exactly wrong, right?[n]I kinda get where they're both comin'[n]from.[n][w][e]

[msg ALL_RESEARCH_END_mes_1st_3 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What matters is which one Dr. Maruki[n]thinks is wrong.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why don't we collect our thoughts[n]somewhere and talk out our answer?[n][w][e]

[msg ALL_RESEARCH_END_mes_1st_4 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]How 'bout that empty room over there?[n][w][e]

[msg ALL_RESEARCH_END_mes_2nd [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57033 65535 0]I think we've heard all sides of the[n]situation—perhaps we should gather[n]somewhere to discuss it.[n][w][e]

[msg ALL_RESEARCH_END_mes_3rd [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It may not be much, but we do have[n]some information.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maybe we should discuss how we[n]think Dr. Maruki would react to[n]each answer.[n][w][e]

[msg ALL_RESEARCH_END_mes_3rd_2 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Looks like we got some information—[n]though it might've been better if it[n]were more concrete.[n][w][e]

[msg ALL_RESEARCH_END_mes_3rd_3 [Violet]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It seems like everyone's been struck[n]with indecision, facing this many[n]options...[n][w][e]

[msg ALL_RESEARCH_END_mes_3rd_4 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, thank you... If that's the case, then[n]we'll just have to think of our answer[n]with the information we have.[n][w][e]

[msg D10_09_3rd_hint_hiddenro [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6166 65535 0]Hmm... We got some information,[n]but not a lot compared to the last[n]one.[n][w][e]

[msg D10_09_3rd_hint_hiddenro_2 [Violet]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There are quite a few answers, so[n]we can only figure out so much...[n][w][e]

[msg D10_09_3rd_hint_hiddenro_3 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4150 65535 0]Actually, wasn't there some sort of[n]surveillance room?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do you think we could find a way into it?[n][w][e]

[msg D10_09_3rd_hint_hiddenro_4 [Skull]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7048 65535 0]Ooh, good idea! Maybe we can see[n]the right answer![n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Either that, or we just pick an elevator.[n]It's your call, Joker.[n][w][e]

[msg D10_09_3rd_hint_hiddenro_5 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]We won't know the answer no matter[n]how long we talk about it. Ain't there[n]a way to see where these elevators go?[n][w][e]

[msg D10_09_3rd_hint_hiddenro_6 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No way. Like this place would just[n]let us cheat the system like that.[n][w][e]

[msg D10_09_3rd_hint_hiddenro_7 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Hang on—if they're calling it an exam[n]room, there might be some room where[n]actual examination takes place.[n][w][e]

[msg D10_09_3rd_hint_hiddenro_8 [Skull]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, shit! For real!?[n][w][e]

[msg D10_09_3rd_hint_hiddenro_9 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9199 65535 0]That's true... based on this room's layout,[n]there might be a path to somewhere[n]else. Could be worth checking out![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But, it could be dangerous, too. Choosing[n]an answer without poking around any[n]further isn't a terrible idea, either.[n][w][e]

[msg D10_09_3rd_hint_hiddenro_10 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]It's your pick, Joker—if we gotta fight,[n]I'll mess 'em up for you![n][w][e]