[msg D03_01_e246_110_re_mes02 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're not gonna get anything outta this[n]one. How 'bout we try someone else?[n][w][e]

[msg D03_01_e246_111_re_mes02 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...It doesn't look like this one's going to[n]say anything.[n][w][e]

[msg D03_01_e246_111_re_mes03 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Come on, Joker! Let's try talking to[n]some more people![n][w][e]

