[msg QUEST_71_BATTLE_PRE_mes0 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]It's the complainer![n][w][e]

[msg QUEST_71_BATTLE_PRE_mes0_3 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]You! You've been filing all those complaints[n]to that store, right? Knock it off, asshole![n][w][e]

[msg QUEST_71_BATTLE_PRE_mes0_5 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]You seriously think you're blameless?[n][w][e]

[msg SEL_Q71_SEL_A_0_mes01 [Skull]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]It sucks getting dumped.[n][w][e]

[msg SEL_Q71_SEL_A_1_mes01 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Yeah, there's someone else who[n]deserves an apology from you.[n][w][e]

[msg QUEST_71_BATTLE_AFTER_me_3 [Skull]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]They'll forgive you if your apology is[n]sincere. The employee there is super nice![n][w][e]

