[msg QUEST_53_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1164 65535 0]So that Shadow is Fukurai, the Chairman.[n][w][e]

[msg QUEST_53_ENTER_mes01f [[Oracle]]]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]There it is. Chairman Fukurai's Shadow.[n][w][e]

[msg QUEST_53_ENTER_mes02 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He looks super shady.[n][w][e]

[msg QUEST_53_ENTER_mes03 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Well, he's selling useless rocks and[n]those brainwashing seminars to his[n]followers, right?[n][w][e]

[msg QUEST_53_ENTER_mes04 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]If we let him go on like this, so many[n]more people will end up unhappy![n][w][e]

[msg QUEST_53_ENTER_mes05 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2165 65535 0]Let's go and strip this wolf of his sheep's[n]clothing.[n][w][e]

