[msg D02_153_09_ex_pre_mes01 [Skull]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7029 65535 0]What the— They got Shadows here too!?[n][w][e]

[msg D02_153_09_ex_pre_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I can feel a Seed past this door... It might[n]be a pain to get our hands on it, though.[n][w][e]

[msg D02_153_09_ex_chk_mes01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]That one's gonna be tough. You guys[n]ready?[n][w][e]

[msg D02_153_09_ex_chk_selA_1 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right. Just make sure you're fully[n]prepared before you confront it.[n][w][e]

[msg D02_153_09_ex_btl_mes02 [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmph, this room will only be your end.[n]We'll be passing through![n][w][e]

