[msg QUEST_29_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]...So that's Kiritani's Shadow, eh?[n][w][e]

[msg QUEST_29_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Whoa, there it is. Kiritani's Shadow. [n][w][e]

[msg QUEST_29_ENTER_mes02 [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I get chills just looking at him. [n][w][e]

[msg QUEST_29_ENTER_mes03 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]He's an ex-mercenary who is now[n]a professional assassin. He's no[n]ordinary person.[n][w][e]

[msg QUEST_29_ENTER_mes04 [Noir]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][f 4 10 65535 0 0][vp 8 2 1 3200 65535 0]If even the police can't handle him,[n]then it's up to us to take care of him.[n][w][e]

[msg QUEST_29_ENTER_mes05 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Let's approach him with caution.[n][w][e]

[msg MSG_163_0_0 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]We can't just let someone dangerous[n]like you go around, killin' people.[n][w][e]

[msg MSG_165_0_0 [Panther]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][f 4 10 65535 0 0][vp 8 2 1 6187 65535 0]Evil? Don't be ridiculous! We're doing[n]our best to do what's right![n][w][e]

[msg QUEST_29_BOSS_EV_mes04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]He's coming![n][w][e]

[msg MSG_170_0_0 [Mona]]
[s][bup 0 3 0 0 0][vp 1 0 0 0 0 0]本気か? だがオマエがそういうなら、[n]仕方ないか。[n][w][e]

[msg MSG_171_0_0 [Mona]]
[s][bup 0 3 0 0 0][vp 1 0 0 0 0 0]Sorry, but we're not the same.[n]The Phantom Thieves would never[n]murder people.[n][w][e]

[msg MSG_173_0_0 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]I don't agree completely, but perhaps[n]he's a necessary evil. [n][w][e]

[msg MSG_175_0_0 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]If you ever target an innocent person,[n]we're takin' you down. You better[n]remember that.[n][w][e]

[msg MSG_177_0_0 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][f 4 10 65535 0 0][vp 8 2 1 6191 65535 0]How can you say that after you murdered[n]so many people!?[n][w][e]

[msg MSG_178_0_0 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]You better accept that you lost already.[n]Prepare yourself.[n][w][e]

[msg MSG_180_0_0 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]We'll destroy evil in a way that's different[n]from yours. You can disappear without[n]worry.[n][w][e]

