[msg QUEST_08_ENTER_mes01 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Hey, something's there![n][w][e]

[msg QUEST_08_ENTER_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That seems to be Nakanohara's Shadow.[n][w][e]

[msg QUEST_08_ENTER_mes03 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lemme see. Some front desk guy at City[n]Hall became a stalker, right?[n][w][e]

[msg QUEST_08_ENTER_mes04 [Panther]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I don't know how much evil he's done,[n]but we have to do something if he's[n]bothering other people.[n][w][e]

[msg QUEST_08_ENTER_mes05 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, we'll go talk to him.[n][w][e]

[msg MEME_QUEST_08_e185_002_m_2 [Panther]]
[s][bup 0 4 0 65535 0]Are you that stalker!? Haven't you ever[n]stopped to consider how your ex feels?[n][w][e]

[msg MEME_QUEST_08_e185_002_m_4 [Skull]]
[s][bup 0 2 0 65535 0]You can't treat someone like shit[n]just 'cause they did it to you! What[n]a load of crap![n][w][e]
[s]We're gonna change the hearts of all the[n]bastards like you![n][w][e]

[msg MEME_QUEST_08_e185_002_m_6 [Skull]]
[s][bup 0 2 0 65535 0]...Madarame? The hell's this guy goin' on[n]about?[n][w][e]

[msg MEME_QUEST_08_e185_002_m_7 [Mona]]
[s][bup 0 3 0 65535 0]Get ready! Here he comes![n][w][e]

[msg MEME_QUEST_08_e185_002_s_4 [Mona]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg MSG_002_0_0 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Hold on, are you talkin' about that guy[n]you mentioned earlier? Madarame?[n][w][e]

[msg MSG_003_0_0 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]You don't have to be so hard on him[n]anymore. He seems like he's sorry.[n][w][e]
[s][vp 1 0 0 0 0 0]So, this person you trusted... Is this the[n]Madarame that you were talking about[n]before?[n][w][e]

[msg MSG_005_0_0 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Treated like a thing...? What a horrible[n]experience.[n][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Next time, love your partner not as a thing,[n]but as a human being, okay?[n][w][e]

[msg MSG_007_0_0 [Mona]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Hmm!? This light... Is it the Treasure!?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Let's take it, Joker![n][w][e]

