[msg QUEST_72_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1176 65535 0]There! That's Ryoko Aino. Let's change her[n]heart for the sake of all the cats in Yongen![n][w][e]

[msg QUEST_72_BATTLE_PRE_mes0 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7018 65535 0]Ryoko Aino? You're gonna[n]let all the cats in Yongen go.[n][w][e]

[msg QUEST_72_BATTLE_PRE_mes0_3 [Mona]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]"Other kitties"...?[n][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Hey, what are you talking about?[n][w][e]

[msg QUEST_72_BATTLE_AFTER_me_2 [Mona]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]It's brought you a lot of suffering, huh...[n][w][e]

[msg QUEST_72_BATTLE_AFTER_me_4 [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]It's all right. You realized your mistake...[n]Just don't do something like this again.[n][w][e]

[msg QUEST_72_BATTLE_AFTER_me_6 [Mona]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1036 65535 0]I am NOT a cat![n][w][e]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But... that sounds nice.[n][w][e]