[msg QUEST_59_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]There they are, the Shadows of that[n]Kana girl's parents.[n][w][e]

[msg QUEST_59_ENTER_mes01f [Oracle]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]There. It's the Shadows of Kana-chan's[n]parents.[n][w][e]

[msg QUEST_59_ENTER_mes02 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Why are there so many parents who[n]try to control their children?[n][w][e]

[msg QUEST_59_ENTER_mes03 [Skull]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Don't overthink it. Let's worry more[n]about helpin' their daughter.[n][w][e]

[msg QUEST_59_ENTER_mes04 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]We have to change their hearts if we[n]want to save Futaba's friend![n][w][e]

[msg QUEST_59_ENTER_mes05 [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9108 65535 0]L-Let's go![n][w][e]

[msg MSG_002_0_0 [Oracle]]
[s][bup 0 8 0 65535 0][vp 1 0 0 0 0 0]You call yourselves parents!?[n][w][e]
[s][vp 1 0 0 0 0 0]Kana-chan's suffering so much because[n]of you![n][w][e]

[msg MSG_008_0_0 [Oracle]]
[s][bup 0 8 0 65535 0][vp 1 0 0 0 0 0]...I knew it. These two are rotten to the core![n][w][e]
[s][vp 1 0 0 0 0 0]Joker, please save Kana-chan![n][w][e]

[msg MSG_014_0_0 [Oracle]]
[s][bup 0 8 0 65535 0][vp 1 0 0 0 0 0]You HAVE to! Don't hurt Kana-chan[n]ever again![n][w][e]

[msg MSG_017_0_0 [Oracle]]
[s][bup 0 8 0 65535 0][vp 1 0 0 0 0 0]Thank you, Joker. I think Kana-chan's[n]going to be all right now.[n][w][e]
