[msg MSG_e296_125_000 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7192 65535 0]Another one...? Hey, how far do you think[n]we've gone?[n][w][e]

[msg MSG_e296_125_001 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If there are more traps waiting ahead,[n]I'd say we're probably not even halfway[n]done...[n][w][e]

[msg MSG_e296_230_000 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]This is the same kind of wall as the one[n]that displayed the mural last time...[n][w][e]

[msg MSG_e296_230_001 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why don't we try activating it, Joker?[n][w][e]

[msg MSG_e296_230_AF02_000 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This one is more complicated than our[n]previous puzzle... Let us try assembling[n]this picture, Joker.[n][w][e]

[msg MSG_e296_235_000 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]All right, it opened! That was a breeze![n][w][e]

[msg MSG_e296_235_001 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're pretty far in now, right? This has to[n]be past halfway.[n][w][e]

[msg MSG_e296_235_002 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, the Treasure is definitely close.[n]You better be excited![n][w][e]

