[msg QUEST_54_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]There it is. That's the Shadow of Tsuda.[n][w][e]

[msg QUEST_54_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Whoa, it's Tsuda's Shadow.[n][w][e]

[msg QUEST_54_ENTER_mes02 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7018 65535 0]Somethin' about this guy tells me he's[n]nuts. I guess I shouldn't be surprised.[n][w][e]

[msg QUEST_54_ENTER_mes03 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He's threatening Iwai... He's doing this[n]because he's getting desperate, right?[n][w][e]

[msg QUEST_54_ENTER_mes04 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He seriously intends to kill someone. We'd[n]better change his heart immediately.[n][w][e]

[msg QUEST_54_ENTER_mes05 [Panther]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6027 65535 0]It's scary, but we gotta do it![n][w][e]