[msg MSG_e296_322_000 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Hey, there's some kinda button here.[n]You wanna push it?[n][w][e]

[msg MSG_e296_322_002 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2157 65535 0]So there was a passage hidden behind[n]the wall... I wonder if there's a way back[n]there.[n][w][e]

[msg MSG_e296_322_003 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]All right, let's at least try to commit this[n]location to memory for the time being.[n][w][e]

