[msg mini_EV_e210_146_mes01 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]H-Hey, there's a strong-lookin' one over[n]there! We've seen that kind before...[n][w][e]

[msg mini_EV_e210_146_mes02 [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]His stance conveys the notion that he is[n]no ordinary foe.[n][w][e]

[msg mini_EV_e210_146_mes03 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]I think the control room's behind him.[n]He's probably guarding it to make sure[n]nobody gets too close.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]However, we'll need to disarm the[n]security if we want to ensure we have[n]a safe infiltration route.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Forcing our way through seems to be[n]our only option...[n][w][e]

[msg mini_EV_e210_146_mes04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Hey, are you ready to do this?[n][w][e]

[msg mini_EV_e210_146_mes06 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Phew, that guy was tough... I guess that's[n]just par for the course in a Palace...[n][w][e]

[msg mini_EV_e210_146_mes07 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]It really was on a totally different level[n]from the other enemies though...[n][w][e]

[msg mini_EV_e210_146_mes08 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Hm, he dropped some sort of card.[n][w][e]

[msg mini_EV_e210_146_mes09 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]What's this for? I've never seen anything[n]like it...[n][w][e]

[msg mini_EV_e210_146_mes10 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Ain't it just some kinda loot? C'mon,[n]let's get back to explorin'.[n][w][e]

