[msg MSG_QST_079_01 [Oracle]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9114 65535 0]There he is! That's Ushiwata! Let's get him![n][w][e]

[msg MSG_QST_079_04 [Mona]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1176 65535 0]We are "too"...?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What do you mean by that?[n][w][e]

[msg MSG_QST_079_05 [Crow]]
[s][bup 0 9 812 0 0]......[n][w][e]

[msg MSG_QST_079_06 [Noir]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Crow...?[n][w][e]

[msg MSG_QST_079_09 [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Not just immature. You framed your own[n]child...[n][w][e]

[msg MSG_QST_079_10 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let Toji go now. Turning your own son into a[n]criminal is sick...[n][w][e]

[msg MSG_QST_079_12 [Queen]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......?[n][w][e]

[msg MSG_QST_079_14 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Is this... a key?[n][w][e]

[msg MSG_QST_079_17 [Crow]]
[s][bup 0 9 811 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54489 65535 0]Something came to mind, that's all.[n]I don't intend to do anything bad with it.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]To make up for it, please take this.[n][w][e]

[msg MSG_QST_079_18 [Crow]]
[s][bup 0 9 811 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You can have it as thanks for accepting[n]my request.[n][w][e]

[msg MSG_QST_079_19 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right! Now they'll release Toji, right?[n][w][e]

[msg MSG_QST_079_20 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I don't sense a presence anymore, so the[n]change of heart should have worked.[n][w][e]

[msg MSG_QST_079_21 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...I'll let you all know what becomes[n]of Karataki. No matter what happens.[n][w][e]

