[msg D04_03_e296_359_mes01 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This door is the one to Futaba's room...[n][w][e]

[msg MSG_e296_359_AF_000 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1021 65535 0]If we want to get past here, we'll have to[n]get into Futaba's room in the real world...[n][w][e]

[msg MSG_e296_359_AF_001 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]She referred to it as the "Pharaoh's[n]Chamber"...[n][w][e]

[msg MSG_e296_359_AF_002 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C'mon, we gotta hurry to Futaba's room.[n]We'll bring her a calling card, too![n][w][e]

[msg MSG_e296_359_AF_003 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Right. For now, let's retreat from the[n]Palace. Joker can decide when we[n]actually go to her room.[n][w][e]

[msg MSG_e296_359_AF02_000 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If we want to get past here, we'll have to[n]get into Futaba's room in the real world...[n][w][e]

[msg MSG_e296_359_AF02_001 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]In any case, let's retreat for the time[n]being. You can choose when we carry[n]this out, Joker.[n][w][e]

[msg D04_ex_e297_025_mes01 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]I hope she read the calling card.[n][w][e]

[msg D04_ex_e297_025_mes02 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I mean after all the trouble we went[n]through, she damn well better've[n]read it![n][w][e]

[msg D04_ex_e297_025_mes03 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]All right! It's open![n][w][e]

[msg D04_ex_e297_025_mes04 [Panther]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well yeah, Futaba-chan opened the door[n]herself.[n][w][e]

[msg D04_ex_e297_025_mes05 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1045 65535 0]Anyway, the Treasure is up ahead![n]Let's finish this![n][w][e]

