[msg QUEST_56_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Those Shadows must be the guardians[n]of the student named Takase.[n][w][e]

[msg QUEST_56_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]There it is. The Shadows of the guardians[n]of the student named Takase.[n][w][e]

[msg QUEST_56_ENTER_mes02 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Those two look pretty sure of themselves.[n]Real smug lookin'.[n][w][e]

[msg QUEST_56_ENTER_mes03 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]So they're blackmailing that teacher,[n]Kawakami, by using that incident[n]where their child died.[n][w][e]

[msg QUEST_56_ENTER_mes04 [Panther]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]But Ms. Kawakami did nothing wrong,[n]right? We have to help her![n][w][e]

[msg QUEST_56_ENTER_mes05 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]Are you ready? Let's go.[n][w][e]

