[msg mini_EV_e210_145_mes02 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Pffft! He's really puffin' his chest out[n]here, ain't he...?[n][w][e]

[msg mini_EV_e210_145_mes03 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hold on a moment... Could this be[n]the spot of "Madarame's feet" that[n]the security guard mentioned?[n][w][e]

[msg mini_EV_e210_145_mes04 [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's at his feet... Oh, right! But isn't the[n]password supposed to be a number of[n]some kind?[n][w][e]

[msg mini_EV_e210_145_mes05 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, I do believe there are numbers[n]here though...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"One" ray of hope stands "alone" with[n]"two adept hands." "None" shall match[n]him... That means...[n][w][e]

[msg mini_EV_e210_145_selA_0_ [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1156 65535 0]Try putting the numbers in order.[n]The password has to be 1120![n][w][e]

[msg mini_EV_e210_145_selA_1_ [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1166 65535 0]Yeah, that must be it![n][w][e]

[msg mini_EV_e210_145_selA_2_ [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1155 65535 0]Just put the numbers in order. You get[n]1120 out of it, right?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That has to be the password![n][w][e]

[msg mini_EV_e210_145_mes06 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sweet! Let's head back and shut down[n]the security![n][w][e]

[msg mini_EV_MONUMENT_mes01 [Fox]]
[s][bup 0 5 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4047 65535 0]Ngh... I never would have imagined such[n]a sight in a museum. It's nothing short[n]of an abomination.[n][w][e]

[msg mini_EV_MONUMENT_mes02 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I guess Palace rulers like makin' statues[n]of themselves.[n][w][e]

[msg mini_EV_MONUMENT_mes03 [Panther]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It was the same with Kamoshida. I guess[n]this one's a little better-made though.[n][w][e]

[msg mini_EV_MONUMENT_mes04 [Fox]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4188 65535 0]I-Is that so...?[n][w][e]

