[msg QUEST_50_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]So that's Wakasa's Shadow.[n][w][e]

[msg QUEST_50_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah, we found Wakasa's Shadow.[n][w][e]

[msg QUEST_50_ENTER_mes02 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He's some kinda scam artist, right?[n][w][e]

[msg QUEST_50_ENTER_mes03 [Noir]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3127 65535 0]Yes, and he only targets lonely, elderly[n]people.[n][w][e]

[msg QUEST_50_ENTER_mes04 [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]How could he do something so terrible?[n][w][e]

[msg QUEST_50_ENTER_mes05 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4020 65535 0]Now this is a man who requires a change[n]of heart.[n][w][e]

[msg MSG_014_0_0 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1046 65535 0]Don't lump us in the same category[n]with scam artists like you![n][w][e]

[msg MSG_015_0_0 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Tricking nice old people into givin' you[n]their money... Just how big of a jerk are[n]you?[n][w][e]

[msg MSG_017_0_0 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Would you say something like that about[n]your own parents!?[n][w][e]

[msg QUEST_50_BOSS_EV_mes04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Let's go![n][w][e]

[msg MSG_025_0_0 [Noir]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]It was really horrible of you to take[n]advantage of people's weakness like that.[n][w][e]

[msg MSG_026_0_0 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]What do you intend to do from now on?[n][w][e]

[msg MSG_028_0_0 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]If you knew how much pain you put[n]your victims through, you would have[n]never done this.[n][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Remember the shame you feel over[n]what you've done, and do your best[n]to make up for it.[n][w][e]

[msg QUEST_50_BATTLE_END_mes0 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, got the Treasure![n][w][e]

[msg QUEST_50_BATTLE_END_mes0_3 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Don't ever do it again! Make up for all[n]the wrongs you've done![n][w][e]

