[msg QUEST_55_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]So that's the Shadow of that doctor,[n]Oyamada.[n][w][e]

[msg QUEST_55_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]That Oyamada doctor's Shadow has[n]been spotted.[n][w][e]

[msg QUEST_55_ENTER_mes02 [Skull]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7028 65535 0]That bastard looks like he's been eatin'[n]well lately.[n][w][e]

[msg QUEST_55_ENTER_mes03 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Hm. He made a mistake in rushing a[n]drug's development, and now intends[n]for his subordinate to take the fall.[n][w][e]

[msg QUEST_55_ENTER_mes04 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6101 65535 0]People might die if we don't change[n]his heart! And a good doctor will have[n]to quit...[n][w][e]

[msg QUEST_55_ENTER_mes05 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7198 65535 0]Yeah. We gotta do something![n][w][e]