[msg QUEST_48_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]It's Tsuboi's Shadow. No doubt about it.[n][w][e]

[msg QUEST_48_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Shadow spotted. It's Tsuboi's, right?[n][w][e]

[msg QUEST_48_ENTER_mes02 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2182 65535 0]He seems a little irritated.[n][w][e]

[msg QUEST_48_ENTER_mes03 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]I heard he was abusin' animals just to take[n]his anger out on them.[n][w][e]

[msg QUEST_48_ENTER_mes04 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]I can't let him get away with something like[n]that![n][w][e]

[msg QUEST_48_ENTER_mes05 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1156 65535 0]You guys, don't go easy on him![n][w][e]

[msg MSG_026_0_0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1046 65535 0]What a poor excuse for a human being![n]I could never forgive someone like you![n][w][e]

[msg MSG_028_0_0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]We'll take your twisted desires, but first I'll[n]show you the pain you caused those poor[n]animals![n][w][e]

[msg QUEST_48_BOSS_EV_mes04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Let's do it, Joker! I'll show you the wrath of[n]cats![n][w][e]

[msg MSG_033_0_0 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7187 65535 0]Those cats were actually gettin' killed 'cause[n]of you. Don't you get it now?[n][w][e]

[msg MSG_034_0_0 [Skull]]
[s][bup 0 2 2 65535 0][vp 8 2 1 7187 65535 0]Who cares? He's a scumbag.[n][w][e]

[msg MSG_035_0_0 [Fox]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4189 65535 0]That's a good idea. Perhaps then, he'll[n]understand what those animals had to[n]endure.[n][w][e]

[msg MSG_037_0_0 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Remember the awful things you did to those[n]cats. Doesn't it make you feel horrible?[n][w][e]

[msg MSG_039_0_0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]I won't tell you to give up your life. But you[n]will spend the rest of your life in guilt.[n][w][e]

[msg QUEST_48_BATTLE_END_mes0 [Skull]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Aww yeah, there it is! The Treasure![n][w][e]

[msg QUEST_48_BATTLE_END_mes0_3 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Never do that again! You better fully atone[n]for the crimes you committed![n][w][e]

