[msg D07_02_e410_010_mes01 [Panther]]
[s][vp 8 2 1 6159 65535 0]Ah, we turned into mice again!?[n][w][e]

[msg D07_02_e410_010_mes02 [Queen]]
[s]I guess that means there's a Shido statue[n]here too. How troublesome.[n][w][e]

[msg D07_02_e410_010_mes03 [Fox]]
[s][vp 8 2 1 4023 65535 0]Hm... My ad-mice would be[n]to pro-squeak cautiously.[n][w][e]

[msg D07_02_e410_010_mes04 [Oracle]]
[s]......[n][w][e]

[msg D07_02_e410_010_mes05 [Fox]]
[s]Oracle, my ad-mice would be—[n][w][e]

[msg D07_02_e410_010_mes06 [Noir]]
[s][vp 8 2 1 3178 65535 0]I believe she heard you the first time.[n]Anyway, can we focus on the task at hand?[n][w][e]

[msg D07_02_e410_015_mes01 [Fox]]
[s][vp 8 2 1 4132 65535 0]Oh! This aroma... Could it be!?[n][w][e]

[msg D07_02_e410_015_mes02 [Fox]]
[s][vp 8 2 1 4048 65535 0]It's cheese... The cheese is beckoning me![n][w][e]

[msg D07_02_e410_015_mes03 [Skull]]
[s]Oh damn... Cheese? I can't even[n]control myself...[n][w][e]

[msg D07_02_e410_015_mes04 [Mona]]
[s][vp 8 2 1 1029 65535 0]You idiots! How could you fall for[n]such an obvious traaa...[n][w][e]
[s]...aaaaaaah I can't stop myself![n]Save some for meeeee![n][w][e]

[msg D07_02_e410_015_mes05 [Panther]]
[s]What? Wait, guys![n][w][e]

[msg D07_02_e410_015_mes06 [Noir]]
[s][vp 8 2 1 3001 65535 0]Oh no! It's luring me in...[n][w][e]

[msg D07_02_e410_015_mes07 [Panther]]
[s]Wha— You too, Noir!?[n][w][e]
[s]Hey, Queen, aren't you gonna say[n]anything about—[n][w][e]

[msg D07_02_e410_015_mes08 [Queen]]
[s]Thanks for the food![n][w][e]

[msg D07_02_e410_015_mes09 [Panther]]
[s]QUEEN!?[n][w][e]
[s]......[n][w][e]
[s]Hey! Leave some for me too...![n][w][e]

[msg D07_02_e410_015_mes10 [Skull]]
[s]We're at max capacity here! Hey, don't[n]get your mouth all over it! We're sharing![n][w][e]

[msg D07_02_e410_015_mes11 [Fox]]
[s]Cheese... More cheese... Is there any[n]more cheese left!?[n][w][e]

[msg D07_02_e410_015_mes12 [Panther]]
[s][vp 8 2 1 6088 65535 0]We knew it was a trap but we walked[n]right in anyway... aaaaaand it doesn't[n]open from the inside.[n][w][e]

[msg D07_02_e410_015_mes13 [Oracle]]
[s]So, did the little meese enjoy their feast?[n][w][e]

[msg D07_02_e410_015_mes14 [Skull]]
[s][vp 8 2 1 7028 65535 0]Owww... Thanks, Oracle. I dunno[n]how much longer I could stay[n]cramped in there.[n][w][e]
[s]But jeez, who knew cheese could[n]hypnotize? I seriously had no control...[n][w][e]

[msg D07_02_e410_015_mes15 [Fox]]
[s]Indeed, nobody was able to stop[n]themselves... It was simply too[n]delectable.[n][w][e]
[s]I must say though, the sight of all seven[n]of us gorging ourselves, as mice, on a[n]single piece of cheese... What a spectacle.[n][w][e]

[msg D07_02_e410_015_mes16 [Queen]]
[s]But, was that cheese... even safe to eat?[n][w][e]

[msg D07_02_e410_015_mes17 [Mona]]
[s]I don't think we have to worry about[n]that, at least—I didn't sense any danger[n]from it.[n][w][e]

[msg D07_02_e410_015_mes18 [Noir]]
[s]I actually feel somewhat refreshed[n]having eaten that.[n][w][e]

[msg D07_02_e410_015_mes19 [Mona]]
[s][vp 8 2 1 1175 65535 0]Hmm... then I vote that we have ourselves[n]a nibble if we spot any more cheese![n][w][e]
[s]Now that we're fed, let's get moving![n][w][e]

