[msg QUEST_52_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]There it is. That should be the Shadow[n]of the man named Uchimura.[n][w][e]

[msg QUEST_52_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah, that must be Uchimura's Shadow.[n][w][e]

[msg QUEST_52_ENTER_mes02 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He's abusing his girlfriend, right?[n][w][e]

[msg QUEST_52_ENTER_mes03 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Didn't her fortune say she's gonna get[n]hurt bad? We can't leave him like this.[n][w][e]

[msg QUEST_52_ENTER_mes04 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]We need to change his heart, and fast![n][w][e]

[msg MSG_004_0_0 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 1170 65535 0]Phew... The right to beat his girlfriend?[n]He was really the worst of the worst[n]to think that.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]We changed his heart, so let's go tell the[n]fortune teller when we get the chance.[n][w][e]

