[msg EV_SP_ABILITY_OPEN_START [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Okay everyone, this is the first infiltration[n]Fox will be in on from the start—let's do[n]this right![n][w][e]

[msg EV_SP_ABILITY_OPEN_END_0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1018 65535 0]Hey! Joker![n][w][e]

[msg EV_SP_ABILITY_OPEN_END_0_2 [Mona]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1026 65535 0]What're you standin' around for?[n][w][e]

[msg EV_SP_ABILITY_OPEN_END_0_3 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Get with the program, all right? You're[n]a vital member of the team here![n][w][e]
