[msg D08_BRIEFING_060_mes01 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9043 65535 0]So there's a limit on the number of[n]moves... It looks like security's getting[n]tighter the deeper we go...[n][w][e]

[msg D08_BRIEFING_060_mes02 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That just goes to show how close we are.[n]Ain't that right, Mona?[n][w][e]

[msg D08_BRIEFING_060_mes03 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Exactly. I'd say we're probably around[n]seventy percent through by now.[n][w][e]

[msg D08_BRIEFING_060_mes04 [Noir]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]So that means we're not quite done with[n]the security systems yet.[n][w][e]

[msg D08_BRIEFING_060_mes05 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Don't worry 'bout that. Joker's been[n]helpin' us get this far, so it'll be a breeze[n]with him here![n][w][e]

[msg D08_BRIEFING_060_mes06 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You've just completely given up on[n]thinking for yourself, huh...[n][w][e]

