[msg D07_01_e407_201_A_mes05 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]Hey, these guys totally ignore me when[n]I try and talk to 'em...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do I look that much like I don't got any[n]money? Is it 'cause of the skull mask or[n]something?[n][w][e]

[msg D07_01_e407_201_B_mes05 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Beyond this door is the "VIP area," and[n]the main assembly hall is a "sacred place."[n][w][e]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It looks like we can't get in unless Shido[n]accepts us.[n][w][e]

[msg D07_01_e407_201_C_mes05 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]It appears these people all want to[n]be accepted as one of Shido's special[n]customers.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]By the way, I've gained some information[n]on the VIPs. We should discuss later.[n][w][e]

[msg D07_01_e407_201_D_mes05 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Hearing people speak so casually about[n]the mental shutdown business makes[n]my head spin...[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...But it seems as though we need[n]certification from five VIPs to become[n]a "special customer."[n][w][e]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]These people are willing to share[n]anything. Perhaps it's because their[n]faces are hidden?[n][w][e]

[msg D07_01_e407_201_E_mes03 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Um, I'm not entirely sure how to speak[n]to people here...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I either remained silent or spoke in[n]simple pleasantries during Father's[n]business relations...[n][w][e]

[msg D07_01_e407_201_F_mes01 [Oracle]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9027 65535 0]You're some kinda sadist for making me[n]get info from complete strangers, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But I'll do it! I'm going to avenge my mom.[n][w][e]

[msg D07_01_e407_201_A_AF_mes [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]Hey, these guys totally ignore me when[n]I try and talk to 'em...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do I look that much like I don't got any[n]money? Is it 'cause of the skull mask or[n]something?[n][w][e]

[msg D07_01_e407_201_B_AF_mes [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Beyond this door is the "VIP area," and[n]the main assembly hall is a "sacred place."[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It looks like we can't get in unless Shido[n]accepts us.[n][w][e]

[msg D07_01_e407_201_C_AF_mes [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]It appears these people all want to[n]be accepted as one of Shido's special[n]customers.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]By the way, I've gained some information[n]on the VIPs. We should discuss later.[n][w][e]

[msg D07_01_e407_201_D_AF_mes [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Hearing people speak so casually about[n]the mental shutdown business makes[n]my head spin...[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...But it seems as though we need[n]certification from five VIPs to become[n]a "special customer."[n][w][e]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]These people are willing to share[n]anything. Perhaps it's because their[n]faces are hidden?[n][w][e]

[msg D07_01_e407_201_E_AF_mes [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Um, I'm not entirely sure how to speak[n]to people here...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I either remained silent or spoke in[n]simple pleasantries during Father's[n]business relations...[n][w][e]

[msg D07_01_e407_201_F_AF_mes [Oracle]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9027 65535 0]You're some kinda sadist for making me[n]get info from complete strangers, Joker![n][w][e]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But I'll do it! I'm going to avenge my mom.[n][w][e]

