[msg MSG_e296_113_000 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Yo, this statue's got a gem. We should[n]take it, yeah?[n][w][e]

[msg MSG_e296_113_001 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6165 65535 0]Wait, there's an inscription here. It says,[n]"Any who attempts to steal this gem[n]shall be cursed..."[n][w][e]

[msg MSG_e296_113_002 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's here too... We saw the same thing at[n]the other Anubis statue.[n][w][e]

[msg MSG_e296_113_003 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]We can't let shit like that get to us, right?[n]C'mon, let's take it.[n][w][e]

[msg MSG_e296_113_004 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo, this statue's got a gem. We should[n]take it, yeah?[n][w][e]

[msg MSG_e296_113_005 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hold on, there's an inscription on this[n]stone slab here...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Any who attempts to steal this gem[n]shall be cursed..." Uhhh...[n][w][e]

[msg MSG_e296_113_006 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dude, we can't let this "curse" shit get to[n]us, right? C'mon, let's just take it.[n][w][e]

[msg D04_03_e296_113_selA_0_m [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Sweet, we got it. Let's go.[n][w][e]

[msg D04_03_e296_113_selA_1_m [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6027 65535 0]Yeah, we really shouldn't. I mean, uh...[n]not like I believe in curses or anything.[n][w][e]

[msg MSG_e296_113_AF01_000 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C'mon, you wanna take this thing?[n][w][e]

[msg MSG_e296_115_000 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, do you want to put back the gem[n]we took earlier?[n][w][e]

[msg MSG_e296_115_002 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, we can always come back and[n]get it if we need to later.[n][w][e]

[msg MSG_e296_115_003 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oooh, the atmosphere's kinda different[n]in here now.[n][w][e]

[msg MSG_e296_115_004 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Could the "curse" perhaps have been[n]lifted? We should check to see if[n]anything has changed.[n][w][e]

[msg MSG_e296_115_005 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, really? Well, I guess that works too.[n][w][e]

[msg MSG_e296_118_000 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, it's another Anubis statue. There[n]seems to be an inscription here as well.[n][w][e]

[msg MSG_e296_118_001 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's see... "Any who attempts to steal[n]this gem shall be cursed..." Wait, it says[n]the same thing!?[n][w][e]

[msg MSG_e296_118_002 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But this statue isn't actually holding[n]a gem... What could be the meaning[n]of this?[n][w][e]

[msg MSG_e296_118_003 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, it's an Anubis statue. There seems[n]to be an inscription here...[n][w][e]

[msg MSG_e296_118_004 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Any who attempts to steal this gem[n]shall be cursed..." Uhhh...[n][w][e]

[msg MSG_e296_118_005 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dude, we can't go around bein' afraid of[n]this "curse" shit. Let's just take it, yeah?[n][w][e]

[msg MSG_e296_118_006 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But this statue isn't actually holding[n]a gem... What could be the meaning[n]of this?[n][w][e]

[msg MSG_e296_118_007 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hold up, we got one with us. Wanna try[n]puttin' it in there?[n][w][e]

[msg MSG_e296_118_009 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, the atmosphere has changed in[n]some intangible way... Perhaps the[n]"curse" has been lifted?[n][w][e]

[msg MSG_e296_118_00A [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That thing wasn't even holdin' a gem[n]to start with! It ain't fair makin' us put[n]one in![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It don't matter if this is some dog god[n]or whatever... It just ain't fair![n][w][e]

[msg MSG_e296_118_00B [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Somebody prolly came in here before[n]us and took it.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Either way, we're just gonna have to[n]find one we can pop in there.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maybe there's one somewhere around[n]here, yeah? Let's look.[n][w][e]

[msg MSG_e296_118_00C [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I guess that's probably safer. The gem[n]we have didn't come from this statue[n]to begin with.[n][w][e]

[msg MSG_e296_118_AF01_000 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's this "curse" shit it's talkin' about?[n]Anyways, wanna try puttin' the gem we got[n]on there?[n][w][e]

[msg MSG_e296_118_AF01_002 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, the atmosphere has changed[n]in some intangible way... Perhaps[n]the "curse" has been lifted?[n][w][e]

[msg MSG_e296_118_AF01_003 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That thing wasn't even holdin' a gem[n]to start with! It ain't fair makin' us[n]put one in![n][w][e]

[msg MSG_e296_118_AF01_004 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This "curse" shit's a load of bull. It ain't[n]even holdin' a gem to begin with.[n][w][e]

[msg MSG_e296_118_AF02_000 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It seems the gem we left in the Anubis[n]statue is still there. Shall we take it[n]with us?[n][w][e]

[msg MSG_e296_118_AF02_003 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I don't know if I quite like the sound of[n]that... Do you think we will be all right?[n][w][e]

[msg MSG_e296_118_AF02_004 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, not our problem. I mean, we're the[n]ones who brought the gem here in the[n]first place![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's get outta here, Joker.[n][w][e]

[msg MSG_e296_118_AF02_005 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, if you say so. Let's go![n][w][e]

[msg D155_07_c_02_mes02 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We have a gem on us. Should we try[n]placing it in here?[n][w][e]

[msg MSG_e296_118_00C_AF [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Very well. Let's continue onward[n]for now.[n][w][e]

[msg D155_07_GIMMICK_NG_01_me [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, we have a gem from somewhere[n]else... but I don't think we're supposed[n]to use it here.[n][w][e]

[msg D155_07_GIMMICK_NG_01_me_2 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You're right. Let's look around for a[n]better place to use it.[n][w][e]

[msg D155_07_GIMMICK_NG_02_me [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, we have a gem from somewhere[n]else... but I don't think we're supposed[n]to use it here.[n][w][e]

[msg D155_07_GIMMICK_NG_02_me_2 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You're right. Let's look around for a[n]better place to use it.[n][w][e]

