[msg MSG_QUEST_78_01 [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9100 65535 0]All right, there's Anji Fuwa! Let's[n]change his heart, for his family's sake.[n][w][e]

[msg MSG_QUEST_78_03 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7114 65535 0]Come on, man. You know that's not right,[n]don't you!?[n][w][e]

[msg MSG_QUEST_78_05 [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9194 65535 0]He's in no condition to listen. Watch out,[n]Joker![n][w][e]

[msg MSG_QUEST_78_07 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7173 65535 0]But now you know what you've gotta do,[n]right?[n][w][e]

[msg MSG_QUEST_78_12 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7114 65535 0]So you're not gonna stop chasing her...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, guess it's not a bad thing to have a[n]hobby.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Become a dad your kid can be proud of.[n][w][e]