[msg MSG_QST_073_01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]There! That's Saeki Kaya![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]She apparently used to be close with[n]Shiho, but now she hates her so much[n]that she destroys her belongings![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Let's change her heart before any[n]harm comes to Shiho herself.[n][w][e]

[msg MSG_QST_073_04 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]I know how hard it can be when stuff falls[n]apart in your club. But your volleyball[n]team's still around, ain't it?[n][w][e]

[msg MSG_QST_073_06 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7187 65535 0]Just listen! Your love of volleyball's obvious.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]I know you've got just as much passion[n]for it as Kamoshida and Suzui do.[n][w][e]

[msg MSG_QST_073_08 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6156 65535 0]Your volleyball team went through[n]a lot... but it still exists.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So why not play again?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]If anyone can make the team[n]thrive again, I'm sure it's you.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]It's something only you can do.[n]That's what Shiho would want too...[n][w][e]

[msg MSG_QST_073_10 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6034 65535 0]It's all right. I'm sure Shiho will forgive you.[n]In fact, I guarantee it as her best friend![n][w][e]