[msg MSG_e296_114_000 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Whoa, that was TOO close![n][w][e]

[msg MSG_e296_114_001 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It doesn't look like we can go through[n]here either... Maybe it's that "curse"?[n][w][e]

[msg MSG_e296_114_002 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ughhh, this is so annoyin'! God freakin'[n]dammit![n][w][e]

[msg MSG_e296_114_003 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're not getting past here with[n]those arrows. Maybe the "curse"[n]is real after all...[n][w][e]

[msg MSG_e296_114_004 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ughhh, what the hell're we supposed[n]to do!? Goddammit![n][w][e]

[msg MSG_e296_114_AF_000 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That way's too dangerous. Maybe that[n]"curse" has to do with it?[n][w][e]

[msg MSG_e296_117_000 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]Hm... We've seen this trap before. It had[n]something to do with that "curse"...[n][w][e]

[msg MSG_e296_117_001 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Does that mean this one's related to[n]that gem too?[n][w][e]

[msg MSG_e296_117_FA01_000 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ngh, we cannot proceed like this...[n][w][e]

[msg MSG_e296_117_FA01_001 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm sure there's some way to prevent[n]this from triggering—let's look around.[n][w][e]

[msg MSG_e296_117_FA02_000 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The route is impassable as is. We must[n]find a way to stop the arrows, Joker.[n][w][e]

