[msg D04_03_e296_335_mes01 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Look, there's another Anubis statue![n]And it has one of those shining things,[n]just like before![n][w][e]

[msg D04_03_e296_335_mes02 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I bet we're gonna have to use it[n]somewhere. Let's take it, Joker![n][w][e]

[msg D04_03_e296_335_mes02_AF [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can probably use it on that pedestal[n]thing. Let's swipe it, Joker![n][w][e]

[msg D04_03_e296_335_selA_0_m [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Okay, we've got it now. Let's go.[n][w][e]

[msg D04_03_e296_335_selA_1_m [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Really? I'm thinkin' you're a little too[n]careful, dude.[n][w][e]

[msg D04_03_e296_335_AF01_mes [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Do you want to take this gem with you[n]after all, Joker?[n][w][e]

[msg MSG_e296_335_AF02_000 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What is the matter? Do you wish to[n]return the gem to this statue?[n][w][e]

[msg MSG_e296_335_AF02_002 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, it's back to how it was before.[n]Let's get out of here![n][w][e]

[msg MSG_e296_335_AF02_003 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm, we can probably just keep what[n]we take. After all, we're the Phantom[n]Thieves![n][w][e]

