[msg QUEST_51_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]That Shadow must be Shinya's mother.[n][w][e]

[msg QUEST_51_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Shadow spotted! Is she that gamer[n]Shinya's mom?[n][w][e]

[msg QUEST_51_ENTER_mes02 [Queen]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]She looks like she would bite us if we[n]even tried to speak to her.[n][w][e]

[msg QUEST_51_ENTER_mes03 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]I heard she's the definition of a helicopter[n]parent. She's really selfish too.[n][w][e]

[msg QUEST_51_ENTER_mes04 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]We gotta do somethin' about this! Kids[n]really look up to their parents, you know?[n][w][e]

[msg QUEST_51_ENTER_mes05 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1023 65535 0]Let's go, guys![n][w][e]