[msg QUEST_36_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]That's Kishi's Shadow, right?[n][w][e]

[msg QUEST_36_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah, it's Kishi's Shadow.[n][w][e]

[msg QUEST_36_ENTER_mes02 [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]God, he looks pigheaded...[n][w][e]

[msg QUEST_36_ENTER_mes03 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]This guy abused his position at work,[n]right? Harassin' the people under him[n]and all that.[n][w][e]

[msg QUEST_36_ENTER_mes04 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]It's people like him who create awful[n]workplace environments...[n][w][e]

[msg QUEST_36_ENTER_mes05 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4099 65535 0]Let's talk to him.[n][w][e]

[msg MSG_029_0_0 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Stealing credit from your subordinates[n]is one of the worst things you can do as[n]a superior.[n][w][e]

[msg MSG_031_0_0 [Panther]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]How did someone like you ever get[n]promoted? If I were the president,[n]you'd be fired![n][w][e]

[msg QUEST_36_BOSS_EV_mes04 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Let's go![n][w][e]

[msg MSG_040_0_0 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]How do you intend to take responsibility[n]for all this?[n][w][e]

[msg MSG_042_0_0 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]I want you to think carefully about[n]what kind of boss you'd like to work[n]for. Figure it out.[n][w][e]

[msg QUEST_36_BATTLE_END_mes0 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]An amusement park guidebook!?[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Even if you abused your subordinates,[n]I guess your kids were real important[n]to you...[n][w][e]

[msg QUEST_36_BATTLE_END_mes0_3 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Don't do this again! You better make[n]amends for the wrong you've done![n][w][e]

