[msg D04_03_e296_231_mes03 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Oh hey, it came on. This one's kinda[n]hard to tell though.[n][w][e]

[msg D04_03_e296_231_mes04 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]It must be scrambled as well. Let's use[n]the controls to put it back together.[n][w][e]

[msg GMC_PUZZLE_EXIT_CHECK_ms [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 14 0 0]What's wrong, Joker? Do you need to[n]think this over?[n][w][e]

[msg GMC_PUZZLE_INIT_msg_03 [Queen]]
[s]Ü度頭を冷やして挑戦してみましょう。[n][w][e]

[msg D04_03_e296_201_mes01 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]It seems the picture is complete.[n][w][e]

[msg GMC_PUZZLE_INIT_msg_02 [Queen]]
[s]何と言うか、奇妙な壁画ね。[n][w][e]
