[msg D04_155_06_ex_chk_mes01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, Joker, I'm getting a certain feeling[n]from that door...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1027 65535 0]We're in for a tough battle—are you[n]ready?[n][w][e]

[msg D04_155_06_ex_chk_selA_1 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right. Just make sure you're fully[n]prepared before you enter.[n][w][e]

[msg D04_155_06_ex_btl_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Here it comes! Get ready, guys![n][w][e]

