[msg QUEST_33_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]There he is, Asakura's Shadow.[n][w][e]

[msg QUEST_33_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah, it's Asakura's Shadow.[n][w][e]

[msg QUEST_33_ENTER_mes02 [Noir]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He's acting like he owns the place.[n][w][e]

[msg QUEST_33_ENTER_mes03 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He's a producer in the world of[n]entertainment, destroying the dreams[n]of young girls, right?[n][w][e]

[msg QUEST_33_ENTER_mes04 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6101 65535 0]I can't let this go! I'm going, even if you[n]try to stop me![n][w][e]

[msg QUEST_33_ENTER_mes05 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7107 65535 0]No one's gonna stop you, so calm down![n]Let's go![n][w][e]

[msg MSG_040_0_0 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6187 65535 0]Yeah, right! Just what are you doing to[n]these girls!?[n][w][e]

[msg MSG_042_0_0 [Queen]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Don't be stupid. We're the ones[n]who'll be managing you.[n][w][e]

[msg QUEST_33_BOSS_EV_mes04 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Here we go![n][w][e]

[msg MSG_050_0_0 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]You've done whatever you wanted and[n]caused a lot of damage. What do you[n]plan to do about it now?[n][w][e]

[msg MSG_052_0_0 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6194 65535 0]Sincerity? How!?[n][w][e]

[msg MSG_054_0_0 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6137 65535 0]If I ever hear another bad rumor about[n]you, you better be ready for us. Okay!?[n][w][e]

[msg QUEST_33_BATTLE_END_mes0 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Right on, we got the Treasure![n][w][e]

[msg QUEST_33_BATTLE_END_mes0_3 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Don't do it again! You better fully atone[n]for what you've done![n][w][e]

