[msg QUEST_57_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]So that Shadow's the boss of that[n]journalist, Ohya.[n][w][e]

[msg QUEST_57_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah, it's the Shadow of that Ohya[n]journalist's boss.[n][w][e]

[msg QUEST_57_ENTER_mes02 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]He looks so suspicious.[n][w][e]

[msg QUEST_57_ENTER_mes03 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Well, he is obstructing a news[n]investigation to keep some incident[n]hidden under the rug.[n][w][e]

[msg QUEST_57_ENTER_mes04 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]People died in that incident. He should[n]be ashamed to call himself a journalist.[n][w][e]

[msg QUEST_57_ENTER_mes05 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6101 65535 0]We'll have to make him see the truth![n][w][e]

