[msg D04_03_e296_336_mes01 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Wasn't there something like this[n]before? You know, when we had to[n]use that shining gem from Anubis.[n][w][e]

[msg D04_03_e296_336_mes02 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We already have another one of those[n]gems, do we not? We should try placing[n]it in here.[n][w][e]

[msg D04_03_e296_336_selA_0_m [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]

[msg D04_03_e296_336_selA_1_m [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4026 65535 0]Very well. I was looking forward to[n]seeing what would happen, but I[n]suppose that can wait...[n][w][e]

[msg D04_03_e296_336_mes03 [Fox]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4048 65535 0]Hm, this sight brings a tear to my eye[n]yet again![n][w][e]

[msg D04_03_e296_336_mes04 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You're so freakin' weird, dude...[n][w][e]

[msg MSG_e296_336_AF01_000 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're supposed to put the gem from[n]that statue here, right?[n][w][e]

[msg D04_03_e296_336_AF02_mes [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wasn't there something like this[n]before? You know, when we had to[n]use that shining gem from Anubis.[n][w][e]

[msg D04_03_e296_336_AF02_mes_2 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm, we will need to obtain another one.[n]Very well, let us go search for it.[n][w][e]

[msg MSG_e296_336_AF03_000 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We'll need a gem from an Anubis statue.[n]Let's get looking![n][w][e]
