[msg MSG_QST_083_01 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]There! That's Tamako Takuno![n][w][e]

[msg MSG_QST_083_02 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]According to the info we have...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]The fans know that she lost on purpose.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]It would be a problem if the media found[n]out.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]She's gotten threats, saying that if she[n]doesn't cooperate with the rigged games,[n]they'll kill her.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]She hit a wall when she became a pro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]It's even hard for a pro to make money if[n]they don't win.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]This is our evidence! Let's convince her[n]and change her heart![n][w][e]

[msg MSG_QST_083_03 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Are you Tamako Takuno? We're the[n]Phantom Thieves.[n][w][e]

[msg MSG_QST_083_05 [Violet]]
[s][bup 0 10 102 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]No! We want to talk about the rigged games[n]and sport bettings![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Why did you make that mistake!?[n][w][e]

[msg MSG_QST_083_08 [Violet]]
[s][bup 0 10 103 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]And you went with it.[n][w][e]

[msg MSG_QST_083_10 [Panther]]
[s][bup 0 4 103 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]I think I know the feeling...[n][w][e]

[msg MSG_QST_083_11 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]But a crime is a crime. You can't just act like[n]it didn't happen.[n][w][e]

[msg MSG_QST_083_13 [Violet]]
[s][bup 0 10 100 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]You have to confess.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Do it while there are still people who are[n]worried about you and who care about you.[n][w][e]

