[msg QUEST_40_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Look. That must be Naguri's Shadow.[n][w][e]

[msg QUEST_40_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]There it is... Naguri's Shadow.[n][w][e]

[msg QUEST_40_ENTER_mes02 [Queen]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He's got a crazy look in his eyes.[n][w][e]

[msg QUEST_40_ENTER_mes03 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He's been known to attack indiscriminately.[n]I suppose he really has lost his sanity...[n][w][e]

[msg QUEST_40_ENTER_mes04 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]If we don't make him have a change of[n]heart, I won't feel safe walking around[n]in public.[n][w][e]

[msg QUEST_40_ENTER_mes05 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1099 65535 0]We have to do this.[n][w][e]

[msg MSG_023_0_0 [Panther]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Oh, geez, he's the annoying type...[n][w][e]

[msg MSG_025_0_0 [Skull]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Stop playin' dumb, you crazy criminal.[n][w][e]

[msg MSG_027_0_0 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2047 65535 0]I'll show you what justice really is.[n][w][e]

[msg QUEST_40_BOSS_EV_mes04 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Urgh, let's take him down, Joker![n][w][e]

[msg MSG_031_0_0 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]"Sorry" won't cut it. You attacked and[n]hurt a lot of people, you know?[n][w][e]

[msg MSG_034_0_0 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Tell the police everything.[n][w][e]

[msg MSG_035_0_0 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Turn yourself in, and confess everything.[n][w][e]

[msg MSG_036_0_0 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Turn yourself in, and confess everything.[n][w][e]

[msg MSG_038_0_0 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]We were fortunate to have caught him[n]before anyone died. We should be quite[n]grateful for that fact.[n][w][e]

[msg QUEST_40_BATTLE_END_mes0 [Skull]]
[s][bup 0 2 100 0 0]Aww yeah, got the Treasure![n][w][e]

[msg QUEST_40_BATTLE_END_mes0_3 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Never do that again! You better fully[n]atone for the crimes you committed![n][w][e]

