[msg MSG_QST_082_01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]That old man must be Ono! Let's stop him[n]before he causes any more trouble for[n]others![n][w][e]

[msg QUEST_82_BATTLE_PRE_mes0_2 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7114 65535 0]That's the first thing out of his mouth...[n][w][e]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]But it seems like this is the old guy who's[n]making trouble in Kichijoji![n][w][e]

[msg QUEST_82_BATTLE_PRE_mes0_4 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4091 65535 0]...He's certainly disturbed.[n][w][e]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Let's end this, Joker![n][w][e]

[msg QUEST_82_BATTLE_AFTER_me_2 [Fox]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]An unfortunate consequence of isolation...[n][w][e]

[msg QUEST_82_BATTLE_AFTER_me_6 [Fox]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53720 65535 0]I'm certain that's what your family[n]wishes as well.[n][w][e]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]And from now on, instead of taking it out[n]on others, you should communicate your[n]needs directly to your family.[n][w][e]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Tell them that you're "lonely" before it's[n]too late.[n][w][e]

