[msg MSG_QST_077_01 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]There! That's Takeo Saburi![n][w][e]

[msg MSG_QST_077_02 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]According to the info we have...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]"When submitting a complaint, he just says[n]the effectiveness depends on the individual,"[n]"Automatic payments"...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]"No scientific evidence" and "people[n]recovered from sickness on their own"...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Those are our four pieces of evidence![n]Let's change his heart![n][w][e]

[msg MSG_QST_077_03 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Takeo Saburi, yes? We're the Phantom[n]Thieves.[n][w][e]

[msg MSG_QST_077_05 [Noir]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Your product, "Miracle X"... Can you explain[n]to us how it's not a fraud?[n][w][e]

[msg MSG_QST_077_08 [Noir]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]But the products are still healthy, right?[n]Why did you make this mistake?[n][w][e]

[msg MSG_QST_077_10 [Noir]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]You should have promoted it as normal[n]health drink instead of saying it could[n]"cure anything."[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Food isn't just a way to gain nutrition.[n]It can also put a smile on people's faces.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Weren't you happy to hear that people's[n]illnesses got better?[n][w][e]