[msg QUEST_60_ENTER_mes01 [Oracle]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Th-There it is. It's my uncle's Shadow.[n][w][e]

[msg QUEST_60_ENTER_mes02 [Oracle]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He's saying, "money, money"...[n][w][e]

[msg QUEST_60_ENTER_mes03 [Oracle]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He forced Sojiro to pay back his debts. He[n]made me go through horrible things, too.[n][w][e]

[msg QUEST_60_ENTER_mes04 [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]...Joker, make him have a change of heart![n][w][e]

[msg MSG_003_0_0 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]I'm not getting destroyed by someone[n]like him![n][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Let's go, Joker![n][w][e]

[msg MSG_005_0_0 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]You were thinking about Mom...?[n][w][e]

[msg MSG_009_0_0 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Uncle...[n][w][e]

[msg MSG_010_0_0 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Now he won't sue anyone, right?[n][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Sojiro's safe now![n][w][e]