[msg QUEST_49_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Is that Akitsu's Shadow?[n][w][e]

[msg QUEST_49_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]There it is—Akitsu's Shadow.[n][w][e]

[msg QUEST_49_ENTER_mes02 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]It looks a little anxious.[n][w][e]

[msg QUEST_49_ENTER_mes03 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]I hear he's been repeatedly changing[n]his name and face with plastic surgery[n]to escape debt.[n][w][e]

[msg QUEST_49_ENTER_mes04 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]The police will never catch him,[n]so it's up to us.[n][w][e]

[msg QUEST_49_ENTER_mes05 [Skull]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7198 65535 0]Yeah. Let's go![n][w][e]

[msg MSG_018_0_0 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7043 65535 0]Hey, we'd never accept any help from[n]a guy as bad as you.[n][w][e]

[msg MSG_019_0_0 [Queen]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]You'd better return all the money[n]you stole![n][w][e]

[msg MSG_021_0_0 [Fox]]
[s][bup 0 5 2 65535 0][vp 1 0 0 0 0 0]I disagree. You've been running away,[n]always hiding behind a new name and[n]face.[n][w][e]

[msg QUEST_49_BOSS_EV_mes04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Let's do this![n][w][e]

[msg MSG_029_0_0 [Panther]]
[s][bup 0 4 0 65535 0][vp 1 0 0 0 0 0]So, you were saying the Phantom Thieves[n]were hypocrites?[n][w][e]

[msg MSG_031_0_0 [Fox]]
[s][bup 0 5 0 65535 0][vp 1 0 0 0 0 0]From now on, live your life with an[n]open heart and nothing to hide.[n][w][e]

