[msg QUEST_58_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]So is that the Shadow of the mother[n]of that shogi player, Hifumi?[n][w][e]

[msg QUEST_58_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Wah, it's the Shadow. That's the mom[n]of that shogi player, Hifumi, right?[n][w][e]

[msg QUEST_58_ENTER_mes02 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]She's using her just like a pawn, from[n]what I hear.[n][w][e]

[msg QUEST_58_ENTER_mes03 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]That's her own daughter... What is wrong[n]with her?[n][w][e]

[msg QUEST_58_ENTER_mes04 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]I don't know much about shogi, but I do[n]know she's a bad person![n][w][e]

[msg QUEST_58_ENTER_mes05 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]It's as you say, Lady Ann! Let's get her![n][w][e]