[msg MSG_QST_074_01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]There! That's our target, Yuko Amai![n][w][e]

[msg MSG_QST_074_02 [Panther]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6115 65535 0]Tricking people and stealing their[n]money is unforgivable![n][w][e]

[msg MSG_QST_074_03 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2023 65535 0]Yes. Let's change her heart and prevent[n]her from deceiving any more people![n][w][e]

[msg MSG_QST_074_05 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2187 65535 0]Your horrible scam ends now.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Exploiting loopholes in the law for your[n]own gain... You should be ashamed of[n]yourself![n][w][e]

[msg MSG_QST_074_09 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2023 65535 0]That's right. Your crimes can't be forgiven.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]That's why you'll have to spend the rest of[n]your life atoning for it... Can you promise[n]us that?[n][w][e]

[msg MSG_QST_074_10 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2023 65535 0]...We changed your heart, so we'll believe[n]you.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]That's why you'll have to spend the rest of[n]your life atoning for it... Can you promise[n]us that?[n][w][e]

[msg MSG_QST_074_11 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2023 65535 0]That's right. If you do it again, we'll just[n]change your heart again.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]That's why you'll have to spend the rest of[n]your life atoning for it... Can you promise[n]us that?[n][w][e]

[msg MSG_QST_074_13 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7046 65535 0]If you go back on your word, Queen's fist[n]of the phantom star's gonna beat your ass![n][w][e]

