[msg e195_112_LOOK_mes02 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]What, you find something?[n][w][e]

[msg e195_112_LOOK_mes03 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're here to investigate, so we[n]should check everything that[n]catches our attention.[n][w][e]

[msg e195_112_LOOK_mes04 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1111 65535 0]Hold on. We should look into that[n]pamphlet before we go.[n][w][e]

[msg e195_112_mes01 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]Is this... a pamphlet?[n][w][e]

[msg e195_112_mes02 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This is gettin' way too detailed for a[n]freakin' Palace... Why'd he bother[n]makin' something like this?[n][w][e]

[msg e195_112_mes03 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, there's a museum guide on here.[n]Let's take it with us![n][w][e]

[msg e195_112_mes04 [Panther]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6157 65535 0]Yeah! It might even show us the location[n]of the Treasure![n][w][e]

[msg e195_112_mes05 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1166 65535 0]That is a possibility. At the very least,[n]it should be good reference for[n]the scale of this place.[n][w][e]

[msg e195_112_mes06 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Huh...? But the map only shows half[n]of the museum...[n][w][e]

[msg e195_112_mes07 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I see... It says it's one out of two.[n][w][e]

[msg e195_112_mes08 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7028 65535 0]Then the two outta two's gotta be[n]around here somewhere, right?[n]Just how big is this place...?[n][w][e]

[msg e195_112_mes09 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We can worry about that another time.[n]Right now our objective is confirming[n]Madarame's cognition.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We may have to reconsider our plan[n]depending on what we find.[n][w][e]

[msg e195_112_mes10 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I mean, he's got a Palace... Seems pretty[n]sketch to me.[n][w][e]

