[msg MSG_QST_076_01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]There she is! That's Chiyo Tsumano![n]According to what we dug up...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]"It's plagiarism if you trace art and publish it[n]as your own," "The popularity was putting pressure[n]on her" and...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]"She looked stressed in an interview"![n]Let's convince her and change of heart![n][w][e]

[msg MSG_QST_076_02 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Are you Chiyo Tsumano?[n][w][e]

[msg MSG_QST_076_04 [Fox]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Tsumano-san, why are you plagiarizing?[n]Tell me your reasons![n][w][e]

[msg MSG_QST_076_07 [Queen]]
[s][bup 0 6 103 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]You let the temptation get the better of[n]you when you were under pressure.[n][w][e]

[msg MSG_QST_076_09 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]I'm not familiar with manga. I have no[n]idea if you have what it takes to become[n]a manga artist.[n][w][e]

[msg MSG_QST_076_10 [Skull]]
[s][bup 0 2 104 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]H-Hey, Yusuke...[n][w][e]

[msg MSG_QST_076_11 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]But I could feel the emotions of your[n]characters through your drawings.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Being able to convey emotion through art...[n]Is that not talent?[n][w][e]

[msg MSG_QST_076_13 [Panther]]
[s][bup 0 4 101 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]I think you do. You were able to draw[n]without plagiarizing up until you got[n]popular, right?[n][w][e]

[msg MSG_QST_076_15 [Fox]]
[s][bup 0 5 101 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Then you must atone for your sins.[n]For your own sake, if no one else's.[n][w][e]
