[msg MSG_QUEST80_ENTER_01 [Oracle]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9100 65535 0]There, that's Amasaki! Let's stop him for his[n]brother's sake![n][w][e]

[msg MSG_QUEST80_BATTLE_PRE_0_2 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7026 65535 0]So you're Amasaki! You seriously don't give[n]a damn about how much trouble you're[n]causing your family?[n][w][e]