[msg QUEST_12_ENTER_mes01 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Look. It's Sakoda's Shadow.[n][w][e]

[msg QUEST_12_ENTER_mes01f [Oracle]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah... It's Sakoda's Shadow.[n][w][e]

[msg QUEST_12_ENTER_mes02 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]Look at 'im... Thinks he's some kinda[n]hotshot.[n][w][e]

[msg QUEST_12_ENTER_mes03 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]He's the guy who's really behind all that[n]bullying, right?[n][w][e]

[msg QUEST_12_ENTER_mes04 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7198 65535 0]Yeah. If we wanna stop the bullying,[n]we gotta take him down.[n][w][e]

[msg QUEST_12_ENTER_mes05 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6034 65535 0]Let's go.[n][w][e]

[msg MSG_082_0_0 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 7046 65535 0]No jerk's got the right to go around,[n]blackmailin' people![n][w][e]

[msg MSG_084_0_0 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]You gotta be kidding! You're not strong[n]you're just a coward who won't get his[n]hands dirty![n][w][e]

[msg MSG_092_0_0 [Panther]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]Why don't you just admit you lost? You're[n]acting kind of pathetic right now.[n][w][e]

[msg MSG_094_0_0 [Skull]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]All right. Now it's time for you to get[n]eaten. The strong eat the weak or[n]somethin', right?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]When I'm done with you, there's gonna[n]be nothin' left but bone. You ready?[n][w][e]

[msg MSG_096_0_0 [Skull]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 7048 65535 0]...Kiddin'. You don't gotta say sorry to us.[n]Go apologize to who you really need to[n]apologize to![n][w][e]

[msg OTKR_GET_mes01 [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Let's get the Treasure! Case closed![n][w][e]

