[msg TalkMsg_GUY_OP_03_01 [Skull]]

[msg TalkMsg_Coop_Reiji_00 [Skull]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 2 10 301 1]Hey, what are you tryin' to pull?[n]Use your head, man![n][w][e]

[msg TalkMsg_Coop_Reiji_01 [Skull]]
[s]It seems like the Shadow reconsidered...[n][w][e]

[msg TalkMsg_Coop_Morgana_00 [Mona]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 3 10 301 1]Don't move! Your very life is on the line![n][w][e]

[msg TalkMsg_Coop_Morgana_01 [Mona]]
[s]It seems like the Shadow reconsidered...[n][w][e]

[msg TalkMsg_Coop_Ann_00 [Panther]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 4 3 301 1]Don't move—unless you wanna get[n]filled with lead![n][w][e]

[msg TalkMsg_Coop_Ann_01 [Panther]]
[s]It seems like the Shadow reconsidered...[n][w][e]

[msg TalkMsg_Coop_Yugo_00 [Fox]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 5 3 301 1]Consider well the position you are in.[n]I do not appreciate that impression.[n][w][e]

[msg TalkMsg_Coop_Yugo_01 [Fox]]
[s]It seems like the Shadow reconsidered...[n][w][e]

[msg TalkMsg_Coop_Makoto_00 [Queen]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 6 3 301 1]Stop resisting and work with us here![n][w][e]

[msg TalkMsg_Coop_Makoto_01 [Queen]]
[s]It seems like the Shadow reconsidered...[n][w][e]

[msg TalkMsg_Coop_Haruko_00 [Haru]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 7 3 301 1]Please wait! Do you understand the[n]position you find yourself in?[n][w][e]

[msg TalkMsg_Coop_Haruko_01 [Haru]]
[s]It seems like the Shadow reconsidered...[n][w][e]

[msg TalkMsg_Coop_Akechi_00 [Crow]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]Wait! You would be wise not to attempt[n]any sudden moves.[n][w][e]

[msg TalkMsg_Coop_Akechi_01 [Crow]]
[s]It seems like the Shadow reconsidered...[n][w][e]

[msg TalkMsg_Sense_Sixthsense [Crow]]
[s]Initiating Sixth Sense![n][f 1 3 65535][w][e]
[s]Your heightened sense has made clear[n]an option that should not be chosen![n][w][e]

[msg TalkMsg_Sense_Negotiatio [Crow]]
[s]Initiating Negotiation![n][f 1 3 65535][w][e]
[s]With heightened negotiation technique,[n]you now receive greater cooperation![n][w][e]

[msg TalkMsg_Sense_Gigolo_00 [Crow]]
[s]Initiating Gigolo![n][f 1 3 65535][w][e]
[s]Showing off your refined seduction[n]stimulates the hearts and minds[n]of female Shadows![n][w][e]

[msg TalkMsg_Sense_Performanc [Crow]]
[s]Initiate Performance![n][f 1 3 65535][w][e]
[s]Your splendid antics captivate[n]the enemy Shadow's interest![n][w][e]

[msg TalkMsg_Sense_Intelligen [Crow]]
[s]Initiate Intelligence![n][f 1 3 65535][w][e]
[s]Your broad-based display of knowledge[n]wins the respect of male Shadows![n][w][e]

[msg CharmTech [Panther]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]Come on, hot stuff. Can't you be a little[n]more gentle with me?[n][w][e]

[msg CharmActing [Panther]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]Wahhhh!!! How c-could you ask[n]that of us!?[n][w][e]

[msg CheapAct [Panther]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 4 5 300 1]Joker, this is too scary... We should get[n]out of here. Hey! Could you tell your[n]boss that we're leaving now?[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_4 [Panther]]
[s]Then I'll just give the me you already have[n]some experience![n][w][e]

[msg TalkMsg_Coop_AkechiB_00 [Panther]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]Huh, I wouldn't say that's a wise choice...[n]Perhaps you should give this some more[n]thought.[n][w][e]

[msg TalkMsg_Coop_Kasumi_00 [Panther]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]Stop! I think you would be wise not[n]to make any careless moves.[n][w][e]

[msg TalkMsg_Coop_Sumire_00 [Panther]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]Stop! I think you would be wise not[n]to make any careless moves.[n][w][e]

