[msg TalkMsg_06 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1046 0 3][f 4 10 65535 0 0]Well, something along those lines...[n]Now let it be money or items. Just[n]cough it up![n][f 1 3 65535][w][e]

[msg TalkMsg_08 [Mona]]
[s][bup 0 3 10 0 0][vp 8 0 2 1047 0 3][f 4 10 65535 0 0]W-Wait, what? Oh... This isn't how I was[n]planning this to go.[n][f 1 3 65535][w][e]

[msg TalkMsg_21 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1048 0 3][f 4 10 65535 0 0]Uhhh, if that's the case... I guess it's time[n]for you to go to hell.[n][f 1 3 65535][w][e]

[msg TalkMsg_10 [Mona]]
[s][bup 0 3 1 0 0][vp 8 0 2 1014 0 3][f 4 10 65535 0 0]Sorry, but we're in a hurry.[n][f 1 3 65535][w][e]

[msg TalkMsg_17 [Mona]]
[s][bup 0 3 4 0 0][vp 8 0 2 1024 0 3][f 4 10 65535 0 0]What the...!? What's going on!?[n][f 1 3 65535][w][e]
