[msg MSG_BTLSTART_001 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]You have the gun with you, right?[n]Point it at a Shadow and fire![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]Point it at a Shadow and fire![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Mona]]
[s][bup 0 3 1 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]How about that!? Surprised?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1003 0 3][f 4 10 65535 0 0]There are plenty of instances where[n]rapid fire's going to be more useful[n]than swinging your knife.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1004 1 3][f 4 10 65535 0 0]Of course, you can run out of ammo,[n]but using it all up does more good[n]than letting it collect dust![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Mona]]
[s][bup 0 3 1 0 0][vp 8 0 2 1005 0 3][f 4 10 65535 0 0]All right, I'll show you my weapon too![n][f 1 3 65535][w][e]

