[msg MSG_BTLSTART_001 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1049 0 3][f 4 10 65535 0 0]Remember how I taught you Hold Ups[n]and All-Out Attacks? I'll teach you their[n]practical use now.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1050 0 3][f 4 10 65535 0 0]There's another use for Hold Ups[n]besides simply defeating enemies.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1051 0 3][f 4 10 65535 0 0]Shadows are beings born from people's[n]hearts, so naturally, they can talk too.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1052 0 3][f 4 10 65535 0 0]In other words, you can communicate[n]with them. Get it?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1053 0 3][f 4 10 65535 0 0]If you talk to them when they're cornered,[n]they might offer money or items since[n]they don't want to die.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1054 0 3][f 4 10 65535 0 0]In fact, talking has a better chance of[n]scoring something great, as opposed[n]to just offing them.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1055 0 3][f 4 10 65535 0 0]Well then, let's do the first step:[n]Knock all the enemies down, and do[n]a Hold Up![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Mona]]
[s]Now! Surround them![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Mona]]
[s][bup 0 3 4 0 0][vp 8 0 2 1056 0 3][f 4 10 65535 0 0]What was that just now...?[n]What happened...!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Mona]]
[s][bup 0 3 1 0 0][vp 8 0 2 1028 0 3]Hehe... it seems like you really will[n]be useful![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_009 [Mona]]
[s]Okay, I'll try and remember their[n]weaknesses.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010 [Mona]]
[s]After all, I have excellent memory![n]It's just one of my many phantom thief[n]talents![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_011 [Mona]]
[s]During battle, you can check enemy[n]information by pressing the [clr 2]L2[clr 27][n][clr 2]button[clr 27] or selecting Analysis.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_012 [Mona]]
[s]Furthermore, if you have a skill that[n]targets enemy weaknesses,[n]press [clr 2]R2[clr 27] to select it automatically.[n][f 1 3 65535][w][e]

