[msg MSG_BTLSTART_001 [Skull]]
[s][bup 0 2 0 65535 0]We're surrounded! This don't look[n]so good...![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Mona]]
[s][bup 0 3 0 0 0]We have to endure it, you guys![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Mona]]
[s]Observe carefully, then strike![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Mona]]
[s]Looks like you're finally getting a[n]hang of the basics.[n][f 1 3 65535][w][e]
