[msg MSG_BTLSTART_001 [Panther]]
[s][bup 0 4 122 0 0][vp 8 0 2 1002 0 4][f 4 10 65535 0 0]That dirtbag just sees women as sexual[n]outlets! Don't make me laugh with that[n]"love" bullshit![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Panther]]
[s][bup 0 4 122 0 0][vp 8 0 2 1003 0 4][f 4 10 65535 0 0]C'mon, Carmen! Let's give 'em hell![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Panther]]
[s][bup 0 4 100 0 0][vp 8 0 2 1007 0 4][f 4 10 65535 0 0]Pfft, outside of school, that guy's nothing[n]but a pathetic loser![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Panther]]
[s]dummy[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1004 0 3]Look! He's trying to do something![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_009 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1005 0 3]It's important to guard if you think[n]you're in danger![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010 [Mona]]
[s]Selecting Guard will decrease damage[n]taken as well as prevent knockdowns[n]and ailments.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_011 [Mona]]
[s]If you think you'll receive heavy[n]damage or have your weakness targeted,[n]be sure to Guard.[n][f 1 3 65535][w][e]

