[msg MSG_BTLSTART_003 [Fox]]
[s][bup 0 5 122 0 0][vp 8 0 2 1003 0 5][f 4 10 65535 0 0]I learned much from you, Madarame.[n]In order to see authenticity... one must[n]be dispassionately realistic.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Fox]]
[s][bup 0 5 122 0 0][vp 8 0 2 1004 0 5][f 4 10 65535 0 0]With Goemon by my side... I can now[n]ascertain your true self without any[n]reservations![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Fox]]
[s][bup 0 5 100 0 0][vp 8 0 2 1009 0 5][f 4 10 65535 0 0]It matters not how many come...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Fox]]
[s][bup 0 5 102 0 0][vp 8 0 2 1010 0 5][f 4 10 65535 0 0]Goemon and I will not be daunted by[n]your forgery![n][f 1 3 65535][w][e]

