[msg MSG_BTLSTART_002 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]You were taught a technique to defeat[n]him, weren't you?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1003 0 3][f 4 10 65535 0 0]Go kick that cheating bastard's ass[n]with it![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 0 2 1004 0 8][f 4 10 65535 0 0]A gamer taught you the moves to take[n]him down, right?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 0 2 1005 0 8][f 4 10 65535 0 0]Teach that stupid cheater a lesson![n][f 1 3 65535][w][e]

