[msg MSG_BTLTALK_START_001 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 9021 0 8][f 4 10 65535 0 0]Sounds like this guy REALLY doesn't like[n]the section chief.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Let's try and pump him for information,[n]Joker![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_END_000 [Oracle]]
[s][bup 0 8 601 0 0][vp 8 2 2 9190 0 8][f 4 10 65535 0 0]Mweheheh, so the section chief is weak[n]to [clr 2]Wind[clr 27], is he?[n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_END_001 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]We didn't get any deets on the chief[n]director, but this is still good![n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Looks like this guy's done chatting,[n]so let's clean up, Joker![n][f 1 3 65535][w][e]

