[msg MSG_BTL_TALK_FAILD [Mona]]
[s][bup 0 3 4 0 0][vp 8 2 2 1029 0 3][f 4 10 65535 0 0]Crap, we couldn't calm her down![n]We'll have to find a different way![n][f 1 3 65535][w][e]

[msg MSG_BTL_START_001 [Mona]]
[s][bup 0 3 4 0 0][vp 8 2 2 1038 0 3][f 4 10 65535 0 0]Joker, it seems like there's something[n]going on with this one. Maybe we should[n]try talking to them.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Okay, here's what we know about her.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]She's calling the cats she catnapped[n]"snowballs," the catnapped cats are[n]"stressed out"...[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]And lastly, "the pet owners are giving up."[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_001 [Mona]]
[s][bup 0 3 2 0 0][vp 8 2 2 1025 0 3][f 4 10 65535 0 0]What does she mean by snowballs?[n]That's so weird.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Are all cats snowballs!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Mona]]
[s][bup 0 3 2 0 0][vp 8 2 2 1038 0 3][f 4 10 65535 0 0]They'll die "too"?[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]So the real Snowball is already gone?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_002 [Mona]]
[s][bup 0 3 2 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Okay, I think we've got this. She's[n]calm enough for us to talk to her now.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Go for it, Joker![n][f 1 3 65535][w][e]
