[msg MSG_BTLREACTION_MONA_01 [Mona]]
[s][vp 8 2 2 1040 0 3][bup 0 3 4 0 0][f 4 10 65535 0 0]I can't believe this guy...![n][f 1 3 65535][w][e]

[msg MSG_BTLREACTION_MONA_03 [Mona]]
[s][vp 8 2 2 1104 0 3][bup 0 3 2 0 0][f 4 10 65535 0 0]Heh! This guy's nothing! Let's finish him[n]off Joker![n][f 1 3 65535][w][e]

[msg MSG_BTLREACTION_MONA_02 [Mona]]
[s][vp 8 2 2 1104 0 3][bup 0 3 2 0 0][f 4 10 65535 0 0]This guy could practically win an[n]award for being this narcissistic.[n]Let's finish him, Joker![n][f 1 3 65535][w][e]