[msg MSG_BTLSTART_001 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]I'll support you![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]Ryuji, Lady Ann! Don't push yourselves.[n]I'll take care of the rest![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Not bad...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]But now it's my turn! Let's go, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Mona]]
[s][bup 0 3 0 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]All right, let's go for you-know-what![n][f 1 3 65535][w][e]
