[msg MSG_BTL_START_001 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Let's try to have a conversation![n]Perhaps she will think it over![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]What...!? She healed herself with her[n]spirits alone![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0_2 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Let's try to have a conversation![n]Perhaps she will think it over![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_000 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Just so we're clear... That match was[n]fixed, was it not?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_000 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]It's only a matter of time before[n]the public finds out the truth. Please, just[n]come clean.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_001 [Violet]]
[s][bup 0 10 104 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Looks like that didn't work. Perhaps we[n]should try saying something different.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_000 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Apparently, you made this mistake on[n]purpose. Everyone already knows this.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]And, the client is a long time fan.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_001 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Seems like we couldn't convince her.[n]Perhaps we should try again.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_000 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]I heard even if you're pro it's pretty hard[n]to live on, unless you continue to win.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Did you perhaps stop aiming up, and[n]let yourself give in to money?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_001 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Seems like we couldn't convince her.[n]Perhaps we should try again.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_001 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]You became a pro, but then it became[n]harder for you to survive... And that's[n]why you took on this deed?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_002 [Violet]]
[s][bup 0 10 102 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]So... You went through all that difficult[n]training and became pro, just to willingly[n]lose!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_003 [Violet]]
[s][bup 0 10 102 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]There're people who gave up their[n]dreams because they lost to you![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_005 [Violet]]
[s][bup 0 10 103 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]No, I know exactly what you mean! We[n]live in a world where working hard[n]doesn't guarantee you anything.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_006 [Violet]]
[s][bup 0 10 103 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]And that's why I understand. The[n]thoughts you must have had when[n]this alluring offer was given to you...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_007 [Violet]]
[s][bup 0 10 102 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]But there are things you can and cannot[n]do! You are only making a mockery of[n]the sport you love![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_001 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Seems like we couldn't convince her.[n]Perhaps we should try again.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_000 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Were you told something like,[n]"If you don't lose, you're dead" ?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_002 [Violet]]
[s][bup 0 10 102 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Please, stop this nonsense! They're[n]only bluffing![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_003 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]If you continue to do these fixed[n]matches, you'll lose everything![n]You'll be kicked out![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_005 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]You have to stop this... Otherwise,[n]one day, they're going to find out.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_006 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Please, stop betraying people and[n]disgracing yourself![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_007 [Violet]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Try and remember how you felt in[n]your heart, when you were practicing[n]with passion and integrity![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_002_001 [Violet]]
[s][bup 0 10 104 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Seems like we couldn't convince her.[n]Perhaps we should try again.[n][f 1 3 65535][w][e]
