[msg MSG_BTL_START_001 [Oracle]]
[s][bup 0 8 602 0 0][vp 8 2 2 9158 0 8][f 4 10 65535 0 0]This guy's not making any sense...[n]Let's try to calm him down, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTL_PRETALK_001_000 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 9158 0 8][f 4 10 65535 0 0]Hey Joker, maybe we're being too nice,[n]but I think we should try talking to him.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 8][f 4 10 65535 0 0]So, here's the stuff we know about him.[n][f 1 3 65535][w][e]

[msg MSG_BTL_PRETALK_002_000 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 0 0 8][f 4 10 65535 0 0]"He's got a friend at Akihabara,"[n]"He seemed most happy when he[n]was nerding out," and...[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 8][f 4 10 65535 0 0]"His parents got upset at him for[n]failing his entrance exam"...[n][f 1 3 65535][w][e]

[msg MSG_BTL_PRETALK_003_000 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 0 0 8][f 4 10 65535 0 0]For some reason, I can't just leave[n]him behind.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FAILED [Oracle]]
[s][bup 0 8 604 0 0][vp 8 2 2 9040 0 8][f 4 10 65535 0 0]Crap! Looks like we made it worse![n]It's prolly best if we chose what you[n]say wisely![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_001 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 0 0 8][f 4 10 65535 0 0]Even after he found out what you were[n]doing, he insisted that you weren't the[n]type who could do such a thing.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 8][f 4 10 65535 0 0]If that isn't a friend, then what is?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Oracle]]
[s][bup 0 8 602 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]We did some research on ya.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]You went through some rough times[n]after your parents found out about[n]your exams, didn't you?[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Don't you think it's wrong to blame[n]that solely on your nerdy hobbies?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 9197 0 8][f 4 10 65535 0 0]There must've been a lotta things that[n]were fun when you were an otaku.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_002 [Oracle]]
[s][bup 0 8 600 0 0][vp 8 2 2 0 0 8][f 4 10 65535 0 0]C'mon, Joker. Tell him.[n][f 1 3 65535][w][e]

