[msg MSG_BTLSTART_010_003 [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4]Will you stop doing that every single[n]time!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_020_001 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 3]Look! The Treasure's over there![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_030_001 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 3]We should catch him off guard and[n]steal it![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 0 3]Let's attack him and wait for that[n]opportunity![n][f 1 3 65535][w][e]

[msg MSG_BTL_USETROPHY_020_00 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 3]He healed himself? Is it from eating[n]one of those... things in the trophy?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1009 0 3]Then we should destroy that first![n][f 1 3 65535][w][e]

[msg MSG_BTL_USETROPHY_030_00 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 3]He healed himself? Is it from eating[n]one of those... things in the trophy?[n][f 1 3 65535][w][e]

[msg MSG_BTL_USETROP02_010_00 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1011 0 3]We won't last if we leave[n]that trophy be![n][f 1 3 65535][w][e]

[msg MSG_BTL_TROPHY99_010_001 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 3]When someone tells us not to do[n]something, it makes us want to do it[n]even more![n][f 1 3 65535][w][e]

[msg MSG_BTL_TROPHYEND_010_00 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1017 0 3]All right![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_030_002 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1026 0 2]I always saw you as a condescending[n]hotshot, but right now... you're just a[n]pathetic loser.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_040_003 [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1027 0 4]We came all this way to steal that![n]Will you just give it up and hand[n]it over?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_050_001 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 3]You still have the energy to say things[n]like that!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_060_001 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]Then we're going to up our game[n]as well![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_000_0_2 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 2]He's as stubborn as ever... Ain't there[n]an easier way for us to deal with him?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_010_0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Then let's go with Plan B! See that[n]terrace over there!?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 3]Have someone go there while the[n]others are attacking Kamoshida![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1035 0 3]We'll catch Kamoshida off guard and[n]steal the Treasure like the phantom thieves[n]we are![n][f 1 3 65535][w][e]

[msg MSG_BTL_NORYUJI_000_001 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1036 0 3]To think he'd give someone like me[n]such a hard time... I suppose it's time[n]I pull out Plan B...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HAKENNEW_990_001 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1037 0 3]I see... In that case, time for Plan B![n][f 1 3 65535][w][e]

[msg MSG_BTL_HAKENNEW_010_001 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Look over at that terrace![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1039 0 3]While the others are drawing[n]Kamoshida's attention, have[n]someone go there![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Let's steal the Treasure without him[n]noticing![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_011_0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 3]We won't get anywhere with[n]brute force...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_999_0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]What do we do!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_012_0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 3]Then let's go with Plan B! See that[n]terrace over there!?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]Have someone go there while the[n]others are attacking Kamoshida![n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]We'll catch Kamoshida off guard and[n]steal the Treasure like the phantom thieves[n]we are![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_2 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 2 1073 0 3]...It's all going as planned.[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_3 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 2 1074 0 3]Time to use this opportunity to take[n]the Treasure![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_4 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1077 0 2]Yeah, whatever, man...[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_5 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1078 0 2]Anyway. Now's my chance![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_8 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 2 1081 0 3]He hasn't noticed a thing here.[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_9 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 2 1082 0 3]Good. Just a little more to the Treasure![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_10 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1085 0 2]What a total moron...[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_11 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1086 0 2]But at least it's lettin' me get closer[n]to the Treasure.[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_14 [Mona]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 2 1089 0 3]It's already check and mate![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_15 [Skull]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1092 0 2]Took you too long to notice, moron![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_MORGANAMIS_2 [Mona]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 2 1066 0 3]What a blunder I've made...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_MORGANAMIS_3 [Mona]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 0 2 1067 0 3]You have to attack more and draw[n]his attention![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_REIJIMISS__2 [Skull]]
[s][bup 0 2 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1069 0 2]Crap![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_REIJIMISS__3 [Skull]]
[s][bup 0 2 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1070 0 2]If you guys don't attack him more,[n]he'll notice what we're up to![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_ANNMISS_01 [Panther]]
[s][bup 0 4 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1063 0 4]Ugh, he keeps staring at me...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_ANNMISS_02 [Panther]]
[s][bup 0 4 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1064 0 4]Hey, shouldn't I stay here?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTEALAFTER_010_00 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1094 0 3]Good, Kamoshida's shaken up![n][f 1 3 65535][w][e]

[msg MSG_BTLSTEALAFTER_020_00 [Panther]]
[s][bup 0 4 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1095 0 4]I think we can do this![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010_003EX [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4]Will you stop doing that every single[n]time!?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_020_001EX [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 3]Look! The Treasure's over there![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_030_001EX [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 3]We should catch him off guard and[n]steal it![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 0 3]Let's attack him and wait for that[n]opportunity![n][f 1 3 65535][w][e]

[msg MSG_BTL_USETROPHY_020_00_2 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 3]He healed himself? Is it from eating[n]one of those... things in the trophy?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1009 0 3]Then we should destroy that first![n][f 1 3 65535][w][e]

[msg MSG_BTL_USETROPHY_030_00_2 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 3]He healed himself? Is it from eating[n]one of those... things in the trophy?[n][f 1 3 65535][w][e]

[msg MSG_BTL_USETROP02_010_00_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1011 0 3]We won't last if we leave[n]that trophy be![n][f 1 3 65535][w][e]

[msg MSG_BTL_TROPHY99_010_001_2 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 3]When someone tells us not to do[n]something, it makes us want to do it[n]even more![n][f 1 3 65535][w][e]

[msg MSG_BTL_TROPHYEND_010_00_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1017 0 3]All right![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_030_002_2 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1026 0 2]You look down on everyone... but[n]you're seriously lame right now.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_040_003_2 [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1027 0 4]We came all this way to steal that![n]Will you just give it up and hand[n]it over?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_050_001_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 3]You still have the energy to say things[n]like that!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_060_001_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]Then we're going to up our game[n]as well![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_000_0_4 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 2]He's as stubborn as ever... Ain't there[n]an easier way for us to deal with him?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_010_0_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1033 0 3]Then let's go with Plan B! See that[n]terrace over there!?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1034 0 3]While the others are drawing[n]Kamoshida's attention, have[n]someone go there![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1035 0 3]We'll catch Kamoshida off guard and[n]steal the Treasure like the phantom thieves[n]we are![n][f 1 3 65535][w][e]

[msg MSG_BTL_NORYUJI_000_001E [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1036 0 3]To think he'd give someone like me[n]such a hard time... I suppose it's time[n]I pull out Plan B...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HAKENNEW_990_001_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1037 0 3]I see... In that case, time for Plan B![n][f 1 3 65535][w][e]

[msg MSG_BTL_HAKENNEW_010_001_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 3]Look over at that terrace![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1039 0 3]Have someone go there while the[n]others are attacking Kamoshida![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 3]Let's steal the Treasure without him[n]noticing![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_011_0_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 3]We won't get anywhere with[n]brute force...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_999_0_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]What do we do!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOWTOSTEAL_012_0_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Then let's go with Plan B! See that[n]terrace over there!?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1045 0 3]Have someone go there while the[n]others are attacking Kamoshida![n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1046 0 3]We'll catch Kamoshida off guard and[n]steal the Treasure like the phantom thieves[n]we are![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_17 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 2 1073 0 3]...It's all going as planned.[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_18 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 2 1074 0 3]Time to use this opportunity to take[n]the Treasure![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_19 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1077 0 2]Yeah, whatever, man...[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_20 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1078 0 2]Anyway. Now's my chance![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_23 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 2 1081 0 3]He hasn't noticed a thing here.[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_24 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 2 1082 0 3]Good. Just a little more to the Treasure![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_25 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1085 0 2]What a total moron...[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_26 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1086 0 2]But at least it's lettin' me get closer[n]to the Treasure.[n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_29 [Mona]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 2 1089 0 3]It's already check and mate![n][f 1 3 65535][w][e]

[msg MSG_KAMOSHIDA_ATTENTION0_30 [Skull]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1092 0 2]Took you too long to notice, moron![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_MORGANAMIS_5 [Mona]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 2 1066 0 3]I really messed up...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_MORGANAMIS_6 [Mona]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 0 2 1067 0 3]You have to attack more and draw[n]his attention![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_REIJIMISS__5 [Skull]]
[s][bup 0 2 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1069 0 2]Crap![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_REIJIMISS__6 [Skull]]
[s][bup 0 2 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1070 0 2]If you guys don't attack him more,[n]he'll notice what we're up to![n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_ANNMISS_01_2 [Panther]]
[s][bup 0 4 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1063 0 4]Ugh, he keeps staring at me...[n][f 1 3 65535][w][e]

[msg MSG_ATTENTION_ANNMISS_02_2 [Panther]]
[s][bup 0 4 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1064 0 4]Hey, shouldn't I stay here?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTEALAFTER_010_00_2 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1094 0 3]Good, Kamoshida's shaken up![n][f 1 3 65535][w][e]

[msg MSG_BTLSTEALAFTER_020_00_2 [Panther]]
[s][bup 0 4 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1095 0 4]I think we can do this![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010_100 [Panther]]
[s][bup 0 4 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4](未使用)モナ! その前にアレ、やってみる?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010_101 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 3](未使用)OK! お見舞いしてやるぜ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PRE_TROPHY_00 [Panther]]
[s][bup 0 4 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4](未使用)待って! あのトロフィーの中...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PRE_TROPHY_00_2 [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4](未使用)カット[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PRE_TROPHY_00_3 [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4](未使用)ここって、[n]カモシダのイメージが作り出した城なんでしょ?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PRE_TROPHY_00_4 [Panther]]
[s][bup 0 4 103 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4](未使用)カット[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PRE_TROPHY_00_5 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1076 0 2](未使用)ってことは、あのトロフィーって...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PRE_TROPHY_00_6 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3](未使用)そうか、良いところに気がついたな![n]確かに放っといたら今にも食い出しそうだ。[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3](未使用)オタカラの王冠より先に、[n]あのトロフィーを壊しちまうか!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_MORGANA_OUT01 [Mona]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3](未使用)くっ、ワガハイとしたことが...[n]パレスの主がここまでの力とはな。[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_MORGANA_OUT02 [Panther]]
[s][bup 0 4 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4](未使用)ちょっと大丈夫!?[n]カモシダの攻撃、ヤバすぎでしょ...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_MORGANA_OUT03 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1076 0 2](未使用)クソっ![n]せめて誰が狙われてるかでも分かりゃ...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_MORGANA_OUT04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3](未使用)そうか、その手があったな![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3](未使用)ワガハイ、カモシダの観察に[n]専念して誰を狙っているか教えてやろうか?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_MORGANA_OUT04_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3](未使用)あいかわらず危ない攻撃が続くな...[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3](未使用)やっぱりワガハイ、観察に専念して[n]誰を狙っているか教えようか?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_MORGANA_OUT_O [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3](未使用)よし、ワガハイは支援に専念する。[n]ワガハイの情報を当てにしてくれていいぜ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_MORGANA_OUT_N [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3](未使用)そうか![n]ならワガハイも戦力として当てにしてくれ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_MORGANA_RECON [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3](未使用)大丈夫か?[n]狙いが知りたきゃワガハイ支援に回るか?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_TARGET_PC01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3](未使用)ジョーカーが狙われてる![n](カット予定)ちゃんとガードしろよ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_TARGET_PC02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0](未使用)スカルが狙われてる![n](カット予定)ちゃんとガードしろよ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_TARGET_PC03 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0](未使用)ワガハイが狙われてる![n](カット予定)ガードだよな!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_TARGET_PC04 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0](未使用)パンサーが狙われてる![n](カット予定)しっかりガードするんだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_HAKEN_NOT_ENO [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3](未使用)全然効いてないぞ![n]もっとガンガン攻撃しないと作戦がバレちまう![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_HAKEN_SOON_EN [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3](未使用)もうチョイだ![n]あと1~2発ぐらい攻撃すれば気をêけるぞ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_HAKEN_ENOUGH [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3](未使用)もう十分だ![n]カモシダの注Äは完全にそっちに向いてる![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PROVOKE01A [Panther]]
[s][bup 0 4 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4](未使用)うわ! キッモ! 何そのセンス。[n]見てるこっちが恥ずかしくなる...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PROVOKE01B [Panther]]
[s][bup 0 4 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 4](未使用)先生~![n]教師って、変態でもなれるんですか~!?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PROVOKE02A [Skull]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1098 0 2](未使用)ヘイヘイ、変態クソ教師!![n]こっちだぜ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PROVOKE02B [Skull]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 2 1098 0 2](未使用)センセ~イ![n]指導が必要なのは、テメーのほうじゃねえの~?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PROVOKE03A [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3](未使用)お~いお~い! 鬼さんコチラ![n]まあ、変態の攻撃なんて当たらないけどな~![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_PROVOKE03B [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3](未使用)どこ見てる! こっちだ![n]そこの役立たずのデカブツ![n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_RYUJI_10 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1053 0 2](未使用)なあ、カモシダの注Äをêくんだろ!?[n]俺がカモシダの野郎を挑発してやろうか?[n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_RYUJI_11 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1053 0 2](未使用)俺が挑発してれば、少し手ェ出すだけで、[n]モナがバレずにオタカラに近づけると思うぜ![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 2 1053 0 2](未使用)...けど、挑発してるとき、他の行動はできねー。[n]そこはワリぃけどヨロシクな。[n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_RYUJI_11B [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1053 0 2](未使用)どーする?[n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_RYUJI_12 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 2](未使用)オッケー![n]後のことは任したぜッ![n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_RYUJI_13 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 2](未使用)そっか...自信あったけどな。[n]なら攻撃して気をêこうぜ![n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_MORGANA_10 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1056 0 3](未使用)なあ、カモシダの注Äをêくんだろ!?[n]ワガハイがカモシダのヤツを挑発してやろうか?[n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_MORGANA_11 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1056 0 3](未使用)ワガハイが挑発してる間なら、少しの攻撃でも[n]スカルが気づかれずにオタカラに近づける![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 2 1056 0 3](未使用)ちなみに、ワガハイ全力で挑発するから、[n]他の行動はできなくなるからな。[n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_MORGANA_11_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1056 0 3](未使用)どうする?[n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_MORGANA_12 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1058 0 3](未使用)よーし![n]怪盗の先輩らしいトコ見せてやるぜ![n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_MORGANA_13 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1058 0 3](未使用)ん!?[n]そうか、なら攻撃して気をêくぞ![n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_ANN_10 [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1059 0 4](未使用)[n]カモシダの挑発は私にまかせて![n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_ANN_11 [Panther]]
[s][vp 8 0 2 1060 0 4](未使用)ずっと私のほう見てるし、[n]絶対上手く行くから![n][f 1 3 65535][w][e]

[msg EXTRA_PROVOKE_ANN_12 [Panther]]
[s][vp 8 0 2 1061 0 4](未使用)[n]じゃあオタカラのほうはよろしくね![n][f 1 3 65535][w][e]

[msg ADD_TARGET_EVENT_0_1 [Skull]]
[s][bup 0 2 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1100 0 2]M-Mishima!?[n][f 1 3 65535][w][e]

[msg ADD_TARGET_EVENT_0_6 [Panther]]
[s][bup 0 4 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1101 0 4]Wait, what!? Why's he here?[n][f 1 3 65535][w][e]

[msg ADD_TARGET_EVENT_0_3 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1102 0 3]Calm down. That's only Kamoshida's[n]cognitive version of him! It's not the[n]real Mishima![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_0_2B [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1106 0 4]I'm so sorry, Mishima-kun! I swear[n]we'll spike this phony king![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_0_2C [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1107 0 2]Sorry, Mishima... We'll make sure to[n]give Kamoshida double that![n][f 1 3 65535][w][e]

[msg ADD_TARGET_EVENT_1_1 [Panther]]
[s][bup 0 4 104 65535 0][f 4 10 65535 0 0][vp 8 0 2 1121 0 4]N-No way! What's Shiho doing here!?[n][f 1 3 65535][w][e]

[msg ADD_TARGET_EVENT_1_3 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1122 0 3]Panther, calm down! That's not the[n]real one![n][f 1 3 65535][w][e]

[msg ADD_TARGET_EVENT_1_4 [Panther]]
[s][bup 0 4 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1123 0 4]Y-Yeah, you're right... But, this is just...[n][f 1 3 65535][w][e]

[msg ADD_TARGET_EVENT_1_4B [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1124 0 2]Dammit, even Suzui too! You've gone[n]too far, you piece of shit![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_1_2B [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1127 0 4]Kamoshida, I'll never forgive you![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_1_2C [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1128 0 2]Sorry, Suzui... I swear we'll beat that[n]bastard's ass![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_2_0 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1139 0 2]I know he's not the real Mishima, but...[n]Dammit, this makes things hard![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_2_1 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1140 0 3]That's just a cognitive being—you guys[n]had better not hesitate over it![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_2_2 [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1141 0 4]How dare you treat students like slaves...[n]You're scum! Nothing but scum![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_3_0 [Skull]]
[s][bup 0 2 107 65535 0][f 4 10 65535 0 0][vp 8 0 2 1142 0 2]Panther, don't worry about it. We'll take[n]care of this for you![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_3_1 [Mona]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 0 2 1143 0 3]I feel so bad for Panther... but, we have[n]to do this![n][f 1 3 65535][w][e]

[msg REMOVE_TARGET_EVENT_3_2 [Panther]]
[s][bup 0 4 105 65535 0][f 4 10 65535 0 0][vp 8 0 2 1144 0 4]Shiho... I'm sorry![n][f 1 3 65535][w][e]

[msg BALL_TAEGET_START01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1145 0 3]Hey, if we attacked the ball, wouldn't[n]that prevent Kamoshida's big attack?[n][f 1 3 65535][w][e]

[msg BALL_TAEGET_START02 [Skull]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1146 0 2]Hey, I got it! If Kamoshida doesn't get[n]the ball, won't that stop him from[n]doin' the killshot?[n][f 1 3 65535][w][e]

[msg BALL_TAEGET_START03 [Panther]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1147 0 4]...Wait! Won't Kamoshida not be able[n]to attack us if he doesn't get a ball?[n][f 1 3 65535][w][e]

[msg NO_SLAVE_0_2GO [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1151 0 3]Looks like he can't use that killshot[n]anymore—now's our chance to[n]attack him and draw his attention![n][f 1 3 65535][w][e]

[msg NO_SLAVE_0_2NOT_GO [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1152 0 3]Looks like he can't use that killshot[n]anymore! Time to give him everything[n]we've got![n][f 1 3 65535][w][e]

[msg DECISION_MORGANA01 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 0 0 3]Hey, if we attacked the ball, wouldn't[n]that prevent Kamoshida's big attack?[n][f 1 3 65535][w][e]

[msg DECISION_Q [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]What do we do?[n][f 1 3 65535][w][e]

[msg DECISION_MORGANA02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1154 0 3]You gotta go for the ball again![n][f 1 3 65535][w][e]

[msg DECISION_ANSWER [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1153 0 3]All right, let's do this![n][f 1 3 65535][w][e]

[msg DECISION_ANSWER2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1155 0 3]Roger that![n][f 1 3 65535][w][e]

