[msg MSG_ACT_START_000 [Mona]]
[s][bup 0 3 2 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Heh, not bad... But love always burns[n]the brightest when facing down[n]an opponent like this![n][f 1 3 65535][w][e]

[msg MSG_ACT_START_001 [Mona]]
[s][bup 0 3 8 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]Panther, I think the moment's finally[n]arrived—it's showtime![n][f 1 3 65535][w][e]

[msg MSG_ACT_START_002 [Panther]]
[s][bup 0 4 104 0 0][vp 8 0 2 1003 0 4][f 4 10 65535 0 0]Eh? You wanna do that right now!?[n][f 1 3 65535][w][e]

[msg MSG_ACT_START_003 [Panther]]
[s][bup 0 4 100 0 0][vp 8 0 2 1004 0 4][f 4 10 65535 0 0]Geez... Fine! Here we go![n][f 1 3 65535][w][e]

