[msg MSG_BTL_START_000 [Mona]]
[s][bup 0 3 2 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Okay, I'll show you an example first.[n]You better watch closely![n][f 1 3 65535][w][e]

[msg MSG_ACT_START_000 [Mona]]
[s][bup 0 3 2 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]Use this opportunity to Baton Pass and[n]swap your turn with someone else![n][f 1 3 65535][w][e]

[msg MSG_ACT_START_003 [Mona]]
[s][bup 0 3 2 0 0][vp 8 0 2 0 0 0][f 4 10 65535 0 0]First, swap with Panther![n][f 1 3 65535][w][e]

[msg MSG_ACT_START_002 [Mona]]
[s][bup 0 3 2 0 0][vp 8 0 2 1003 0 3][f 4 10 65535 0 0]Now, strike the enemy's weakness and[n]give the Baton Pass a try![n][f 1 3 65535][w][e]

