[msg MSG_BTLSTART_001 [Oracle]]
[s][vp 8 2 2 9043 0 8][bup 0 8 602 65535 0][f 4 10 65535 0 0]Here's another bossy-looking one...[n]Joker, let's work him over for some[n]info![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK1_001 [Oracle]]
[s][vp 8 2 2 9134 0 8][bup 0 8 604 65535 0][f 4 10 65535 0 0]Well! Sounds to me like he's got[n]some beef with the chief.[n][f 1 3 65535][w][e]

[msg MSG_BTLTALK1_001_2 [Oracle]]
[s][vp 8 0 2 0 0 0][bup 0 8 600 65535 0][f 4 10 65535 0 0]Joker, if you play him right, he might[n]dish some useful details![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK2_002 [Oracle]]
[s][vp 8 2 2 9196 0 8][bup 0 8 602 65535 0][f 4 10 65535 0 0]Nice! A classic slip of the tongue![n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0][f 4 10 65535 0 0]I don't think he has any more useful[n]dirt, so let's just mop the floor with[n]him real quick![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK2_004 [Oracle]]
[s][vp 8 2 2 9109 0 8][bup 0 8 602 65535 0][f 4 10 65535 0 0]Any boss that lets their employees[n]suffer deserves the same thing![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK2_006 [Oracle]]
[s][vp 8 2 2 9196 0 8][bup 0 8 602 65535 0][f 4 10 65535 0 0]This guy's useless! Let's just put[n]him away real quick, Joker![n][f 1 3 65535][w][e]

