[msg LOCK_CLEAR02 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right! Let's get movin'![n][w][e]

[msg EX_0009_mes01 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, it ain't openin'![n][w][e]

[msg EX_0009_mes02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This shouldn't be the only exit![n]Let's look for another way out![n][w][e]

[msg PREV_SEED_GET_EX_DOOR_me [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmm? Is that what I think it is? Joker,[n]could you take a closer look?[n][w][e]

