[msg D10_09_gimmick_start [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4192 65535 0]This is quite the change in environment.[n]Where are we now?[n][w][e]

[msg D10_09_gimmick_02 [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]An exam room?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Like... a hospital exam room?[n][w][e]

[msg D10_09_gimmick_03 [Noir]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perhaps? What an odd place.[n][w][e]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3192 65535 0]The Shadows here aren't attacking us.[n]Don't they want to stop us?[n][w][e]

[msg D10_09_gimmick_end [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Strange as it may be, they do not seem[n]hostile to us at all... Furthermore, I admit[n]I'm curious as to what this "exam" entails.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, perhaps we can talk to these[n]Shadows and gather some useful[n]information.[n][w][e]

[msg D10_09_1st_announcement_ [Panther]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]That receptionist told us to start with the[n]Information Panel...[n][w][e]

[msg D10_09_1st_announcement__2 [Panther]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, is that it?[n][w][e]

[msg D10_09_1st_announcement__4 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So we have to use an elevator to enter[n]a simple questionnaire answer?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That seems rather excessive for an exam.[n]What's the meaning behind all this?[n][w][e]

[msg D10_09_1st_announcement__6 [Crow]]
[s][bup 0 9 802 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So this is where they identify the[n]aberrational cognitions that need[n]changing...[n][w][e]

[msg D10_09_1st_announcement__7 [Skull]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]For real!? I don't want 'em messin'[n]with my mind again![n][w][e]

[msg D10_09_1st_announcement__8 [Queen]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...I suppose we have no choice but to[n]take the exam.[n][w][e]

[msg D10_09_1st_question_chec_2 [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]Huh? Neither answer is wrong, though...[n][w][e]

[msg D10_09_1st_question_chec_3 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, but this is a medical exam, not a[n]school one. They're trying to figure out[n]whether or not you need treatment.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So, maybe go with the answer that[n]you think Dr. Maruki would pick?[n][w][e]

[msg D10_09_1st_question_chec_4 [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6166 65535 0]So we have to try and figure out which[n]one Dr. Maruki would pick? Oooh,[n]this is gonna be hard...[n][w][e]

[msg D10_09_1st_question_chec_5 [Mona]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's hard to be sure of anything[n]whatsoever right now...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why don't we try asking some of these[n]other patients around here?[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They may only be cognitive beings, but[n]they still have to take the exam just like[n]we do.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maybe they can help us figure out[n]which answer's right.[n][w][e]

[msg D10_09_1st_question_chec_6 [Oracle]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9035 65535 0]I'm with Mona. Besides, if you try and fail,[n]at least you gave it a shot.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Although, I'm not opposed to just[n]plowing our way through the whole[n]exam, but...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]If you refuse their treatment regimen,[n]whatever it is, they're not gonna take[n]that lying down.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]TL;DR: be ready to fight if it comes[n]down to it![n][w][e]

[msg D10_09_second_display_lo [Noir]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We made it—the second question[n]appears to have three possible[n]answers, though.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53501 65535 0]Let's find out what we're dealing with[n]this time.[n][w][e]

[msg D10_09_2nd_question_chec_2 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4129 65535 0]Hmm... We don't know enough to[n]make a decision. We should gather[n]information.[n][w][e]

[msg D10_09_2nd_question_chec_3 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right. Let's go around and talk to[n]these folks like we did last time.[n][w][e]

[msg D10_09_Third_display_loo [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]One, two, three, four... Aw, man,[n]we got FIVE choices this time?[n][w][e]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]My brain can't take this shit anymore...[n]Can we just pick a random elevator[n]and be done with this shit?[n][w][e]

[msg D10_09_Third_display_loo_2 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I understand how you feel, but we can't[n]give up before we've even tried.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Come on, let's see what our question is.[n][w][e]

[msg D10_09_3rd_question_chec_2 [Skull]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7182 65535 0]What the—? Is this question about us?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, obviously, it's D! Let's roll.[n][w][e]

[msg D10_09_3rd_question_chec_3 [Mona]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Actually USE your brain! You're not[n]even trying![n][w][e]

[msg D10_09_3rd_question_chec_4 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]So, the conditions this time are that[n]we won't be caught, and that we can[n]only choose one use for our ability.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We should bear those in mind as[n]we consider our answer.[n][w][e]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54503 65535 0]Assuming you have a mind in the first[n]place...[n][w][e]

[msg D10_09_3rd_question_chec_5 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey! Raggin' on Mona ain't cool![n][w][e]

[msg D10_09_3rd_question_chec_6 [Mona]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1139 65535 0]Yeah, thanks, but uh, I don't think[n]I was the one being insulted there...[n][w][e]

[msg D10_FindGate_start [Panther]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6039 65535 0]What the— They're just passing through[n]that weird wall of... what even IS that!?[n][w][e]

[msg D10_FindGate_01 [Oracle]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Whoooa, so sci-fi![n][w][e]

[msg D10_FindGate_01_insert01 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, had we failed the psychological[n]exam, they would have "treated" us...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Since our answers were satisfactory,[n]I suppose we were brought to this[n]passageway instead.[n][w][e]

[msg D10_FindGate_01_insert02 [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6027 65535 0]Uhhh, okay, just... be careful.[n][w][e]

[msg D10_FindGate_03 [Skull]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What!? Who're you callin' "abnormal"[n]here!? We passed your stupid test an'[n]everything![n][w][e]

[msg D10_FindGate_04 [Oracle]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Buuuut, we weren't answering honestly.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We're gonna be seen as abnormal[n]no matter what, considering we're[n]here to stop Maruki and all.[n][w][e]

[msg D10_FindGate_end [Skull]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7113 65535 0]But that means we can't get past here[n]no matter what![n][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Agh, dammit! I'm findin' a way past[n]this thing even if it kills me![n][w][e]

[msg D10_09_gimmick_end_01 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7190 65535 0]Huh. We messed up, but we still get to[n]go on...[n][w][e]

[msg D10_09_gimmick_end_end [Violet]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]The announcement said the treatment[n]room's up ahead...[n][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm getting a bad feeling.[n][w][e]

[msg D10_09_question_ans_A [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Do you want to take Elevator [clr 2]A[clr 27]?[n][w][e]

[msg D10_09_question_ans_B [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Do you want to take Elevator [clr 2]B[clr 27]?[n][w][e]

[msg D10_09_question_ans_C [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Do you want to take Elevator [clr 2]C[clr 27]?[n][w][e]

[msg D10_09_question_ans_wron [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]You know this is the wrong answer,[n]don't you?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Are you really taking Elevator [clr 2]C[clr 27]?[n][w][e]

[msg D10_09_question_ans_D [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Do you want to take Elevator [clr 2]D[clr 27]?[n][w][e]

[msg D10_09_question_ans_E [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Do you want to take Elevator [clr 2]E[clr 27]?[n][w][e]

[msg D10_09_question_ans_wron_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]You know this is the wrong answer,[n]don't you?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Are you really taking Elevator [clr 2]E[clr 27]?[n][w][e]

[msg D10_09_research_not_end [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1192 65535 0]We haven't learned enough to make[n]an informed decision. Why don't we[n]ask the people standing around here?[n][w][e]

[msg D10_09_after_answer01_02 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]No bad news so far... I guess that really[n]was the right answer.[n][w][e]

[msg D10_09_after_answer01_03 [Skull]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So it's better to just run from some shit[n]than to try an' help? I don't buy that...[n][w][e]

[msg D10_09_after_answer01_03_2 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Maybe it means Maruki believes it best[n]to find a way to avoid being hurt.[n][w][e]

[msg D10_09_after_answer01_en [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]All right everyone, let's keep it up![n][w][e]

[msg D10_09_after_mistake01_0 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1046 65535 0]A Shadow!? Wait, does that mean...[n][w][e]

[msg D10_09_after_mistake01_0_3 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hear that? Any of you interested in[n]"proper treatment"?[n][w][e]

[msg D10_09_after_mistake01_e [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Hell no! Time to throw down![n][w][e]

[msg D10_09_after_answer02_01 [Violet]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]I guess we were right, but... I'm not sure[n]how I feel about that.[n][w][e]

[msg D10_09_after_answer02_03 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's not that we agree with you—we were[n]just trying avoid the wrong answer.[n][w][e]

[msg D10_09_after_answer02_07 [Violet]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dr. Maruki thinks people should give up[n]on their dreams?[n][w][e]

[msg D10_09_after_answer02_en [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]More accurately, he thinks people[n]shouldn't cause themselves pain[n]in their pursuit of dreams.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Something to that effect.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]This exam is likely intended to filter[n]people who are inclined to do such[n]a thing.[n][w][e]
[s][bup 0 9 812 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]At any rate, contemplating the[n]completed questions is nothing[n]but a waste of our time.[n][w][e]

[msg D10_09_after_mistake02_0_2 [Panther]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Whoa, it's a Shadow![n][w][e]

[msg D10_09_after_mistake02_0_4 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7104 65535 0]Allow ME to say "hell no"![n]Let's clean him up, Joker![n][w][e]

[msg D10_09_after_mistake02_0_6 [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Shit, a Shadow![n][w][e]

[msg D10_09_after_mistake02_0_8 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]This wouldn't be the best path, even[n]if it did lead to your dream coming[n]true...[n][w][e]

[msg D10_09_after_answer03_st [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]A Shadow!? Wait, does that mean[n]we got it wrong?[n][w][e]

[msg D10_09_after_answer03_03 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]I guess we passed without them finding[n]any abnormalities... What a relief.[n][w][e]

[msg D10_09_after_answer03_04 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]But, what's he mean, "fulfilled"?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He doesn't even get that we just picked[n]all the answers we knew they'd wanna[n]hear![n][w][e]

[msg D10_09_after_answer03_03_2 [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Shut up, Skull...![n][w][e]

[msg D10_09_after_answer03_en [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Nice! That went rather well.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's keep that up![n][w][e]

[msg D10_09_after_answer03_no_2 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]I guess we passed without them finding[n]any abnormalities... What a relief.[n][w][e]

[msg D10_09_after_answer03_no_4 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2022 65535 0]Y-Yes, same here...[n][w][e]

[msg D10_09_after_answer03_no_5 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Even though we screwed up a bit.[n][w][e]

[msg D10_09_after_answer03_no_9 [Mona]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1169 65535 0]Well, we messed up a little back there,[n]but we've managed to make it through.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's get going.[n][w][e]

[msg D10_09_after_mistake03_0_2 [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4074 65535 0]Grrr... A Shadow![n][w][e]

[msg D10_09_after_mistake03_0_5 [Noir]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3041 65535 0]A Shadow!? Oh, shoot...[n][w][e]

[msg D10_09_after_mistake03_0_7 [Panther]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6183 65535 0]A Shadow![n][w][e]

[msg D10_09_after_mistake03_0_10 [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6047 65535 0]Tch, a Shadow! Of course we'd run into[n]one here![n][w][e]

[msg D10_09_after_mistake03_0_13 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A Shadow—get ready![n][w][e]

[msg D10_09_after_mistake03_0_16 [Crow]]
[s][bup 0 9 812 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54473 65535 0]Joker... Are you all right?[n][w][e]

[msg D10_09_hidden_room_first [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1027 65535 0]This place...[n][w][e]

[msg D10_09_hidden_room_first_2 [Noir]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3040 65535 0]Look! Outside the window![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's where the elevator leads, right?[n][w][e]

[msg D10_09_hidden_room_first_3 [Crow]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, they did call it an Exam Room.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54489 65535 0]They could very well be monitoring[n]the psychological state of every[n]"patient" in the room.[n][w][e]

[msg D10_09_hidden_room_first_4 [Panther]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You mean they might've been watching[n]us this whole time!? That's so creepy...[n][w][e]

[msg D10_09_hidden_room_first_5 [Mona]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1027 65535 0]"Creepy" is right—I just wish there was[n]some way we could benefit from this...[n][w][e]

[msg D10_09_hidden_room_first_6 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2100 65535 0]It does in fact look like they're observing[n]everyone who undergoes the exam.[n][w][e]

[msg D10_09_hidden_room_first_7 [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So there's another one in here...[n][w][e]

[msg D10_09_hidden_room_first_8 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Maybe we can peek at the results.[n]Let's take a look around.[n][w][e]

[msg D10_09_hidden_room_first_9 [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So there's another one in here, too...[n][w][e]

[msg D10_09_hidden_room_first_10 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]We might able to narrow down our[n]options. Let's see what we can learn.[n][w][e]

[msg D10_09_HiddenRoom01_Hint [Skull]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So that's how they spy on everyone[n]in the Exam Room.[n][w][e]
[s]......[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Sooo, uh... Are you guys as bored as I am?[n][w][e]

[msg D10_09_HiddenRoom01_Hint_2 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Depending on where we check,[n]we might be able to pick up[n]something beneficial...[n][w][e]

[msg D10_09_HiddenRoom02_Hint [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1130 65535 0]We can listen in on some conversations[n]here.[n][w][e]

[msg D10_09_HiddenRoom02_Hint_4 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]Damn, they're just throwin' treatment[n]at her right away...[n][w][e]

[msg D10_09_HiddenRoom02_Hint_5 [Fox]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Her reply was, "C: Steal my own heart[n]to heal."[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Admitting to having a problem is[n]practically begging for treatment[n]in this place.[n][w][e]

[msg D10_09_HiddenRoom02_Hint_7 [Mona]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]I don't hear much of anything...[n][w][e]

[msg D10_09_HiddenRoom03_Hint [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7167 65535 0]Hey, look, a Shadow. That must mean...[n][w][e]

[msg D10_09_HiddenRoom03_Hint_4 [Oracle]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]I don't think this is the right one.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]She answered, "E: Steal the one I love's[n]heart."[n][w][e]

[msg D10_09_HiddenRoom03_Hint_5 [Panther]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Happiness gained by depriving others[n]of their own is unhappiness..." I have[n]no idea what he means by that.[n][w][e]

[msg D10_09_HiddenRoom03_Hint_7 [Mona]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Hmmm... Nothing useful there.[n][w][e]

[msg D10_09_ExtraHuddle01_Fir [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's use this place to sort out our[n]next step, Joker.[n][w][e]

[msg D10_09_ExtraHuddle01_Ans [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]Unsure about something, Joker? We can[n]go over our intel again, if you'd like.[n][w][e]

[msg D10_09_ExtraHuddle01_Gen [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]Okay, here's another place we can use.[n][w][e]

[msg D10_09_ExtraHuddle02_Fir [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]Okay, here's another place we can use.[n][w][e]

[msg D10_09_ExtraHuddle02_Ans [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]Unsure about something, Joker? We can[n]go over our intel again, if you'd like.[n][w][e]

[msg D10_09_ExtraHuddle02_Gen [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]Okay, here's another place we can use.[n][w][e]

[msg D10_09_ExtraHuddle03_Fir [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]Okay, here's another place we can use.[n][w][e]

[msg D10_09_ExtraHuddle03_Ans [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]Unsure about something, Joker? We can[n]go over our intel again, if you'd like.[n][w][e]

[msg D10_09_ExtraHuddle03_Gen [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]Okay, here's another place we can use.[n][w][e]

[msg ALL_RESEARCH_END_mes_3rd [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]It may not be a lot, but we did gather[n]some information after all.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Why don't we try to hash out what we[n]think Dr. Maruki would consider the[n]right answer?[n][w][e]

[msg D10_09_question_not_answ [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1038 65535 0]If we're done collecting information,[n]then let's return to the room and[n][clr 2]discuss the answers[clr 27] there.[n][w][e]

[msg D10_09_question_not_chec [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Let's see what the next question is, Joker.[n][w][e]

[msg D10_09_Listen_end [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]We've learned all that we can about[n]the person who chose this answer.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Whether or not we choose this one,[n]that's up to you, Joker.[n][w][e]

[msg D10_09_Listen_not_end [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]We haven't learned enough about[n]the person who chose this answer...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Whether or not we choose this one,[n]that's up to you, Joker.[n][w][e]

[msg D10_09_acceptance_check__2 [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]...Allowing intruders to proceed?[n]How odd.[n][w][e]

[msg D10_09_acceptance_check__3 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]They must be awfully confident in their[n]"exam" techniques—at any rate, such[n]progression should work in our favor.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We should make sure we get our act[n]straight for this.[n][w][e]

[msg D10_09_acceptance_check__7 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54411 65535 0]And what exactly comprises these[n]examinations?[n][w][e]

[msg D10_09_acceptance_check__11 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]So, all we have to do is choose the[n]answer we believe to be correct.[n][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Although I'm a bit hesitant to find out[n]what they mean by "treatment"...[n][w][e]

[msg D10_09_acceptance_check__12 [Oracle]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Examine a person's heart, find their pain[n]and regret, then distort their cognition...[n][w][e]
[s]This is just the Palace version of what[n]Dr. Maruki does in real life.[n][w][e]

[msg D10_09_acceptance_check__13 [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Buuut, if we make a mistake, does[n]that mean they're going to change[n]our cognitions?[n][w][e]

[msg D10_09_acceptance_check__14 [Oracle]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's probably confined to the real[n]world—here, they probably mess with[n]people's heads some other way.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Like, maybe they hook you up to[n]some machine and just BZZZZZT![n][w][e]

[msg D10_09_acceptance_check__15 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7176 65535 0]Hey! Don't scare me like that...[n][w][e]

[msg D10_09_acceptance_check__16 [Queen]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, whatever form his treatment[n]takes, I'm sure we want no part of it[n]for ourselves.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Standing here attempting to imagine it[n]won't do us any good, though. Let's take[n]the exam and see where we wind up.[n][w][e]

[msg D10_09_back_block [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1111 65535 0]Like the receptionist said, it's probably[n]better that we don't go back at this point.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We don't want to make a wrong move[n]and raise the security level.[n][w][e]

