[msg SCN_LOCK_04_mes02 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It won't open?[n][w][e]

[msg SCN_LOCK_04_mes03 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, it means the public isn't accepting[n]enough of us yet.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's how it's been for all the previous[n]ones as well.[n][w][e]

[msg SCN_LOCK_04_mes04 [Queen]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A wall that doesn't open unless we[n]are accepted... It's almost akin to the[n]entertainment industry.[n][w][e]

[msg SCN_LOCK_04_mes05 [Panther]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]When you put it that way, it's actually[n]a little depressing that we can't get[n]through...[n][w][e]

[msg SCN_LOCK_04_mes06 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, so that's what's been goin' on? Damn...[n][w][e]

[msg SCN_LOCK_CLEAR_04_mes01 [Queen]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It opened...[n][w][e]

[msg SCN_LOCK_CLEAR_04_mes02 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sweet, now we can keep movin'.[n][w][e]

[msg SCN_LOCK_CLEAR_04_mes03 [Mona]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Just be careful, okay? The deeper we go,[n]the stronger the enemies get.[n][w][e]

