[msg D08_01_NPC_TALK_08_mes02 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]The hell is he talkin' about, "end"!?[n]This is bullshit![n][w][e]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Goddammit... Who the hell's lockin' all[n]these people up?[n][w][e]

[msg D08_01_NPC_TALK_09_mes02 [Queen]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]The world's going to end?[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What does he mean by that? It's more[n]than just some offhand comment, right?[n][w][e]

[msg D08_01_NPC_TALK_10_mes02 [Fox]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4141 65535 0]Destruction is... pleasing? He cannot be[n]in his right mind.[n][w][e]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It is as though he wishes for the world[n]to end...[n][w][e]

[msg D08_01_NPC_TALK_11_mes02 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Is she talkin' about Kamoshida and all[n]the others?[n][w][e]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I dunno how to put this... It's almost like[n]our targets were still more human than[n]all these people in here...[n][w][e]

[msg D08_01_NPC_TALK_12_mes02 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9028 65535 0]So he just wants to see the world from[n]online, huh?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I know how that might feel, but it gets old[n]after a while. I can speak from experience...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]And besides that, what's "happening[n]soon"?[n][w][e]

[msg D09_05_SCN_BTL02_mes02 [Mona]]
[s]This is it... The place where I was born...[n][w][e]

[msg D09_05_SCN_BTL02_mes03 [Skull]]
[s]H-Here? The hell is it!?[n][w][e]

[msg D09_05_SCN_BTL02_mes04 [Mona]]
[s]I don't know... I can't remember[n]anything more...[n][w][e]

[msg D09_05_SCN_BTL02_mes07 [Fox]]
[s]Hmph, what foul timing... Let us[n]defeat it before it attempts to enlist[n]reinforcements![n][w][e]

