[msg e511_630_mes_Start [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]We will surely be walking into a fight—[n]have you finished your preparations?[n][w][e]

[msg e511_630_mes_01 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]Mm... Then let us return when[n]we're ready.[n][w][e]

[msg e511_630_mes_02 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4035 65535 0]Very well. Let's go![n][w][e]

[msg D10_12_researcher_enemy0 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Enemies, Joker! ...Hm? Their apparel...[n][w][e]

[msg D10_12_researcher_enemy0_2 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Are those... lab coats? Why are[n]Shadows wearing lab coats in[n]a sports arena?[n][w][e]
[s]What could Dr. Maruki see this place as?[n][w][e]

[msg D10_12_get_map_start [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4090 65535 0]This appears to be a floor plan of[n]the Palace.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It's quite thorough... and it seems[n]that we still have a long way to go.[n][w][e]

[msg D10_12_get_map02 [Panther]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]"Maruki Cognitive Psience Laboratory"...[n][w][e]

[msg D10_12_get_map03 [Skull]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]This Palace is a lab!?[n][w][e]

[msg D10_12_get_map04 [Crow]]
[s][bup 0 9 801 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]You really hadn't figured that out yet?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Given Maruki's past and the Palace's[n]appearance we've seen so far, it wasn't[n]difficult to deduce.[n][w][e]

[msg D10_12_get_map05 [Skull]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7195 65535 0]Shuddup! This place is just so weird that[n]I didn't bother thinkin' about it yet![n][w][e]

[msg D10_12_get_map05_insert0 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]You get me, don't you, [fName]!?[n][w][e]

[msg D10_12_get_map06 [Skull]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54215 65535 0]...For real?[n][w][e]

[msg D10_12_get_map07 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]A Palace's appearance is based on what[n]its ruler thinks of someone or something.[n][w][e]

[msg D10_12_get_map08 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7048 65535 0]Yeah! Take that![n][w][e]

[msg D10_12_get_map09 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]...A Palace's appearance is based on[n]what its ruler thinks of someone or[n]something.[n][w][e]

[msg D10_12_get_map10 [Crow]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]In Takuto Maruki's case, he must[n]think of this stadium as a laboratory.[n][w][e]

[msg D10_12_get_map11 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yeah, I get that part—but why[n]the stadium, of all places?[n][w][e]

[msg D10_12_get_map12 [Violet]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Oh... That reminds me of something[n]I heard a while ago.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Before starting construction on the[n]stadium, there were apparently plans[n]to build some kind of research facility.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I wonder, could it have anything to do[n]with that...?[n][w][e]

[msg D10_12_get_map_end [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8038 65535 0]It's possible, but for now, we should[n]focus on progress in the Palace rather[n]than trying to answer questions.[n][w][e]

[msg D10_12_1st_passcode_lock [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uh-oh. That door's security looks[n]super-strict, and there isn't even[n]an ID scanner on it...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Let's take a closer peek![n][w][e]

[msg D10_12_1st_passcode_lock_3 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Gaaah, it talked! Ahem... But that's not[n]the part that matters now.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]What's it talkin' about, Doc losin'[n]something? Is this some kinda riddle?[n][w][e]

[msg D10_12_1st_passcode_lock_4 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9128 65535 0]That's a security question, like when[n]you reset a password—only the one[n]person's supposed to know the answers.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That's how you end up with private[n]information being used like a key.[n][w][e]

[msg D10_12_1st_passcode_lock_5 [Mona]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I see. So, we need information on[n]Maruki's life...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Well, this is his own Palace. I'd bet we'll[n]find some clues to the answer if we look[n]around throroughly enough.[n][w][e]

[msg D10_12_1st_passcode_lock_6 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7052 65535 0]Alright, if that's the plan, then let's[n]get to clue huntin'![n][w][e]

[msg D10_12_1st_passcode_lock_7 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Don't we need to look for clues first,[n]Joker?[n][w][e]

[msg D10_12_1st_passcode_lock_9 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]I know the answer after watching[n]that video...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I assume you know as well? You can[n]do the honors.[n][w][e]

[msg D10_12_1st_passcode_lock_12 [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8141 65535 0]You seem to be wrong there, Joker.[n]Give it another try.[n][w][e]

[msg D10_12_1st_passcode_lock_14 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54241 65535 0]Aw yeah! Nailed it![n][w][e]

[msg D10_12_1st_passcode_lock_15 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Joker, let's take a closer look at that[n]mega-secure door.[n][w][e]

[msg D10_12_get_map_start_bef [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wait... What is this?[n][w][e]

[msg D10_12_wall_vanish_start [Noir]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Look! The cables are gone![n][w][e]

[msg D10_12_wall_vanish_01 [Fox]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Rather fortuitous that we tried out the[n]console we found in Mementos—now[n]we can proceed.[n][w][e]

[msg D10_12_wall_vanish_end [Violet]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57026 65535 0]Okay! Let's go, Senpai![n][w][e]

[msg D10_12_find_boss_start [Queen]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Hold on—look over there![n][w][e]

[msg D10_12_find_boss_01 [Fox]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Security is even tighter here,[n]apparently. They appear quite[n]formidable.[n][w][e]

[msg D10_12_find_boss_end [Crow]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That means this place must be[n]important. Let's take them out[n]whenever we're ready.[n][w][e]

[msg D10_12_1st_passcode_lock_16 [Oracle]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Hmm? Hang on, Joker...[n][w][e]

[msg note_find_reaction_start [Violet]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]What could this be...? A diary?[n][w][e]

[msg note_find_reaction_01 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Looks like it. Judging from what's written[n]inside, it's most likely Maruki's...[n][w][e]

[msg note_find_reaction_watch [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Even that video from earlier... He just[n]really loves talking about himself.[n][w][e]

[msg note_find_reaction_notwa [Fox]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]It seems like he has written about things[n]in the past, but it looks like they are only[n]fragments of them...[n][w][e]

[msg note_find_reaction_end [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Doesn't look like it has any meaning to[n]it either.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Not sure if it'll come in handy for the[n]investigation, but let's hold on to it and[n]see if we can find other ones.[n][w][e]

