[msg GOTO_DUNGEON_mes01 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]All right, Joker... What do you want to do?[n][w][e]

[msg GOTO_DUNGEON_mes02 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Oh, sure thing. Make sure that you're[n]fully prepared.[n][w][e]

[msg GOTO_DUNGEON_mes03 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Ooh, I'm always down for a little bit[n]of dress up![n][w][e]
[s]What should we go with?[n][w][e]

[msg GOTO_DUNGEON_mes04 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1067 65535 0]Heheh, roger that. I hope you're looking[n]forward to my appearance![n][w][e]

[msg GOTO_DUNGEON_mes05 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1048 65535 0]All right, I'm up for something[n]extraordinary! I hope you look[n]forward to my new appearance![n][w][e]

[msg GOTO_DUNGEON_mes06 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1166 65535 0]I see! Well, I guess I am pretty[n]good-looking as is![n][w][e]

[msg GOTO_DUNGEON_mes07 [Mona]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1067 65535 0]You got it—I'll show you just how cool[n]I can look![n][w][e]

