[msg D05_BRIEFING_010_mes01 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I wonder what this giant place's[n]Treasure's gonna be like.[n][w][e]

[msg D05_BRIEFING_010_mes02 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'd expect it to be related to these[n]buildings somehow...[n][w][e]
[s]But I can't imagine what that could end[n]up meaning.[n][w][e]

[msg D05_BRIEFING_010_mes03 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Speakin' of that, what're these buildin's[n]for anyways?[n][w][e]

[msg D05_BRIEFING_010_mes04 [Panther]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm not sure. That's just another thing[n]we'll need to investigate.[n][w][e]

