[msg SAFE_RECOVERY_OK_PC03_me [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All right, let's rest up, guys![n][w][e]

[msg SAFE_RECOVERY_OK_PC09_me [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Then let's rest.[n][w][e]

[msg SAFE_RECOVERY_OK_END_PC0 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew... That helped a little.[n][w][e]

[msg SAFE_RECOVERY_OK_END_PC0_2 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That helped us recover a bit.[n][w][e]

[msg SAFE_RECOVERY_OK_END_PC0_3 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Phew... That definitely helped.[n][w][e]

[msg SAFE_RECOVERY_OK_END_PC0_4 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]That definitely helped us recover a bit.[n][w][e]

[msg SAFE_RECOVERY_NG_PC03_me [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hey, you don't have any tools you[n]can use.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Make sure to prepare beforehand.[n][w][e]

[msg SAFE_RECOVERY_NG_PC09_me [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It doesn't seem like you have tools[n]you can use?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maybe you forgot to prepare?[n][w][e]

[msg SAFE_RECOVERY_NG_PC03_me_2 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? Doesn't seem like anyone here[n]is tired.[n][w][e]

[msg SAFE_RECOVERY_NG_PC09_me_2 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It doesn't seem like anyone here is tired.[n][w][e]

[msg DUNGEON_BREIFING_USE_ITE [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Didn't you have something we could use[n]to recover? Should we use that and rest?[n][w][e]

[msg DUNGEON_BREIFING_USE_ITE_2 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]It seems like you have something we[n]could use to recover. Would you like[n]to use it?[n][w][e]

[msg CHECK_USE_ITEM_PC03_mes0 [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I'm glad you came prepared, Joker![n]All right then, let's rest up.[n][w][e]

[msg CHECK_USE_ITEM_PC09_mes0 [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I knew you'd be prepared. Let's rest.[n][w][e]

[msg CANCEL_USE_ITEM_PC03_mes [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? Are we not resting?[n][w][e]

[msg CANCEL_USE_ITEM_PC09_mes [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm? We're not resting?[n][w][e]

[msg NO_EFF_USE_ITEM_PC03_mes [Mona]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]There's no point in using that.[n][w][e]

[msg NO_EFF_USE_ITEM_PC09_mes [Crow]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I don't think there's any point in[n]using that.[n][w][e]

