[msg characoop_Reiji_00 [Skull]]
[s]I got this, man![n][w][e]

[msg characoop_Morgana_00 [Mona]]
[s]All right, it's my turn![n][w][e]

[msg characoop_Ann_00 [Panther]]
[s]Leave it to me![n][w][e]

[msg characoop_Yugo_00 [Fox]]
[s]Allow me to follow up on that![n][w][e]

[msg characoop_Makoto_00 [Queen]]
[s]Now's my chance![n][w][e]

[msg characoop_Ranko_00 [Noir]]
[s]Should I help out?[n][w][e]

[msg characoop_Futaba_00 [Oracle]]
[s]I'll create an opening, so we'll switch[n]during then. Got it?[n][w][e]

[msg characoop_Akechi_00 [Crow]]
[s]I'll finish it off![n][w][e]

[msg characoop_Uzuki_00 [Violet]]
[s]Please, leave it to me![n][w][e]

[msg characoop_special_Ryuji_ [Skull]]
[s]Let's do this together![n][w][e]

[msg characoop_special_Morgan [Mona]]
[s]Let's finish this![n][w][e]

[msg characoop_special_Anne_0 [Panther]]
[s]Here we go![n][w][e]

[msg characoop_special_Yusuke [Fox]]
[s]We strike as one![n][w][e]

[msg characoop_special_Makoto [Queen]]
[s]Now's our chance![n][w][e]

[msg characoop_special_Haru_0 [Noir]]
[s]Let us finish this together![n][w][e]

[msg characoop_special_Futaba [Oracle]]
[s]I'll create an opening, so we'll switch[n]during then. Got it?[n][w][e]

[msg characoop_special_Akechi [Crow]]
[s]We'll finish it together![n][w][e]

[msg characoop_special_Uzuki_ [Violet]]
[s]We'll be the ones to end this![n][w][e]

[msg characoop_KuroAkechi_00 [Crow]]
[s]Want me to kill it?[n][w][e]

