[msg MSG_014_0_0 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Ooh! That sounds awesome! I'm Skull![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Skull]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]What do we do about this one's[n]code name?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Skull]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]...How 'bout "Mona"?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Well, if Joker thinks it's easier to call me[n]that, then I'll go with it.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Mona]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]All right. From here on out, we're Joker,[n]Skull, and Mona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]We need to be absolutely thorough about[n]using those code names from now on![n][f 1 3 65535][w][e]

